import {beforeEach,describe,expect,it,vi} from "vitest";
const state=vi.hoisted(()=>({po:"PO-TEST",cycle:"MONTHLY",invoices:[] as unknown[],holidayFetch:vi.fn(async()=>[{date:"2026-12-25"},{date:"2026-12-28"}])}));
vi.mock("./billing-periods",async original=>({...await original<typeof import("./billing-periods")>(),englandBankHolidays:state.holidayFetch}));
vi.mock("./prisma",()=>({prisma:{billingPeriod:{findUnique:async()=>({id:"period",label:"December",cycle:state.cycle,periodStart:new Date("2026-12-01"),periodEnd:new Date("2026-12-31"),bankHolidayDates:["2026-12-25","2026-12-28"]})},student:{findMany:async()=>[{id:"client",displayName:"Example Client",startDate:new Date("2026-01-01")}]},billingProfile:{findMany:async()=>[{id:"profile",studentId:"client",payerName:state.cycle==="LBE"?"London Borough of Enfield":"Private payer",purchaseOrderNumber:state.po,billingAddress:"Example address",activeFrom:new Date("2026-01-01"),vatRate:0,chargeRules:[{id:"rule",activeFrom:new Date("2026-01-01"),activeTo:null,chargeType:"FULL_DAY",active:true,attendanceDependency:"FUNDED",unitType:"DAY",applicableWeekdays:[],fundedDayCount:12,rate:40,vatRate:0}]}]},invoice:{findMany:async()=>state.invoices}}}));
import {billingClientRoster,billingChoices} from "./billing-wizard";
beforeEach(()=>{state.po="PO-TEST";state.cycle="MONTHLY";state.invoices=[];state.holidayFetch.mockClear()});
describe("billing date and holiday previews",()=>{
 it("lets the user opt into holiday deductions for other clients",async()=>{const off=await billingChoices("period",false),on=await billingChoices("period",true);expect(off.rows[0].total).toBe(480);expect(on.rows[0].total).toBe(400);expect(on.rows[0].quantity).toBe(10);expect(state.holidayFetch).toHaveBeenCalledTimes(1)});
 it("defaults LBE to saved holiday deductions but allows an explicit override",async()=>{state.cycle="LBE";expect((await billingChoices("period")).rows[0].total).toBe(400);expect((await billingChoices("period",false)).rows[0].total).toBe(480);expect(state.holidayFetch).not.toHaveBeenCalled()});
 it("supports manual dates without writing or replacing a saved period",async()=>{const result=await billingChoices({periodStart:"2026-12-02",periodEnd:"2026-12-30",cycle:"MONTHLY"},true);expect(result.period.id).toBeNull();expect(result.period.label).toContain("2 Dec 2026");expect(result.rows[0].total).toBe(400)});
 it("identifies a partially overlapping issued invoice against the client",async()=>{state.invoices=[{id:"invoice",studentId:"client",billingProfileId:"profile",invoiceNumber:"STARS-TEST",billingRun:{periodStart:new Date("2026-12-02"),periodEnd:new Date("2026-12-30")}}];const row=(await billingChoices("period")).rows[0];expect(row.error).toBeNull();expect(row.overlap?.invoiceNumber).toBe("STARS-TEST");expect(row.existing).toBeNull()});
});

describe("manual billing client visibility",()=>{
 it("shows the client roster before dates are supplied without a preparation token",async()=>{const result=await billingClientRoster();expect(result.rows).toHaveLength(1);expect(result.rows[0].name).toBe("Example Client");expect(result.token).toBe("");expect(result.period).toBeNull();expect(result.rows[0].total).toBeNull()});
 it("includes LBE clients in manual dates regardless of the legacy group",async()=>{state.cycle="LBE";const result=await billingChoices({periodStart:"2026-12-02",periodEnd:"2026-12-30",cycle:"MONTHLY"},false);expect(result.rows).toHaveLength(1);expect(result.rows[0].payer).toBe("London Borough of Enfield");expect(result.rows[0].total).toBe(480)});
 it("includes other clients in an all-client manual period",async()=>{const result=await billingChoices({periodStart:"2026-12-02",periodEnd:"2026-12-30",cycle:"ALL"},false);expect(result.rows).toHaveLength(1);expect(result.period.id).toBeNull()});
 it("still filters saved periods by billing group",async()=>{state.cycle="LBE";const result=await billingChoices("period",false);expect(result.rows[0].payer).toBe("London Borough of Enfield")});
});

it("warns but does not block LBE without a PO",async()=>{state.cycle="LBE";state.po="";const row=(await billingChoices("period",false)).rows[0];expect(row.error).toBeNull();expect(row.warning).toContain("No PO reference");expect(row.total).toBe(480)});
