export const billingHelpTopics = [
  { id: "dates", title: "Choose billing dates", target: "billing-dates", keywords: ["date", "period", "saved"], content: "Choose Saved period for a configured period, or Enter dates to set From and To. All clients across billing groups appear immediately. Click Use these dates to calculate amounts and check billing details. Manual dates do not edit saved periods. Dates must cover 1 to 62 days. Check the dates again before creating invoices." },
  { id: "holidays", title: "Exclude bank holidays", target: "billing-bank-holidays", keywords: ["holiday", "exclude", "deduct", "lbe"], content: "Exclude bank holidays switches holiday deductions on or off for this batch. It starts On for saved LBE periods and Off for other or manual periods; switch it on for manual billing when required. The count below it shows how many holidays fall within the chosen dates. Agreed funded days are reduced by that count, regardless of attendance weekdays. The GOV.UK England and Wales calendar is used. If verification fails, retry; do not guess a deduction. A manual invoice total is the final amount you enter and is not reduced again." },
  { id: "clients", title: "Select clients", target: "billing-clients", keywords: ["select", "client", "student", "search", "all", "missing"], content: "No clients are selected automatically. Tick individual clients or Select all, then check the selected count. Search filters the visible names; Select all applies to the whole eligible list. Show all reveals the remaining clients. Saved periods use active status, funding dates and the billing group. Manual dates show all clients, including inactive clients for interim or historic billing; warnings explain any dates or billing details that need attention. A warning explains missing payer, address or PO information. Use Fix details or deselect that client." },
  { id: "amounts", title: "Choose how totals are entered", target: "billing-method", keywords: ["agreed", "funded", "rate", "manual", "amount"], content: "Use agreed amounts fills totals from agreed funded days and the configured rate, VAT and holiday deductions. Attendance does not affect charges. Funded days are optional: where no count is saved, prepare billing and enter the agreed billable days during review. Whole or half days can be entered. If needed, choose a manual total instead. Enter totals myself lets you type each final invoice total, including VAT. Enter positive amounts with at most two decimal places. An agreed day count is not automatically prorated when you choose a shorter manual period; review the total." },
  { id: "review", title: "Check and amend totals", target: "billing-totals", keywords: ["review", "check", "total", "reason", "change", "vat", "zero"], content: "Click Prepare billing after choosing dates and clients. No total is required before preparation. Review every client and payer. Adjust Billable days to recalculate the total from the saved rate and VAT. You can choose Enter totals myself on the first step if a final amount is needed instead. A change of at least the greater of £10 and 5%, or a total without an agreed amount, requires a short reason. The original and final amount, user, time and reason are audited. Back preserves your entries. A manual total appears as QTY 1 at its net rate; VAT remains included in the final total." },
  { id: "create", title: "Issue invoices safely", target: "billing-actions", keywords: ["create", "confirm", "duplicate", "replace", "disabled", "button"], content: "The summary stays below the client list. Its message explains a disabled button: choose dates and select clients. On the review screen, enter valid billable days or an optional manual total. On Review totals, supply required reasons and confirm any replacement. Issue invoices asks you to confirm the count and combined total. Repeated clicks or retrying the same request will not create duplicates. Confirm Issue again when an invoice already exists. Exact-period replacements keep older PDFs in history; overlapping interim periods create additional invoices. A missing LBE PO reference is a warning and does not stop issuing. Clive never clicks Issue invoices or changes records for you." },
  { id: "history", title: "Find and download previous invoices", target: "billing-history", keywords: ["previous", "history", "historic", "label", "download", "pdf", "po", "reference"], content: "Open Previous invoices to search invoice numbers or PO references and filter by month, client, payer or status. Older invoices without a saved client name show their original billing run label. Choose Earlier versions for replaced invoices. View opens a PDF; Download saves it. After creating a batch, Download invoices prepares a ZIP, then use its download link. PDFs show Client, From–To, service, QTY, Rate, NET and TOTAL, and Your Ref for the PO. Issued PDFs do not change when settings change. Creating or downloading does not send email." },
  { id: "settings", title: "Fix billing settings", target: "billing-help", keywords: ["setting", "payer", "profile", "permission", "automatic"], content: "Billing settings holds saved periods, rates, payer details, PO references and automatic preparation. Access depends on your account permissions. Routine invoicing does not require opening settings. Automatic preparation creates review work, not issued or emailed invoices. Advanced billing retains historical controls and authorised additional services. If your Issue button says an authorised manager is required, ask a manager with billing editing and approval access." },
] as const;
export type BillingHelpTopic = {id:string;title:string;target:string;keywords:readonly string[];content:string};
export function billingHelpForQuestion(question: string): BillingHelpTopic {
  const words: string[] = (question.toLowerCase().match(/[a-z]+/g) || []).map(word=>word.replace(/s$/, ""));
  return [...billingHelpTopics].sort((a, b) => b.keywords.filter(key => words.includes(key.replace(/s$/, ""))).length - a.keywords.filter(key => words.includes(key.replace(/s$/, ""))).length)[0];
}
