import {beforeEach,describe,expect,it,vi} from "vitest";
const state=vi.hoisted(()=>({cycle:"MONTHLY",invoices:[] as unknown[],holidayFetch:vi.fn(async()=>[{date:"2026-12-25"},{date:"2026-12-28"}])}));
vi.mock("./billing-periods",async original=>({...await original<typeof import("./billing-periods")>(),englandBankHolidays:state.holidayFetch}));
vi.mock("./prisma",()=>({prisma:{billingPeriod:{findUnique:async()=>({id:"period",label:"December",cycle:state.cycle,periodStart:new Date("2026-12-01"),periodEnd:new Date("2026-12-31"),bankHolidayDates:["2026-12-25","2026-12-28"]})},student:{findMany:async()=>[{id:"client",displayName:"Example Client",startDate:new Date("2026-01-01")}]},billingProfile:{findMany:async()=>[{id:"profile",studentId:"client",payerName:state.cycle==="LBE"?"London Borough of Enfield":"Private payer",purchaseOrderNumber:"PO-TEST",billingAddress:"Example address",activeFrom:new Date("2026-01-01"),vatRate:0,chargeRules:[{id:"rule",activeFrom:new Date("2026-01-01"),activeTo:null,chargeType:"FULL_DAY",active:true,attendanceDependency:"FUNDED",unitType:"DAY",applicableWeekdays:[],fundedDayCount:12,rate:40,vatRate:0}]}]},invoice:{findMany:async()=>state.invoices}}}));
import {billingChoices} from "./billing-wizard";
beforeEach(()=>{state.cycle="MONTHLY";state.invoices=[];state.holidayFetch.mockClear()});
describe("billing date and holiday previews",()=>{
 it("lets the user opt into holiday deductions for other clients",async()=>{const off=await billingChoices("period",false),on=await billingChoices("period",true);expect(off.rows[0].total).toBe(480);expect(on.rows[0].total).toBe(400);expect(on.rows[0].quantity).toBe(10);expect(state.holidayFetch).toHaveBeenCalledTimes(1)});
 it("defaults LBE to saved holiday deductions but allows an explicit override",async()=>{state.cycle="LBE";expect((await billingChoices("period")).rows[0].total).toBe(400);expect((await billingChoices("period",false)).rows[0].total).toBe(480);expect(state.holidayFetch).not.toHaveBeenCalled()});
 it("supports manual dates without writing or replacing a saved period",async()=>{const result=await billingChoices({periodStart:"2026-12-02",periodEnd:"2026-12-30",cycle:"MONTHLY"},true);expect(result.period.id).toBeNull();expect(result.period.label).toContain("2 Dec 2026");expect(result.rows[0].total).toBe(400)});
 it("identifies a partially overlapping issued invoice against the client",async()=>{state.invoices=[{id:"invoice",studentId:"client",billingProfileId:"profile",invoiceNumber:"STARS-TEST",billingRun:{periodStart:new Date("2026-12-02"),periodEnd:new Date("2026-12-30")}}];expect((await billingChoices("period")).rows[0].error).toContain("Dates overlap invoice STARS-TEST")});
});
