export const careFields = [
 ["source","Information supplied by (name, role, date and contact)"],
 ["consent","Consent / authority to hold and share this information"],
 ["birth","Date of birth, other names, gender, nationality and ethnicity"],
 ["partner","Partner / close family details"],
 ["address","Home and other addresses, telephone, email and social accounts"],
 ["description","Height, build, hair, complexion, identifying marks and other physical features"],
 ["tracking","Tracking devices, medical ID and alert information"],
 ["health","Health conditions, symptoms, allergies and essential care needs"],
 ["medication","Medication and consequences of missed doses (short and long term)"],
 ["mobility","Walking aids, transfers and walking distance"],
 ["behaviour","Risks, phobias, triggers and response when upset"],
 ["communication","Languages, communication needs and ways to reassure"],
 ["money","Access to money and relevant financial information"],
 ["transport","Travel passes, nearby stops, regular routes, vehicles and transport providers"],
 ["employment","Current and past work / education and contact details"],
 ["places","Significant addresses, friends, worship, shops, pharmacy, clinics and favourite places"],
 ["interests","Interests, hobbies, indoor/outdoor activities and community groups"],
 ["routine","Weekly routine, including mornings, afternoons and evenings"],
 ["missing","Previous missing episodes: circumstances, locations found and reasons"],
 ["professionals","GP, social worker, other professionals, representatives and contact details"],
 ["hazards","RAMS: identified hazards and who may be harmed"],
 ["controls","RAMS: agreed controls, supervision and protective measures"],
 ["method","RAMS: activity steps, equipment, responsibilities and safety checks"],
 ["emergency","RAMS: stop conditions and emergency response"],
 ["review","Review owner and next review date"],
 ["further","Further information"],
 ["completedBy","Person completing the information: relationship, address and contact details"],
] as const;
export const herbertSource="https://www.met.police.uk/SysSiteAssets/media/downloads/central/advice/herbert-protocol/herbert-protocol-form.pdf";
