// A paginated profile export with a current JPEG photograph on the first page.
const escape=(s:string)=>s.normalize("NFKD").replace(/[^\x20-\x7e]/g," ").replace(/\\/g,"\\\\").replace(/\(/g,"\\(").replace(/\)/g,"\\)");
export function carePdf(title:string,lines:string[],photo?:{data:Buffer;width:number;height:number}) {
 const wrapped=lines.flatMap(line=>line.split(/\r?\n/).flatMap(part=>{const chunks=[];let remaining=part;while(remaining.length>88){let end=remaining.lastIndexOf(" ",88);if(end<1)end=88;chunks.push(remaining.slice(0,end));remaining=remaining.slice(end).trimStart();}chunks.push(remaining);return chunks;}));
 const pages:string[][]=[];let offset=0;do{const count=pages.length===0&&photo?34:47;pages.push(wrapped.slice(offset,offset+count));offset+=count;}while(offset<wrapped.length);
 const font=3+pages.length*2,image=font+1,objects:Array<Buffer|string>=["<< /Type /Catalog /Pages 2 0 R >>",`<< /Type /Pages /Kids [${pages.map((_,i)=>`${3+i*2} 0 R`).join(" ")}] /Count ${pages.length} >>`];
 pages.forEach((lines,i)=>{const top=i===0&&photo?548:740;const body=[`BT /F1 18 Tf 42 800 Td (STARS Connect) Tj ET`,`BT /F1 12 Tf 42 777 Td (${escape(title)}) Tj ET`,...(i===0&&photo?[`q ${Math.min(160,160*photo.width/photo.height)} 0 0 ${Math.min(160,160*photo.height/photo.width)} 42 570 cm /Photo Do Q`]:[]),...lines.map((line,j)=>`BT /F1 10 Tf 42 ${top-j*14} Td (${escape(line)}) Tj ET`),`BT /F1 8 Tf 42 28 Td (Confidential - page ${i+1} of ${pages.length}) Tj ET`].join("\n");objects.push(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 ${font} 0 R >> ${photo?`/XObject << /Photo ${image} 0 R >>`:""} >> /Contents ${4+i*2} 0 R >>`,`<< /Length ${Buffer.byteLength(body)} >>\nstream\n${body}\nendstream`);});
 objects.push("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>");if(photo)objects.push(Buffer.concat([Buffer.from(`<< /Type /XObject /Subtype /Image /Width ${photo.width} /Height ${photo.height} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${photo.data.length} >>\nstream\n`),photo.data,Buffer.from("\nendstream")]));
 const parts=[Buffer.from("%PDF-1.4\n")],offsets=[0];let length=parts[0].length;objects.forEach((o,i)=>{offsets.push(length);const b=Buffer.concat([Buffer.from(`${i+1} 0 obj\n`),Buffer.isBuffer(o)?o:Buffer.from(o),Buffer.from("\nendobj\n")]);parts.push(b);length+=b.length;});parts.push(Buffer.from(`xref\n0 ${objects.length+1}\n0000000000 65535 f \n${offsets.slice(1).map(n=>`${String(n).padStart(10,"0")} 00000 n `).join("\n")}\ntrailer << /Size ${objects.length+1} /Root 1 0 R >>\nstartxref\n${length}\n%%EOF`));return Buffer.concat(parts);
}
