import type {User} from "@prisma/client";import {taskOverview} from "./task-overview";import {taskOwners} from "./task-ownership";import {CAPABILITIES as C,hasCapability} from "./permissions";import {londonDay,sortTasks,taskClosed,type QueueTask} from "./task-queue";import {prisma} from "./prisma";import {canReviewStaffRequest} from "./staff-task-access";
const words=(s:string):string[]=>s.toLowerCase().match(/[a-z0-9]+/g)||[];
export function matchTaskQuery(rows:QueueTask[],question:string){const q=question.toLowerCase(),now=londonDay();let result=rows.filter(r=>/completed|closed|history/.test(q)?taskClosed(r.status):!taskClosed(r.status));if(/overdue/.test(q))result=result.filter(r=>r.dueDate&&londonDay(new Date(r.dueDate))<now);if(/evidence|proof|certificate/.test(q))result=result.filter(r=>r.awaitingEvidence||r.status==='AWAITING_EVIDENCE'||/evidence|certificate/.test(r.title.toLowerCase()));if(/compliance/.test(q))result=result.filter(r=>r.category==='Compliance'||r.category==='Operations');if(/monday|review/.test(q)&&!/assign|owner|evidence/.test(q)){const end=new Date();const delta=(1-end.getDay()+7)%7;end.setDate(end.getDate()+delta);result=result.filter(r=>r.decision||r.awaitingEvidence||r.dueDate&&londonDay(new Date(r.dueDate))<=londonDay(end))}const owner=result.filter(r=>r.owner!=='Unassigned'&&words(r.owner).some(w=>w.length>2&&words(q).includes(w)));if(/own/.test(q)&&!/assign|change/.test(q))result=/\bme\b|\bmy\b/.test(q)?result:owner;if(/high priority|urgent/.test(q))result=result.filter(r=>['HIGH','URGENT','CRITICAL'].includes(r.priority));if(/\bopen\b|summaris|summariz|details/.test(q)){const terms=words(q).filter(w=>!['open','show','me','the','task','action','details','summarise','summarize','of','please','tasks'].includes(w));if(terms.length)result=result.filter(r=>terms.some(w=>words(r.title).includes(w)))}return sortTasks(result)}
export async function liveCliveAnswer(user:User,question:string,pathname:string){const q=question.toLowerCase(),can=(c:typeof C[keyof typeof C])=>hasCapability(user.role,c,user.permissionOverrides);
 if(/task|overdue|awaiting evidence|what.*own|assign.*to|review.*monday|monday.*review|compliance gaps/.test(q)){
 if(!can(C.STAFF_TASKS))return {answer:'Tasks are not enabled for your account. Ask an administrator to review Tasks permissions.',mode:'live'};
 let rows=(await taskOverview(user)).rows;const currentTask=new URL(pathname,"https://local.invalid").searchParams.get("task");if(currentTask&&/this|current/.test(q))rows=rows.filter(r=>r.id===currentTask);
 const requests=await prisma.staffRequest.findMany({where:{organisationId:user.organisationId||'',status:{not:'DRAFT'}},include:{staff:{select:{displayName:true}}}});for(const r of requests.filter(r=>canReviewStaffRequest(user,r))){rows.push({id:r.id,source:'request',title:r.type==='CONCERN'?'Confidential concern':r.type.toLowerCase()+' request — '+r.staff.displayName,category:'Staff requests',status:r.status,priority:'NORMAL',owner:'Assigned reviewer',ownerId:r.assignedUserId,dueDate:r.dueDate?.toISOString(),awaitingEvidence:r.status==='AWAITING_EVIDENCE',decision:['NEW','IN_REVIEW'].includes(r.status),href:'/dashboard/staff/tasks?task='+r.id})}
 if(/assign|change.*owner/.test(q)){const people=await taskOwners(user);const titlePart=q.replace(/^.*?(?:assign|owner of|owner for)\s+/,'').split(/\s+to\s+/)[0];const meaningful=words(titlePart).filter(w=>!['the','task','this','action','change','owner','of'].includes(w));let tasks=rows.filter(r=>r.canChange&&!taskClosed(r.status));if(meaningful.length){const matches=tasks.filter(r=>meaningful.some(w=>words(r.title).includes(w)));tasks=matches.length?matches:tasks}const personPart=q.split(/\s+to\s+/).pop()||'';const candidates=/^(me|myself)\b/.test(personPart)?people.filter(p=>p.userId===user.id):people.filter(p=>words(p.displayName).some(w=>w.length>1&&words(personPart).includes(w)));return {answer:tasks.length?'Choose the correct task and person below. I will show the current and proposed owner; nothing changes until you confirm.':'No assignable task matched your permissions. Open the original workflow for clinical, fleet or approval tasks.',mode:'live',ownerProposal:{tasks:tasks.slice(0,20),people:candidates.length?candidates:people},links:tasks.slice(0,5).map(t=>({label:t.title,href:'/dashboard/staff/tasks?task='+t.id}))}}
 if(/edit|change|update/.test(q)&&!/owner|assign/.test(q))return {answer:'Choose the task, enter the proposed title, date or note, then review the old and new values before confirming. Status and approvals are unchanged.',mode:'live',editProposal:{tasks:rows.filter(r=>r.canChange&&!taskClosed(r.status)).slice(0,40)}};
 if(/create|draft|new task/.test(q)&&can(C.STAFF_RESOURCES_MANAGE)){return {answer:'I can prepare a draft task. Check the title, dates and note before confirming creation.',mode:'live',draftTask:{title:question.replace(/^.*?(?:task|called)\s*[:—-]?\s*/i,'').slice(0,180)||'New task',notes:'',dueDate:londonDay()},suggestedRoute:'/dashboard/staff/tasks?guide=create-task'}}
 rows=matchTaskQuery(rows,question);if(/\bmy\b|what.*(?:me|myself).*own/.test(q))rows=rows.filter(r=>r.ownerId===user.id);const facts=rows.slice(0,8);return {answer:rows.length?`${rows.length} matching task${rows.length===1?'':'s'} in your authorised records.\n`+facts.map(t=>`${t.title} — ${t.status.replaceAll('_',' ').toLowerCase()}; ${t.owner}; ${t.dueDate?'due '+londonDay(new Date(t.dueDate)):'no due date'}${t.awaitingEvidence?'; evidence outstanding':''}.${/detail|summaris|summariz|open/.test(q)?' '+(t.description||t.notes||'No notes recorded.')+' '+(t.evidence?.length||0)+' evidence link(s).':''}`).join('\n'):'No matching tasks were found in the records you can access. This does not certify compliance.',mode:'live',links:facts.map(t=>({label:t.title,href:'/dashboard/staff/tasks?task='+t.id})),suggestedRoute:'/dashboard/staff/tasks'};
 }
 if(/find|policy|rams|asset|inspection/.test(q)&&/find|search|where|show/.test(q)){const links:{label:string;href:string}[]=[];const types=[...(can(C.POLICY_VIEW)?['POLICY' as const]:[]),...(can(C.RAMS_VIEW)?['RAMS' as const]:[])];const records=await prisma.complianceRecord.findMany({where:{organisationId:user.organisationId||'',archivedAt:null,recordType:{in:types}},include:{versions:{where:{status:'PUBLISHED'},orderBy:{version:'desc'},take:1}}});const terms=words(q).filter(w=>!['find','the','a','policy','rams','show','me','where','is','relevant','approved'].includes(w));for(const r of records){const v=r.versions[0];if(v&&(!terms.length||terms.some(t=>words(v.title).includes(t))))links.push({label:`${v.title} · published version ${v.version}`,href:'/dashboard/premises/'+(r.recordType==='POLICY'?'policies':'rams')+'?record='+r.id})}if(/asset/.test(q)&&can(C.PREMISES_VIEW)){const assets=await prisma.premisesAsset.findMany({where:{active:true}});for(const a of assets.filter(a=>terms.some(t=>words(a.name).includes(t))))links.push({label:a.name,href:'/dashboard/premises/assets/'+a.qrToken})}if(links.length)return {answer:`Found ${links.length} authorised record${links.length===1?'':'s'}. Open a link to read the source.`,links:links.slice(0,12),mode:'live'};
 if(/find|search/.test(q))return {answer:'No matching published records were found. These libraries may not have been populated yet. I cannot invent a policy or requirement.',mode:'live'};
 }
 if(pathname.includes('/premises')&&/gap|prepare|inspection/.test(q))return {answer:'Open Attention required for recorded due dates, then Tasks for missing evidence and owners. The library is not a compliance certificate: review coverage and add the relevant records. Use Tests & Inspections to record the actual result and evidence.',mode:'local',suggestedRoute:'/dashboard/premises?guide=attention'};
 return null;
}
