import { z } from "zod";
const optionalText=(max:number)=>z.string().trim().max(max).nullable().optional();const optionalDate=z.string().date().nullable().optional().or(z.literal(""));
export const hazardInput=z.object({id:z.string().uuid().optional(),sortOrder:z.number().int().min(0).max(1000).default(0),hazard:z.string().trim().min(2).max(5000),whoMayBeHarmed:z.string().trim().min(2).max(5000),howTheyMayBeHarmed:z.string().trim().min(2).max(5000),existingControls:z.string().trim().min(2).max(10000),initialLikelihood:z.number().int().min(1).max(5),initialSeverity:z.number().int().min(1).max(5),furtherControls:optionalText(10000),actionOwnerId:z.string().uuid().nullable().optional(),targetDate:optionalDate,residualLikelihood:z.number().int().min(1).max(5),residualSeverity:z.number().int().min(1).max(5)});
export const riskAssessmentCreateInput=z.object({reference:z.string().trim().min(2).max(80),title:z.string().trim().min(2).max(191),categoryId:z.string().uuid().nullable().optional(),description:optionalText(20000),scope:optionalText(20000),premisesLocation:optionalText(191),relatedActivity:optionalText(191),relatedAssetId:z.string().uuid().nullable().optional(),assessorId:z.string().uuid().nullable().optional(),responsibleManagerId:z.string().uuid().nullable().optional(),assessmentDate:optionalDate,reviewDate:optionalDate,internalNotes:optionalText(20000),revisionNotes:optionalText(10000),tags:z.array(z.string().trim().min(1).max(80)).max(30).optional(),hazards:z.array(hazardInput).max(100).default([])}).strict();
export const riskAssessmentUpdateInput=riskAssessmentCreateInput.omit({reference:true}).partial().strict();
export const workflowCommentInput=z.object({comments:z.string().trim().max(10000).optional().default("")}).strict();
const methodStepInput=z.object({stage:z.string().trim().min(2).max(191),method:z.string().trim().min(2).max(10000),responsibleRole:optionalText(120),equipmentRequired:optionalText(5000),protectiveMeasures:optionalText(5000),safetyChecks:optionalText(5000),stopWorkConditions:optionalText(5000),emergencyResponse:optionalText(5000)});
const checklistInput=z.object({label:z.string().trim().min(2).max(191),required:z.boolean().default(true),completed:z.boolean().default(false)});
const participantInput=z.object({id:z.string().uuid(),name:z.string().trim().min(1).max(191),reference:z.string().trim().max(100).optional(),supportReviewRequired:z.boolean().optional(),supportConsideration:z.string().trim().max(500).optional()});
export const ramsDraftInput=z.object({reviewerId:z.string().uuid().nullable().optional(),approverId:z.string().uuid().nullable().optional(),staffGroups:z.array(z.string().max(100)).max(10).optional(),cliveAcceptances:z.array(z.string().uuid()).max(100).optional(),
 reference:z.string().trim().min(2).max(80),title:z.string().trim().min(2).max(191),activityDescription:z.string().trim().min(2).max(20000),location:z.string().trim().min(2).max(191),responsiblePerson:z.string().trim().min(2).max(191),assessmentAuthor:z.string().trim().min(2).max(191),assessmentDate:z.string().date(),reviewDate:z.string().date(),operationOccurrenceId:z.string().uuid().nullable().optional(),operationTitle:optionalText(191),students:z.array(participantInput).max(100),staff:z.array(participantInput).max(100),ppe:z.string().trim().max(10000).default(""),equipment:z.string().trim().max(10000).default(""),emergencyArrangements:z.string().trim().max(10000).default(""),methodStatement:z.string().trim().max(20000).default(""),additionalNotes:z.string().trim().max(20000).default(""),hazards:z.array(hazardInput).max(100),methodSteps:z.array(methodStepInput).max(100),checklistItems:z.array(checklistInput).max(100)
}).strict();
export const pageInput=z.coerce.number().int().min(1).max(100000).default(1);export const pageSizeInput=z.coerce.number().int().min(1).max(100).default(25);
