import{describe,expect,it}from"vitest";import{canTransition,isOverdue,notificationKey,organisationScope,riskScore}from"./compliance-core";import{contentMatchesMime,validateComplianceUpload}from"./compliance-files";import{CAPABILITIES,hasCapability}from"./permissions";
describe("compliance risk matrix",()=>{it("calculates scores",()=>expect(riskScore(4,5)).toBe(20));it("rejects values outside the configured matrix",()=>expect(()=>riskScore(6,1)).toThrow("RISK_VALUE_OUT_OF_RANGE"));});
describe("controlled workflow",()=>{it("allows explicit review and approval transitions",()=>{expect(canTransition("DRAFT","UNDER_REVIEW")).toBe(true);expect(canTransition("AWAITING_APPROVAL","APPROVED")).toBe(true)});it("does not permit published content to return to draft",()=>expect(canTransition("PUBLISHED","DRAFT")).toBe(false));});
describe("actions and notifications",()=>{it("calculates overdue without storing a fake status",()=>{expect(isOverdue(new Date("2026-01-01"),"OPEN",new Date("2026-01-02"))).toBe(true);expect(isOverdue(new Date("2026-01-01"),"COMPLETED",new Date("2026-01-02"))).toBe(false)});it("builds stable recipient/version keys",()=>expect(notificationKey({organisationId:"org",eventType:"REVIEW_7",recordId:"record",versionId:"v2",recipientId:"user",threshold:7})).toBe("org:REVIEW_7:record:v2:user:7"));});
describe("compliance permissions",()=>{it("gives managers draft operations but not approval or publication",()=>{expect(hasCapability("MANAGER",CAPABILITIES.RISK_ASSESSMENT_CREATE)).toBe(true);expect(hasCapability("MANAGER",CAPABILITIES.RISK_ASSESSMENT_APPROVE)).toBe(false);expect(hasCapability("MANAGER",CAPABILITIES.RISK_ASSESSMENT_PUBLISH)).toBe(false)});it("allows explicit per-user removal",()=>expect(hasCapability("DIRECTOR",CAPABILITIES.COMPLIANCE_VIEW,{[CAPABILITIES.COMPLIANCE_VIEW]:false})).toBe(false));});
describe("compliance upload validation",()=>{const pdf=Buffer.from("%PDF-1.7 test");it("checks both declared type and file signature",()=>{expect(contentMatchesMime(pdf,"application/pdf")).toBe(true);expect(validateComplianceUpload({size:pdf.length,type:"application/pdf"},pdf)).toBeNull();expect(validateComplianceUpload({size:pdf.length,type:"image/png"},pdf)).toMatch(/does not match/) });it("rejects unsupported and oversized uploads",()=>{expect(validateComplianceUpload({size:4,type:"text/html"},Buffer.from("html"))).toMatch(/PDF/);expect(validateComplianceUpload({size:11*1024*1024,type:"application/pdf"},pdf)).toMatch(/10 MB/)})});

describe("organisation isolation",()=>{
  it("cannot be overridden by caller-supplied filters",()=>expect(organisationScope("org-a",{organisationId:"org-b",active:true})).toEqual({organisationId:"org-a",active:true}));
  it("rejects an absent organisation boundary",()=>expect(()=>organisationScope("",{active:true})).toThrow("ORGANISATION_REQUIRED"));
});
