import {beforeAll,afterAll,describe,it,expect} from "vitest";
import {PrismaClient} from "@prisma/client";
import {submitVehicleCheck,transitionDefect,returnVehicle} from "./fleet-service";
import {checklist,vehicleConfigSchema,type Submission} from "./vehicle-checklist";
// Explicitly opt in against the disposable local validation database only.
const enabled=process.env.FLEET_INTEGRATION==="1"&&/^mysql:\/\/[^@]+@127\.0\.0\.1:3317\/stars_fleet_validation/.test(process.env.DATABASE_URL||"");
const p=new PrismaClient();const actor={id:crypto.randomUUID(),name:"Fleet synthetic validator"};
let vehicleId:string;
describe.skipIf(!enabled)("fleet real MariaDB workflow",()=>{
 beforeAll(async()=>{await p.user.create({data:{...actor,username:actor.id.slice(0,30),email:`${actor.id}@example.invalid`,passwordHash:"not-a-login",role:"MANAGER"}});const v=await p.fleetVehicle.create({data:{name:"Synthetic validation bus",registration:actor.id.slice(0,8),registrationKey:actor.id.slice(0,8),make:"Test",model:"Test",vehicleType:"Minibus",fuelType:"DIESEL",mileage:100,config:vehicleConfigSchema.parse({}),createdById:actor.id,updatedById:actor.id}});vehicleId=v.id});
 afterAll(()=>p.$disconnect());
 async function input(severity?:"MINOR"|"CRITICAL"){const id=crypto.randomUUID(),image=crypto.randomUUID();await p.documentRecord.create({data:{id:image,documentNumber:image,documentType:"VEHICLE_EVIDENCE",sourceType:"VEHICLE_EVIDENCE",sourceId:id,createdById:actor.id,periodStart:new Date(),periodEnd:new Date(),generationSource:"TEST",storagePath:"synthetic-no-file",mimeType:"image/jpeg",fileSize:1,sha256Hash:"0".repeat(64)}});const answers=checklist("DIESEL",{}).flatMap(s=>s.items).map(i=>({key:i.key,response:i.applicable?"PASS" as const:"NA" as const,notes:"",imageIds:[],secured:false}));const d:Submission={id,vehicleId,clientStartedAt:new Date().toISOString(),mileage:101,initialImageId:image,answers,declaration:true,version:"FLOWER-1"};if(severity)d.answers[0]={key:"fuel",response:"DEFECT",severity,notes:"Synthetic warning",imageIds:[image],secured:false};return d;}
 it("submits all-pass exactly once on retry",async()=>{const d=await input();const first=await submitVehicleCheck(d,actor),retry=await submitVehicleCheck(d,actor);expect(retry.id).toBe(first.id);expect(first.outcome).toBe("PASSED");expect(await p.vehicleCheck.count({where:{id:d.id}})).toBe(1)});
 it("deduplicates simultaneous submissions",async()=>{const d=await input();const rows=await Promise.all(Array.from({length:4},()=>submitVehicleCheck(d,actor)));expect(new Set(rows.map(r=>r.id)).size).toBe(1);expect(await p.vehicleCheck.count({where:{id:d.id}})).toBe(1);expect(await p.auditLog.count({where:{entityId:d.id,action:"VEHICLE_CHECK_SUBMITTED"}})).toBe(1)});
 it("rejects changed payload under an existing id",async()=>{const d=await input();await submitVehicleCheck(d,actor);await expect(submitVehicleCheck({...d,mileage:102},actor)).rejects.toThrow("different check")});
 it("records minor defects without stopping an active vehicle",async()=>{const d=await input("MINOR");const row=await submitVehicleCheck(d,actor);expect(row.outcome).toBe("MINOR_DEFECTS");expect((await p.fleetVehicle.findUniqueOrThrow({where:{id:vehicleId}})).status).toBe("ACTIVE")});
 it("stops a critical vehicle and creates only one alert on retry",async()=>{const d=await input("CRITICAL");await submitVehicleCheck(d,actor);await submitVehicleCheck(d,actor);expect((await p.fleetVehicle.findUniqueOrThrow({where:{id:vehicleId}})).status).toBe("OUT_OF_SERVICE");expect(await p.operationalTask.count({where:{sourceKey:`vehicle-unsafe:${d.id}`}})).toBe(1);expect(await p.vehicleDefect.count({where:{checkId:d.id}})).toBe(1)});
 it("blocks return until all defects verified then closes with history",async()=>{await expect(returnVehicle(vehicleId,"Return after checks",actor.id)).rejects.toThrow("verified");const ds=await p.vehicleDefect.findMany({where:{vehicleId,status:{not:"CLOSED"}}});for(const d of ds){await transitionDefect(d.id,"UNDER_REVIEW","Examined",{},actor.id);await transitionDefect(d.id,"REPAIR_REQUIRED","Repair scheduled",{},actor.id);await transitionDefect(d.id,"REPAIRED","Repair completed",{repairDate:"2026-09-20",provider:"Synthetic workshop"},actor.id);await transitionDefect(d.id,"VERIFIED","Function checked",{verification:"Competent person verified function"},actor.id)}expect((await p.fleetVehicle.findUniqueOrThrow({where:{id:vehicleId}})).status).toBe("OUT_OF_SERVICE");await returnVehicle(vehicleId,"All repairs verified and vehicle released",actor.id);expect((await p.fleetVehicle.findUniqueOrThrow({where:{id:vehicleId}})).status).toBe("ACTIVE");expect(await p.vehicleDefectEvent.count({where:{defectId:ds[0].id}})).toBe(6)});
 it("keeps an overnight offline check on its performed date",async()=>{const d=await input();d.clientStartedAt="2026-09-18T09:00:00.000Z";const r=await submitVehicleCheck(d,actor);expect(r.checkDate.toISOString().slice(0,10)).toBe("2026-09-18");expect(r.submittedAt.getTime()).toBeGreaterThan(new Date(d.clientStartedAt).getTime())});
 it("records a no-fault finding with separate verification and return",async()=>{const d=await input("MINOR");await submitVehicleCheck(d,actor);const defect=await p.vehicleDefect.findFirstOrThrow({where:{checkId:d.id}});await transitionDefect(defect.id,"UNDER_REVIEW","Investigated",{},actor.id);await transitionDefect(defect.id,"NO_FAULT","Competent inspection found no fault",{},actor.id);await expect(returnVehicle(vehicleId,"Release requested",actor.id)).rejects.toThrow("verified");await transitionDefect(defect.id,"VERIFIED","No fault confirmed",{verification:"Independent function check completed"},actor.id);await returnVehicle(vehicleId,"Verification accepted",actor.id);expect((await p.vehicleDefect.findUniqueOrThrow({where:{id:defect.id}})).status).toBe("CLOSED")});
 it("retains archived history and rejects new checks",async()=>{await p.fleetVehicle.update({where:{id:vehicleId},data:{status:"ARCHIVED"}});expect(await p.vehicleCheck.count({where:{vehicleId}})).toBeGreaterThan(0);await expect(submitVehicleCheck(await input(),actor)).rejects.toThrow("archived")});
});
