import {beforeEach,describe,expect,it,vi} from "vitest";
const state=vi.hoisted(()=>({po:"PO-123",claim:true,excluded:false,created:[] as Record<string,unknown>[],updates:[] as Record<string,unknown>[],pdf:vi.fn((input:unknown)=>{void input;return Buffer.from("pdf")})}));
vi.mock("./billing-settings",()=>({getBillingSettings:async()=>({invoicePrefix:"STARS",organisationLegalName:"Stars",organisationAddress:"Enfield",bankDetails:"Bank",remittanceInstructions:"Reference",defaultPaymentTerms:"30 days"})}));
vi.mock("./invoice-logo",()=>({loadInvoiceLogo:async()=>Buffer.from("image"),safeDocumentName:()=>"Student"}));
vi.mock("./invoice-pdf",()=>({invoicePdf:state.pdf}));
vi.mock("./documents",()=>({storeDocument:async()=>({id:"document",storagePath:"synthetic"}),deleteStoredDocument:vi.fn()}));
vi.mock("./audit",()=>({audit:vi.fn()}));
vi.mock("./prisma",()=>{const tx={billingRun:{updateMany:async()=>({count:state.claim?1:0}),findUniqueOrThrow:async()=>({id:"run",status:"INVOICES_GENERATED",periodStart:new Date("2026-09-01"),periodEnd:new Date("2026-09-30"),invoices:[{id:"already-issued"}],charges:[1,2,3].map(n=>({id:String(n),studentId:"student",studentName:"Alex",billingProfileId:"profile",chargeRuleId:"rule",excluded:state.excluded,quantity:1,unitRate:100,netAmount:100,vatAmount:0,grossAmount:100}))}),update:vi.fn()},billingProfile:{findMany:async()=>[{id:"profile",payerName:"London Borough of Enfield",purchaseOrderNumber:state.po,paymentTermsDays:30,billingAddress:"Civic Centre"}]},appSetting:{upsert:async()=>({value:1}),update:vi.fn()},student:{findUniqueOrThrow:async()=>({id:"student",displayName:"Alex",internalReference:"A1"})},invoice:{count:async()=>1,findUnique:async()=>null,findFirst:async()=>({id:"previous",version:1}),create:async({data}:{data:Record<string,unknown>})=>{state.created.push(data);return {id:"new",...data}},update:async({where,data}:{where:Record<string,string>;data:Record<string,unknown>})=>{state.updates.push({where,data});return data}}};return {prisma:{$transaction:async(fn:(t:typeof tx)=>unknown)=>fn(tx)}}});
import {generateFundedInvoices} from "./funded-invoices";
beforeEach(()=>{state.po="PO-123";state.claim=true;state.excluded=false;state.created=[];state.updates=[];state.pdf.mockClear()});
describe("funded invoice generation",()=>{
 it("blocks Enfield invoices without a PO before creating invoices",async()=>{state.po="";await expect(generateFundedInvoices("run","manager")).rejects.toThrow("PO number required");expect(state.created).toHaveLength(0)});
 it("creates one summary line and links a retained prior invoice",async()=>{await generateFundedInvoices("run","manager");expect(state.created[0]).toMatchObject({purchaseOrderNumber:"PO-123",version:2,supersedesId:"previous",grossTotal:300});const input=state.pdf.mock.calls[0][0] as unknown as {rows:unknown[];attendanceDays:string};expect(input.rows).toHaveLength(1);expect(input.attendanceDays).toBe("3.00");expect(state.updates).toContainEqual({where:{id:"previous"},data:{status:"SUPERSEDED"}})});
 it("returns existing output when the same generation request is retried",async()=>{state.claim=false;const output=await generateFundedInvoices("run","manager");expect(output).toEqual([{id:"already-issued"}]);expect(state.created).toHaveLength(0)});
 it("supports an all-days-removed zero invoice without changing the allocation",async()=>{state.excluded=true;await generateFundedInvoices("run","manager");expect(state.created[0]).toMatchObject({grossTotal:0});const input=state.pdf.mock.calls[0][0] as unknown as {attendanceDays:string};expect(input.attendanceDays).toBe("0.00")});
});
