import {beforeEach, expect, it, vi} from "vitest";
import {NextRequest, NextResponse} from "next/server";
const state=vi.hoisted(()=>({user:{id:"test",role:"TEAM_LEADER",accessLevelId:null as string|null,organisationId:"org",permissionOverrides:{} as Record<string,boolean>},level:{active:true,baseRole:"TEAM_LEADER",permissions:{"dashboard.view":true,"students.view":true}},find:vi.fn(),active:true}));
vi.mock("next/headers",()=>({cookies:async()=>({get:()=>({value:"test-token"})})}));
vi.mock("./audit",()=>({audit:vi.fn()}));
vi.mock("./prisma",()=>({prisma:{session:{findFirst:async()=>({id:"session",scope:"FULL",lastSeenAt:new Date(),user:{...state.user}})},accessLevel:{findUnique:state.find},staffMember:{findUnique:async()=>({active:state.active})},appSetting:{findUnique:async()=>null}}}));
import {getSession} from "./security";
import {withRole} from "./api";
import {hasCapability,CAPABILITIES} from "./permission-catalog";
import {managerNavForRole} from "./manager-nav";
beforeEach(()=>{state.user={id:"test",role:"TEAM_LEADER",accessLevelId:null,organisationId:"org",permissionOverrides:{}};state.level={active:true,baseRole:"TEAM_LEADER",permissions:{"dashboard.view":true,"students.view":true}};state.active=true;state.find.mockReset().mockImplementation(async()=>state.level)});
it("uses configured Team Leader permissions for a Settings-created account in the dashboard API and navigation",async()=>{
 const response=await withRole(new NextRequest("https://example.test/api/dashboard"),"RECEPTION",async()=>NextResponse.json({ok:true}));
 expect(response.status).toBe(200);
 expect(state.find).toHaveBeenCalledWith({where:{name:"Team Leader"}});
 const session=await getSession();const user=session!.user;
 const capabilities=Object.values(CAPABILITIES).filter(c=>hasCapability(user.role,c,user.permissionOverrides));
 expect(capabilities).toContain("dashboard.view");
 expect(JSON.stringify(managerNavForRole(user.role,capabilities))).toContain("/dashboard/students");
 expect(capabilities).not.toContain("users.manage");
});
it("replaces legacy saved role defaults with the configured grade",async()=>{state.user.permissionOverrides={"dashboard.view":false};const response=await withRole(new NextRequest("https://example.test/api/dashboard"),"RECEPTION",async()=>NextResponse.json({ok:true}));expect(response.status).toBe(200)});
it("rechecks grade edits for existing sessions",async()=>{expect((await getSession())!.user.permissionOverrides).toMatchObject({"dashboard.view":true});state.level.permissions["dashboard.view"]=false;expect((await getSession())!.user.permissionOverrides).toMatchObject({"dashboard.view":false})});
it("keeps explicit level assignment authoritative",async()=>{state.user.accessLevelId="assigned";state.user.permissionOverrides={"dashboard.view":false};expect((await getSession())!.user.permissionOverrides).toMatchObject({"dashboard.view":true});expect(state.find).toHaveBeenCalledWith({where:{id:"assigned"}})});
it("rejects disabled grades and inactive linked staff",async()=>{state.level.active=false;expect(await getSession()).toBeNull();state.level.active=true;state.active=false;expect(await getSession()).toBeNull()});
it("does not guess which manager grade applies",async()=>{state.user.role="MANAGER";await getSession();expect(state.find).not.toHaveBeenCalled()});
it("keeps administrators unrestricted",async()=>{state.user.role="ADMINISTRATOR";const user=(await getSession())!.user;expect(hasCapability(user.role,CAPABILITIES.USERS_MANAGE,user.permissionOverrides)).toBe(true);expect(state.find).not.toHaveBeenCalled()});
it("leaves restrictive defaults when no grade exists",async()=>{state.find.mockResolvedValue(null);const user=(await getSession())!.user;expect(hasCapability(user.role,CAPABILITIES.DASHBOARD_VIEW,user.permissionOverrides)).toBe(false)});
it("does not substitute another level when an assigned level is missing",async()=>{state.user.accessLevelId="missing";state.find.mockResolvedValue(null);expect(await getSession()).toBeNull()});
