import {moduleCapability} from "./module-access";
import type{Role}from"@prisma/client";
export type ManagerNavItem={label:string;href:string;roles?:Role[]};
export type ManagerNavGroup={label:string;href?:string;items:ManagerNavItem[];roles?:Role[]};
const elevated:Role[]=["MANAGER","DIRECTOR","ADMINISTRATOR"],directors:Role[]=["DIRECTOR","ADMINISTRATOR"],admins:Role[]=["ADMINISTRATOR"];
export const managerNavigation:ManagerNavGroup[]=[
 {label:"Calendar",href:"/dashboard/calendar",roles:elevated,items:[{label:"Operational calendar",href:"/dashboard/calendar",roles:elevated}]},
 {label:"People",items:[{label:"Staff",href:"/dashboard/staff",roles:elevated},{label:"Staff Training",href:"/dashboard/training",roles:elevated},{label:"Clients",href:"/dashboard/students",roles:elevated},{label:"Information Reviews",href:"/dashboard/information-reviews",roles:elevated},{label:"Visitors",href:"/dashboard/visitors"}]},
 {label:"Staff portal",items:[{label:"Access",href:"/dashboard/staff/access",roles:elevated},{label:"Requests",href:"/dashboard/staff/tasks",roles:elevated}]},
 {label:"Attendance",items:[{label:"Registers",href:"/register"},{label:"Timesheets",href:"/timesheets",roles:elevated},{label:"Emergency Register",href:"/emergency"},{label:"Live attendance",href:"/live"}]},
 {label:"Safety & Compliance",roles:elevated,items:[{label:"Health & Safety / RAMS",href:"/dashboard/health-safety",roles:directors},{label:"Safety & Compliance",href:"/dashboard/premises",roles:directors},{label:"Fleet",href:"/dashboard/premises/fleet",roles:elevated},{label:"Complete Vehicle Check",href:"/VehicleCheck"}]},
 {label:"Finance",roles:elevated,items:[{label:"Payroll",href:"/dashboard/payroll",roles:elevated},{label:"Transport setup",href:"/dashboard/payroll/transport",roles:elevated},{label:"Billing",href:"/dashboard/billing",roles:elevated},{label:"Billing setup",href:"/dashboard/billing/profiles",roles:elevated},{label:"Billing periods",href:"/dashboard/billing/periods",roles:elevated},{label:"Payments",href:"/dashboard/billing/payments",roles:elevated}]},
 {label:"Reports",roles:elevated,items:[{label:"Operational Reports",href:"/reports",roles:elevated},{label:"Daily Reports",href:"/dashboard/reports/daily",roles:elevated},{label:"Clocking Photographs",href:"/dashboard/reports/clocking-photos",roles:directors},{label:"Export History",href:"/dashboard/reports/payroll",roles:elevated}]},
 {label:"Settings",items:[{label:"Administration hub",href:"/dashboard/settings",roles:elevated},{label:"Organisation",href:"/settings",roles:admins},{label:"Email",href:"/dashboard/settings/email",roles:directors},{label:"Devices",href:"/dashboard/settings/devices",roles:admins},{label:"Access Levels",href:"/dashboard/settings/access-levels",roles:admins},{label:"Users & Permissions",href:"/dashboard/settings/users",roles:admins},{label:"Kiosk Screensaver",href:"/dashboard/settings/screensaver",roles:elevated},{label:"Synchronisation",href:"/dashboard/settings/synchronisation",roles:elevated},{label:"Conflicts",href:"/dashboard/conflicts",roles:elevated},{label:"Audit Log",href:"/dashboard/audit",roles:admins}]}
];
const allowed=(role:Role,roles?:Role[])=>!roles||roles.includes(role);
export function managerNavForRole(role:Role,capabilities?:string[]){if(capabilities)return managerNavigation.map(group=>({...group,items:group.items.filter(item=>{const cap=moduleCapability(item.href);return cap?capabilities.includes(cap):allowed(role,item.roles)})})).filter(group=>group.items.length);return (role==="TEAM_LEADER"||role==="CARE_ASSISTANT"?managerNavigation.filter(g=>g.label==="Staff portal"):managerNavigation).filter(group=>allowed(role,group.roles)).map(group=>({...group,items:group.items.filter(item=>allowed(role,item.roles))})).filter(group=>group.items.length)}
export function activeManagerSection(pathname:string){if(pathname==="/dashboard")return"Dashboard";if(pathname.startsWith("/dashboard/staff/access")||pathname.startsWith("/dashboard/staff/tasks"))return"Staff portal";for(const group of managerNavigation)if(group.items.some(item=>pathname===item.href||pathname.startsWith(`${item.href}/`)))return group.label;if(pathname.startsWith("/dashboard/settings"))return"Settings";if(pathname.startsWith("/dashboard/payroll")||pathname.startsWith("/dashboard/billing"))return"Finance";if(pathname.startsWith("/dashboard/reports"))return"Reports";return undefined}
