import {Prisma,type ClientMedication} from "@prisma/client";
import {prisma,jsonValue,auditAction,actionRecipients,notifyAction} from "./action-notifications";
import {medicationEstimate,terminalMedicationStates} from "./medication";
import {CAPABILITIES} from "./permission-catalog";
export async function reconcileMedication(tx:Prisma.TransactionClient,m:ClientMedication,actorId:string,now=new Date()){
 const estimate=medicationEstimate(m,now);const current=m.activeTaskId?await tx.operationalTask.findUnique({where:{id:m.activeTaskId}}):null;
 const eligible=m.status==="ACTIVE"&&!!estimate.runOut&&estimate.daysRemaining!==null&&estimate.daysRemaining<=m.reminderDays;
 if(current&&terminalMedicationStates.has(current.status))return current;
 const snapshot={medicationId:m.id,studentId:m.studentId,estimatedRunOut:estimate.runOut,estimatedDaysRemaining:estimate.daysRemaining,quantity:Number(m.quantity),unit:m.unit,href:`/dashboard/medications?client=${m.studentId}&medication=${m.id}`};
 if(!eligible){if(current){await tx.operationalTask.update({where:{id:current.id},data:{status:m.status!=="ACTIVE"?"NO_LONGER_REQUIRED":"ESTIMATE_CORRECTED",details:jsonValue({...current.details as object,...snapshot})}});await tx.operationalTaskEvent.create({data:{taskId:current.id,actorId,action:"ESTIMATE_CORRECTED",details:jsonValue(snapshot)}});await tx.clientMedication.update({where:{id:m.id},data:{activeTaskId:null,cycle:{increment:1}}})}return null;}
 const client=await tx.student.findUnique({where:{id:m.studentId},select:{displayName:true}});const priority=estimate.priority;const title=`Medication stock — ${client?.displayName||"Client"} · ${m.name}`.slice(0,191);const due=new Date(estimate.runOut!.slice(0,10));let task=current;
 if(!task){task=await tx.operationalTask.create({data:{sourceKey:`medication:${m.id}:${m.cycle}`,title,status:"UPCOMING",priority,assignedStaffId:m.responsibleStaffId,startDate:new Date(now.toISOString().slice(0,10)),endDate:due,dueDate:due,createdById:actorId,notes:"Estimated run-out only. Confirm stock and prescription arrangements.",details:jsonValue(snapshot)}});await tx.clientMedication.update({where:{id:m.id},data:{activeTaskId:task.id}});await tx.operationalTaskEvent.create({data:{taskId:task.id,actorId,action:"CREATED",details:jsonValue(snapshot)}})}
 else if((task.details as Record<string,unknown>)?.estimatedRunOut!==estimate.runOut||task.priority!==priority||task.assignedStaffId!==m.responsibleStaffId){await tx.operationalTaskEvent.create({data:{taskId:task.id,actorId,action:"ESTIMATE_UPDATED",details:jsonValue({before:task.details,after:snapshot,priority})}});task=await tx.operationalTask.update({where:{id:task.id},data:{title,priority,dueDate:due,endDate:due,assignedStaffId:m.responsibleStaffId,details:jsonValue({...task.details as object,...snapshot})}})}
 const recipients=await actionRecipients(tx,CAPABILITIES.MEDICATION_VIEW,CAPABILITIES.MEDICATION_MANAGE);if(m.responsibleStaffId){const staff=await tx.staffMember.findUnique({where:{id:m.responsibleStaffId}});const all=await actionRecipients(tx,CAPABILITIES.MEDICATION_VIEW);const assigned=all.find(u=>u.id===staff?.userId);if(assigned&&!recipients.some(u=>u.id===assigned.id))recipients.push(assigned)}
 await notifyAction(tx,recipients,`med:${task.id}:${priority}`,`MEDICATION_${priority}`,task.id,"A medication stock action needs attention.",snapshot.href);
 if(["URGENT","CRITICAL","OVERDUE"].includes(priority)&&["PRESCRIPTION_REQUESTED","AWAITING_MEDICATION","READY"].includes(task.status))await notifyAction(tx,recipients,`med:${task.id}:outstanding:${priority}`,"PRESCRIPTION_OUTSTANDING",task.id,"A prescription is still outstanding near its estimated run-out.",snapshot.href);
 return task;
}
export async function refreshMedications(actorId:string,now=new Date()){const rows=await prisma.clientMedication.findMany({select:{id:true}});for(const row of rows)await prisma.$transaction(async tx=>{const m=await tx.clientMedication.update({where:{id:row.id},data:{updatedAt:new Date()}});await reconcileMedication(tx,m,actorId,now)},{isolationLevel:"Serializable"});return rows.length}
export type StockChange={key:string;version:number;action:"CONFIRM"|"RECEIVED"|"ADJUST"|"CORRECT"|"MISSED"|"REFUSED"|"WITHHELD";quantity?:number;amount?:number;reason:string;relatedReference?:string;correctsEventId?:string};
export async function changeMedicationStock(id:string,input:StockChange,actorId:string,now=new Date()){
 return prisma.$transaction(async tx=>{
 const prior=await tx.medicationStockEvent.findUnique({where:{requestKey:input.key}});if(prior){if(prior.medicationId!==id||prior.actorId!==actorId||Object.entries(input).some(([k,v])=>JSON.stringify((prior.details as Record<string,unknown>)?.[k])!==JSON.stringify(v)))throw Error("Update reference already used.");return prior;}
 if(!(await tx.clientMedication.updateMany({where:{id,version:input.version},data:{version:{increment:1}}})).count)throw Error("This medication changed. Reload before saving.");
 const m=await tx.clientMedication.findUniqueOrThrow({where:{id}});if(input.correctsEventId&&!await tx.medicationStockEvent.findFirst({where:{id:input.correctsEventId,medicationId:id}}))throw Error("Choose an entry from this medication's history.");
 const estimate=medicationEstimate(m,now);const previous=Number(m.quantity||0);let quantity=input.quantity;
 if(["MISSED","REFUSED","WITHHELD"].includes(input.action)){if(estimate.estimatedQuantity===null||!input.amount||m.status!=="ACTIVE")throw Error("A valid active estimate and unused quantity are required.");quantity=estimate.estimatedQuantity+input.amount;}
 if(input.action==="RECEIVED"){if(quantity===undefined||!input.amount)throw Error("Enter the counted stock remaining and new quantity received.");quantity+=input.amount;}
 if(quantity===undefined||!Number.isFinite(quantity)||quantity<0||quantity>9999999999)throw Error("Enter a valid stock quantity.");
 const confirmed=["CONFIRM","RECEIVED","CORRECT","ADJUST"].includes(input.action);const prescription={...(m.prescription as object||{}),...(input.action==="RECEIVED"?{receivedAt:now.toISOString(),receivedQuantity:input.amount,status:"MEDICATION_RECEIVED"}:{})};
 const event=await tx.medicationStockEvent.create({data:{medicationId:id,requestKey:input.key,action:input.action,previousQuantity:m.quantity,newQuantity:quantity,changeAmount:quantity-previous,reason:input.reason,actorId,details:jsonValue({...input,estimatedBefore:estimate.estimatedQuantity,at:now.toISOString()})}});
 let next=await tx.clientMedication.update({where:{id},data:{quantity,stockAt:now,...(confirmed?{confirmedAt:now}:{}),prescription:jsonValue(prescription)}});
 if(m.activeTaskId&&input.action==="RECEIVED"){await tx.operationalTask.update({where:{id:m.activeTaskId},data:{status:"COMPLETED",details:jsonValue({...prescription,medicationId:id,studentId:m.studentId,completionDetails:input.reason})}});for(const action of ["MEDICATION_RECEIVED","COMPLETED"])await tx.operationalTaskEvent.create({data:{taskId:m.activeTaskId,actorId,action,details:jsonValue({eventId:event.id,...prescription,reason:input.reason})}});next=await tx.clientMedication.update({where:{id},data:{activeTaskId:null,cycle:{increment:1}}})}
 else if(m.activeTaskId&&confirmed){const old=await tx.operationalTask.findUnique({where:{id:m.activeTaskId}});if(old&&terminalMedicationStates.has(old.status))next=await tx.clientMedication.update({where:{id},data:{activeTaskId:null,cycle:{increment:1}}})}
 await auditAction(tx,actorId,"MEDICATION_STOCK_UPDATED","ClientMedication",id,{},{eventId:event.id});await reconcileMedication(tx,next,actorId,now);return event;
 },{isolationLevel:"Serializable"});
}
