import {z} from "zod";
export const medicationInput=z.object({studentId:z.string().uuid(),name:z.string().trim().min(1).max(191),strength:z.string().max(100).default(""),form:z.string().max(60).default(""),unit:z.string().trim().min(1).max(40),dose:z.number().min(0).max(1000000).nullable(),administrations:z.number().min(0).max(100).nullable(),weekdayUsage:z.array(z.number().min(0).max(1000000)).length(7).nullable(),prn:z.boolean(),manualDailyUsage:z.number().positive().max(1000000).nullable(),reminderDays:z.number().int().min(0).max(365).default(14),confirmationDays:z.number().int().min(1).max(365).default(30),status:z.enum(["ACTIVE","PAUSED","DISCONTINUED"]),responsibleStaffId:z.string().uuid().nullable(),notes:z.string().max(6000).default("")}).strict();
export type MedicationEstimateInput={quantity:unknown;confirmedAt:Date|string|null;stockAt?:Date|string|null;dose:unknown;administrations:unknown;weekdayUsage:unknown;prn:boolean;manualDailyUsage:unknown;status:string;reminderDays:number;confirmationDays:number};
const dayMs=86400000;
const londonDay=(d:Date)=>new Intl.DateTimeFormat("sv-SE",{timeZone:"Europe/London"}).format(d);
export function medicationEstimate(m:MedicationEstimateInput,now=new Date()){
 const anchor=m.stockAt||m.confirmedAt;const q=m.quantity===null?null:Number(m.quantity);
 const weekdays=Array.isArray(m.weekdayUsage)&&m.weekdayUsage.length===7?m.weekdayUsage.map(Number):null;
 const daily=m.prn?Number(m.manualDailyUsage||0):weekdays?weekdays.reduce((a,b)=>a+b,0)/7:Number(m.dose||0)*Number(m.administrations||0);
 const confirmationOverdue=!m.confirmedAt||+now-+new Date(m.confirmedAt)>m.confirmationDays*dayMs;
 const invalid=m.status!=="ACTIVE"||q===null||!anchor||!Number.isFinite(q)||q<0||!Number.isFinite(+new Date(anchor||""))||(weekdays&&weekdays.some(v=>!Number.isFinite(v)||v<0))||!Number.isFinite(daily)||daily<=0;
 if(invalid)return {dailyUsage:daily||null,daysRemaining:null,runOut:null,estimatedQuantity:null,priority:"NONE",confirmationOverdue,reliable:false,label:m.status!=="ACTIVE"?m.status.toLowerCase():m.prn&&!m.manualDailyUsage?"No run-out estimate available":"Stock confirmation required"};
 const start=new Date(anchor!);let duration=q!/daily,used=Math.max(0,(+now-+start)/dayMs)*daily;
 if(weekdays&&!m.prn){let remaining=q!,elapsed=0;used=0;const startDay=new Date(londonDay(start)+"T00:00:00Z");const currentDay=new Date(londonDay(now)+"T00:00:00Z");const age=Math.max(0,(+currentDay-+startDay)/dayMs);const weeks=Math.max(0,Math.floor(remaining/(daily*7))-1);remaining-=weeks*daily*7;elapsed=weeks*7;while(remaining>0&&elapsed<366000){const usage=weekdays[(startDay.getUTCDay()+elapsed)%7];if(usage>0&&remaining<=usage){elapsed+=remaining/usage;remaining=0;break}remaining-=usage;elapsed++}duration=elapsed;const fullWeeks=Math.floor(age/7);used=fullWeeks*daily*7;for(let j=fullWeeks*7;j<age;j++)used+=weekdays[(startDay.getUTCDay()+j)%7];}
 const runOut=new Date(+start+duration*dayMs);if(!Number.isFinite(+runOut))return {dailyUsage:daily,daysRemaining:null,runOut:null,estimatedQuantity:null,priority:"NONE",confirmationOverdue,reliable:false,label:"Check usage and stock quantities"};const daysRemaining=(+runOut-+now)/dayMs;const priority=daysRemaining<0?"OVERDUE":daysRemaining<=3?"CRITICAL":daysRemaining<=7?"URGENT":daysRemaining<=m.reminderDays?"UPCOMING":"NONE";
 return {dailyUsage:daily,daysRemaining:Math.round(daysRemaining*100)/100,runOut:runOut.toISOString(),estimatedQuantity:Math.max(0,Math.round((q!-used)*10000)/10000),priority,confirmationOverdue,reliable:!confirmationOverdue&&!m.prn,label:m.prn?"Manually estimated run-out":confirmationOverdue?"Stock confirmation overdue":"Estimated run-out date"};
}
export const medicationTaskStates=["UPCOMING","PRESCRIPTION_REQUESTED","AWAITING_MEDICATION","READY","MEDICATION_RECEIVED","COMPLETED","CANCELLED","NO_LONGER_REQUIRED","ESTIMATE_CORRECTED"] as const;
export const terminalMedicationStates=new Set(["COMPLETED","CANCELLED","NO_LONGER_REQUIRED","ESTIMATE_CORRECTED"]);
