import {CAPABILITIES,type Capability} from "./permission-catalog";
export function moduleCapability(path:string,write=false):Capability|undefined {
 const area=path.replace(/^\/api\//,"/").replace(/^\/dashboard\//,"/").split("/")[1];
 const modules:Record<string,[Capability,Capability]>={
 "information-reviews":[CAPABILITIES.INFORMATION_REVIEW_VIEW,CAPABILITIES.INFORMATION_REVIEW_MANAGE],calendar:[CAPABILITIES.CALENDAR_VIEW,CAPABILITIES.CALENDAR_MANAGE],"health-safety":[CAPABILITIES.COMPLIANCE_VIEW,CAPABILITIES.COMPLIANCE_MANAGE],dashboard:[CAPABILITIES.DASHBOARD_VIEW,CAPABILITIES.DASHBOARD_MANAGE],staff:[CAPABILITIES.STAFF_VIEW,CAPABILITIES.STAFF_MANAGE],students:[CAPABILITIES.STUDENTS_VIEW,CAPABILITIES.STUDENTS_MANAGE],register:[CAPABILITIES.REGISTER_VIEW,CAPABILITIES.REGISTER_MANAGE],live:[CAPABILITIES.LIVE_VIEW,CAPABILITIES.LIVE_MANAGE],timesheets:[CAPABILITIES.TIMESHEETS_VIEW,CAPABILITIES.TIMESHEETS_MANAGE],reports:[CAPABILITIES.REPORTS_VIEW,CAPABILITIES.REPORTS_MANAGE],emergency:[CAPABILITIES.EMERGENCY_VIEW,CAPABILITIES.EMERGENCY_MANAGE],visitors:[CAPABILITIES.VISITORS_VIEW,CAPABILITIES.VISITORS_MANAGE],training:[CAPABILITIES.TRAINING_VIEW,CAPABILITIES.TRAINING_MANAGE],premises:[CAPABILITIES.PREMISES_VIEW,CAPABILITIES.PREMISES_MANAGE],devices:[CAPABILITIES.DEVICES_VIEW,CAPABILITIES.DEVICES_MANAGE],users:[CAPABILITIES.USERS_VIEW,CAPABILITIES.USERS_MANAGE],settings:[CAPABILITIES.SETTINGS_VIEW,CAPABILITIES.SETTINGS_MANAGE],audit:[CAPABILITIES.AUDIT_VIEW,CAPABILITIES.AUDIT_MANAGE],conflicts:[CAPABILITIES.CONFLICTS_VIEW,CAPABILITIES.CONFLICTS_MANAGE],synchronisation:[CAPABILITIES.SYNCHRONISATION_VIEW,CAPABILITIES.SYNCHRONISATION_MANAGE],billing:[CAPABILITIES.BILLING_REVIEW,CAPABILITIES.BILLING_APPROVE],payroll:[CAPABILITIES.PAYROLL_REVIEW,CAPABILITIES.PAYROLL_APPROVE],email:[CAPABILITIES.REPORT_SETTINGS_MANAGE,CAPABILITIES.REPORT_SETTINGS_MANAGE],system:[CAPABILITIES.SYSTEM_VIEW,CAPABILITIES.SYSTEM_MANAGE],clock:[CAPABILITIES.TIMESHEETS_VIEW,CAPABILITIES.TIMESHEETS_MANAGE]};
 if(["visitor-reasons","visitor-rules"].includes(area)||path.includes("visitors/config"))return CAPABILITIES.VISITOR_SETTINGS;
 if(path.includes("settings/screensaver"))return CAPABILITIES.KIOSK_SETTINGS;
 if(path.includes("settings/email"))return CAPABILITIES.REPORT_SETTINGS_MANAGE;
 if(path.includes("access-levels"))return CAPABILITIES.USERS_MANAGE;
 if(path.includes("clocking-photos")||path.includes("attendance-photos"))return CAPABILITIES.PHOTO_VIEW;
 if(path.startsWith("/staff-portal/calendar"))return CAPABILITIES.STAFF_CALENDAR;
 if(path.startsWith("/staff-portal"))return CAPABILITIES.STAFF_PORTAL;
 if(path.includes("settings/users"))return CAPABILITIES.USERS_MANAGE;
 if(path.includes("settings/devices"))return CAPABILITIES.DEVICES_VIEW;
 if(path.includes("settings/system"))return CAPABILITIES.SYSTEM_VIEW;
 if(path.includes("settings/synchronisation"))return CAPABILITIES.SYNCHRONISATION_VIEW;
 return modules[area]?.[write?1:0];
}
