import {beforeAll,afterAll,describe,it,expect} from "vitest";
import {prisma as p} from "./prisma";
import {paymentSnapshot,mutatePayments,configureTracking,previewTracking,PaymentError} from "./payments";
import {localDateKey} from "./dates";
const enabled=process.env.PAYMENTS_INTEGRATION==="1"&&/^mysql:\/\/[^@]+@127\.0\.0\.1:3317\/stars_fleet_validation/.test(process.env.DATABASE_URL||"");
const actor={id:crypto.randomUUID(),name:"Payments synthetic manager"};
const ids:string[]=[];let runId:string;let oldSettings:unknown;
const today=localDateKey();
describe.skipIf(!enabled)("payments real MariaDB workflow",()=>{
 beforeAll(async()=>{oldSettings=(await p.appSetting.findUnique({where:{key:"paymentTracking"}}))?.value;await p.appSetting.deleteMany({where:{key:"paymentTracking"}});const run=await p.billingRun.create({data:{periodStart:new Date("2026-01-01"),periodEnd:new Date("2026-01-31"),version:Math.floor(Date.now()/1000),createdById:actor.id,status:"INVOICES_GENERATED",label:"Payments validation"}});runId=run.id});
 afterAll(async()=>{await p.paymentEvent.deleteMany({where:{invoiceId:{in:ids}}});await p.invoice.deleteMany({where:{id:{in:ids}}});await p.billingRun.delete({where:{id:runId}});await p.appSetting.deleteMany({where:{key:"paymentTracking"}});if(oldSettings)await p.appSetting.create({data:{key:"paymentTracking",value:oldSettings as never}});await p.$disconnect()});
 async function invoice(options:Record<string,unknown>={}){const r=await p.invoice.create({data:{billingRunId:runId,billingProfileId:crypto.randomUUID(),invoiceNumber:`PAY-TEST-${crypto.randomUUID()}`,studentName:"Payment test client",payerName:"Test council",invoiceDate:new Date(today),dueDate:new Date(today),issuedAt:new Date(),status:"ISSUED",netTotal:"100.10",vatTotal:0,grossTotal:"100.10",...options}});ids.push(r.id);return r}
 async function row(id:string){return (await paymentSnapshot()).rows.find(i=>i.id===id)!}
 it("does not classify historic data before setup; setup preview is confirmed and idempotent",async()=>{const old=await invoice({issuedAt:new Date("2026-01-01")});expect((await row(old.id)).state).toBe("UNCONFIGURED");const impact=await previewTracking("2026-09-01");expect(impact.excluded).toBeGreaterThan(0);await configureTracking("2026-09-01",impact.token,actor);expect((await row(old.id)).state).toBe("IGNORED");await expect(configureTracking("2026-09-01",impact.token,actor)).rejects.toBeInstanceOf(PaymentError);expect(await p.paymentEvent.count({where:{invoiceId:old.id}})).toBe(0)});
 it("new final invoices are automatic; drafts never enter the list",async()=>{const final=await invoice(),draft=await invoice({status:"DRAFT",issuedAt:null});expect((await row(final.id)).state).toBe("OUTSTANDING");expect(await row(draft.id)).toBeUndefined()});
 it("rejects mismatched money without changing history",async()=>{const r=await invoice();await expect(mutatePayments({action:"PAY",items:[{id:r.id,revision:0}],amount:"100.00",receivedDate:today},actor)).rejects.toThrow("must match");expect(await p.paymentEvent.count({where:{invoiceId:r.id}})).toBe(0)});
 it("records payment once under simultaneous submissions; reverses with preserved history",async()=>{const r=await invoice();const input={action:"PAY" as const,items:[{id:r.id,revision:0}],amount:"100.10",receivedDate:today,reference:"Council remittance"};const result=await Promise.allSettled([mutatePayments(input,actor),mutatePayments(input,actor)]);expect(result.filter(r=>r.status==="fulfilled")).toHaveLength(1);expect((await row(r.id)).state).toBe("PAID");expect((await row(r.id)).receivedAmount).toBe("100.10");await mutatePayments({action:"REVERSE",items:[{id:r.id,revision:1}],reason:"Recorded against wrong invoice"},actor);expect((await row(r.id)).state).toBe("OUTSTANDING");expect(await p.paymentEvent.count({where:{invoiceId:r.id}})).toBe(2);expect(await p.auditLog.count({where:{entityId:r.id,action:{startsWith:"PAYMENT_"}}})).toBe(2)});
 it("bulk ignore and restore preserve history",async()=>{const a=await invoice(),b=await invoice();await mutatePayments({action:"IGNORE",items:[a,b].map(r=>({id:r.id,revision:0})),reason:"Duplicate historic record"},actor);expect((await row(a.id)).state).toBe("IGNORED");await mutatePayments({action:"RESTORE",items:[{id:a.id,revision:1}]},actor);expect((await row(a.id)).state).toBe("OUTSTANDING");expect(await p.paymentEvent.count({where:{invoiceId:a.id}})).toBe(2)});
 it("bulk payment is all or nothing and reports the stale invoice",async()=>{const a=await invoice(),b=await invoice();await expect(mutatePayments({action:"PAY",items:[{id:a.id,revision:0},{id:b.id,revision:4}],receivedDate:today},actor)).rejects.toThrow(b.invoiceNumber);expect((await row(a.id)).state).toBe("OUTSTANDING");await mutatePayments({action:"PAY",items:[a,b].map(r=>({id:r.id,revision:0})),receivedDate:today},actor);expect((await row(a.id)).state).toBe("PAID");expect((await row(b.id)).state).toBe("PAID")});
 it("start-date changes preview impact and never overwrite individual decisions",async()=>{const auto=await invoice({issuedAt:new Date("2026-09-02")}),manual=await invoice({issuedAt:new Date("2026-09-02")});await mutatePayments({action:"IGNORE",items:[{id:manual.id,revision:0}],reason:"Other",notes:"Not in new process"},actor);const preview=await previewTracking("2026-09-03");expect(preview.excluded).toBeGreaterThan(0);await configureTracking("2026-09-03",preview.token,actor);expect((await row(auto.id)).state).toBe("IGNORED");const restore=await previewTracking("2026-09-01");await configureTracking("2026-09-01",restore.token,actor);expect((await row(auto.id)).state).toBe("OUTSTANDING");expect((await row(manual.id)).state).toBe("IGNORED")});
 it("voids, superseded invoices and full credits cannot be outstanding or restored",async()=>{const voided=await invoice({status:"VOID"}),superseded=await invoice({status:"SUPERSEDED"}),original=await invoice();await invoice({grossTotal:"-100.10",netTotal:"-100.10",supersedesId:original.id});for(const r of [voided,superseded,original]){expect((await row(r.id)).state).toBe("IGNORED");await expect(mutatePayments({action:"RESTORE",items:[{id:r.id,revision:0}]},actor)).rejects.toThrow("no longer available")}});
 it("summary uses all rows and received month rather than invoice date",async()=>{const before=(await paymentSnapshot()).summary;const r=await invoice({invoiceDate:new Date("2026-01-01")});const outstanding=(await paymentSnapshot()).summary;expect(outstanding.outstandingCount).toBe(before.outstandingCount+1);await mutatePayments({action:"PAY",items:[{id:r.id,revision:0}],amount:"100.10",receivedDate:today},actor);expect((await paymentSnapshot()).summary.paidCount).toBe(before.paidCount+1)});
});
