export const paymentHelpTopics=[
 {id:"payments-navigation",title:"Open Payments from Finance",target:"payment-nav",keywords:["where","menu","finance","navigate"],content:"Open Finance in the top menu, then choose Payments. On tablets open Menu first. If Payments is not listed, ask your administrator to check your payment view permission. The dashboard Outstanding payments card also opens the page. Open the Finance menu before using Show me to outline its Payments link."},
 {id:"payments-paid",title:"Record payment received",target:"payment-mark-paid",keywords:["paid","received","mark","money"],content:"Open Finance → Payments. In Outstanding, choose Mark as paid. Check the client, invoice, payer and total. Enter Date received and the full balance, with an optional reference and note, then Confirm payment received. Mismatched amounts are blocked; partial payments are not supported yet. Select several rows to record full payment with one received date and shared reference. STARS Connect records your confirmation; it does not connect to your bank or collect money."},
 {id:"payments-ignored",title:"Ignore or restore an invoice",target:"payment-ignored",keywords:["ignore","ignored","restore","old","historic"],content:"In Finance → Payments, open the invoice’s more actions menu and choose Ignore. Select a reason; Other needs an explanation. Confirm to exclude it from outstanding totals without deleting or altering the invoice. Select several Outstanding rows for bulk ignore. Under Ignored, choose Restore to Outstanding and confirm. Fully credited, void or superseded invoices cannot be restored while that lifecycle status applies. Previous actions remain in history."},
 {id:"payments-settings",title:"Choose payment tracking start date",target:"payment-settings",keywords:["start","date","setup","settings","tracking"],content:"Open Payment settings in Finance → Payments. Choose the date STARS began using the checklist and Preview impact. Review the invoice counts and total value, then Confirm start date. Earlier issued invoices are automatically Ignored — predates payment tracking. No historic invoice is silently ignored before confirmation. Later start-date changes preserve individual Paid, Ignored and restored decisions. Only users with payment settings permission can change this."},
 {id:"payments-reverse",title:"Reverse a mistaken payment",target:"payment-paid",keywords:["reverse","mistake","undo","reversal"],content:"Open the Paid tab in Finance → Payments. Choose Reverse payment from the invoice’s more actions menu. Enter a mandatory reason and confirm. Payment history is preserved. The invoice returns to Outstanding unless it is void, superseded or fully credited, in which case it is excluded from tracking. Reversing needs separate permission. View payment details shows who recorded each action, dates, references and notes."},
 {id:"payments-outstanding",title:"Find outstanding payments",target:"payment-dashboard",keywords:["outstanding","missing","appearing","approval","dashboard"],content:"Open Finance → Payments or the dashboard Outstanding payments summary. Issued invoices appear automatically after tracking setup; drafts and unapproved runs do not. Older invoices, manual ignores, voids, superseded invoices and fully credited invoices are excluded from Outstanding. Check Ignored and your filters if an invoice is missing. Invoices awaiting approval means billing work still to finalise; Outstanding payments means issued invoices awaiting money. Paid this month uses Date received, not invoice date."}
];
export function paymentHelpForQuestion(question:string){const text=question.toLowerCase();return [...paymentHelpTopics].sort((a,b)=>b.keywords.filter(k=>text.includes(k)).length-a.keywords.filter(k=>text.includes(k)).length)[0]}
