import{payrollAdjustmentForLabel}from"./payroll-adjustment-options";import{roundPayroll,type PayrollRoundingMode}from"./transport-settings";
export type PayrollClockEvent={id:string;type:"CLOCK_IN"|"CLOCK_OUT";deviceTimestamp:Date;serverReceivedAt?:Date;offlineRecorded?:boolean;deviceId?:string;corrections?:unknown[];transportDuty?:boolean};
export type PayrollAdjustmentInput={category:string;minutes:number;paid:boolean;reason:string};
export function calculatePayroll(events:PayrollClockEvent[],adjustments:PayrollAdjustmentInput[]=[],options:{ordinaryDailyMinutes:number;longShiftMinutes:number;shortShiftMinutes:number;transportClockInMinutes:number;transportClockOutMinutes:number;roundingIntervalMinutes:number;roundingMode?:PayrollRoundingMode}={ordinaryDailyMinutes:480,longShiftMinutes:720,shortShiftMinutes:120,transportClockInMinutes:0,transportClockOutMinutes:0,roundingIntervalMinutes:1,roundingMode:"NEAREST"}){
 const sorted=[...events].sort((a,b)=>a.deviceTimestamp.getTime()-b.deviceTimestamp.getTime());let open:PayrollClockEvent|undefined,worked=0;const sessions:{in:Date;out?:Date;minutes:number}[]=[];const exceptions:string[]=[];const seen=new Set<string>();
 for(const event of sorted){const signature=`${event.type}:${event.deviceTimestamp.toISOString()}`;if(seen.has(signature))exceptions.push("DUPLICATE_EVENT");seen.add(signature);if(event.type==="CLOCK_IN"){if(open)exceptions.push("OVERLAPPING_SESSION");open=event;}else if(!open){exceptions.push("MISSING_CLOCK_IN");}else{const minutes=Math.max(0,Math.round((event.deviceTimestamp.getTime()-open.deviceTimestamp.getTime())/60000));sessions.push({in:open.deviceTimestamp,out:event.deviceTimestamp,minutes});worked+=minutes;if(minutes>options.longShiftMinutes)exceptions.push("UNUSUALLY_LONG_SHIFT");if(minutes<options.shortShiftMinutes)exceptions.push("UNUSUALLY_SHORT_SHIFT");if(open.deviceTimestamp.toDateString()!==event.deviceTimestamp.toDateString())exceptions.push("SPANS_MIDNIGHT");open=undefined;}if(event.offlineRecorded)exceptions.push("LATE_SYNCHRONISED");if(event.corrections?.length)exceptions.push("MANUAL_EDIT");}
 if(open){sessions.push({in:open.deviceTimestamp,minutes:0});exceptions.push("MISSING_CLOCK_OUT");}
 const normalised=adjustments.map(a=>{const option=payrollAdjustmentForLabel(a.reason);return option?{...a,category:option.category,paid:option.paid}:a}),paidAdjustments=normalised.filter(a=>a.paid).reduce((n,a)=>n+a.minutes,0),unpaid=normalised.filter(a=>!a.paid).reduce((n,a)=>n+Math.abs(a.minutes),0),category=(name:string)=>normalised.filter(a=>a.category===name).reduce((n,a)=>n+a.minutes,0),holiday=category("HOLIDAY"),sickness=category("SICKNESS"),training=category("TRAINING"),manualOvertime=category("OVERTIME"),otherPaid=normalised.filter(a=>a.paid&&!['HOLIDAY','SICKNESS','TRAINING','OVERTIME'].includes(a.category)).reduce((n,a)=>n+a.minutes,0);
 const transportMinutes=sorted.filter(e=>e.type==="CLOCK_IN"&&e.transportDuty).length*options.transportClockInMinutes+sorted.filter(e=>e.type==="CLOCK_OUT"&&e.transportDuty).length*options.transportClockOutMinutes,adjustedWorked=worked+transportMinutes,paidWorked=Math.max(0,adjustedWorked-unpaid),ordinary=Math.min(paidWorked,options.ordinaryDailyMinutes),workedOvertime=Math.max(0,paidWorked-options.ordinaryDailyMinutes),preRounded=ordinary+workedOvertime+paidAdjustments,totalPayableMinutes=roundPayroll(preRounded,options.roundingIntervalMinutes,options.roundingMode),roundingAdjustmentMinutes=totalPayableMinutes-preRounded;
 if(transportMinutes||roundingAdjustmentMinutes)exceptions.push("TRANSPORT_OR_ROUNDING_REVIEW");
 return{sessions,workedMinutes:worked,originalWorkedMinutes:worked,transportMinutes,preRoundedMinutes:preRounded,roundingAdjustmentMinutes,ordinaryMinutes:ordinary,overtimeMinutes:workedOvertime+manualOvertime,holidayMinutes:holiday,sicknessMinutes:sickness,trainingMinutes:training,unpaidMinutes:unpaid,adjustmentMinutes:otherPaid+transportMinutes+roundingAdjustmentMinutes,totalPayableMinutes,exceptions:[...new Set(exceptions)]};
}
export const payrollPeriodEditable=(status:string)=>!["APPROVED","LOCKED","EXPORTED","SUPERSEDED"].includes(status);