import { describe, expect, it } from "vitest";
import { payrollTimesheetPdf } from "./payroll-timesheet-pdf";

const tinyJpeg = Buffer.from(
  "/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAP//////////////////////////////////////////////////////////////////////////////////////2wBDAf//////////////////////////////////////////////////////////////////////////////////////wAARCAABAAEDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAf/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIQAxAAAAH/AP/EABQQAQAAAAAAAAAAAAAAAAAAABD/2gAIAQEAAQUCf//EABQRAQAAAAAAAAAAAAAAAAAAABD/2gAIAQMBAT8Bf//EABQRAQAAAAAAAAAAAAAAAAAAABD/2gAIAQIBAT8Bf//EABQQAQAAAAAAAAAAAAAAAAAAABD/2gAIAQEABj8Cf//Z",
  "base64",
);

function fixture(rows = 1) {
  return {
    logoJpeg: tinyJpeg,
    employeeName: "Daniel Seal",
    payrollNumber: "DAN",
    periodLabel: "30 Jul 2026 - 30 Jul 2026",
    documentVersion: 3,
    hourlyRate: "GBP 50.00",
    estimatedGrossPay: "GBP 2,400.00",
    summary: [
      { label: "Ordinary", value: "0.00h" },
      { label: "Overtime", value: "8.00h" },
      { label: "Holiday", value: "8.00h" },
      { label: "Sickness", value: "8.00h" },
      { label: "Total payable", value: "48.00h" },
      { label: "Training", value: "16.00h" },
      { label: "Unpaid", value: "8.00h" },
      { label: "Adjustments", value: "8.00h" },
    ],
    rows: Array.from({ length: rows }, (_, index) => ({
      date: "30/07/2026",
      entry: index ? "Holiday" : "Clocked hours",
      details: index ? "Approved annual leave" : "09:00 - 17:00",
      hours: "8.00",
      notes: index ? "Manual pay item" : "No correction",
    })),
    exceptionStatus: "RESOLVED",
    exceptionCount: 1,
    reviewedBy: "Daniel Seal",
    reviewedAt: "30 July 2026 20:50",
    approvedBy: "Daniel Seal",
    approvedAt: "30 July 2026 21:12",
    generatedBy: "Kellie",
    generatedAt: "30 July 2026 21:20",
  };
}

describe("employee payroll timesheet PDF", () => {
  it("renders the prominent period, employee, breakdown and audit footer", () => {
    const text = payrollTimesheetPdf(fixture()).toString("latin1");
    expect(text.startsWith("%PDF-1.4")).toBe(true);
    expect(text).toContain("(PAY PERIOD)");
    expect(text).toContain("(Daniel Seal)");
    expect(text).toContain("(DAILY BREAKDOWN)");
    expect(text).toContain("(REVIEW AND APPROVAL)");
    expect(text).toContain("(Sheet generated by: Kellie - 30 July 2026 21:20)");
    expect(text).toContain("/Subtype /Image");
  });

  it("paginates long daily breakdowns and repeats document context", () => {
    const text = payrollTimesheetPdf(fixture(35)).toString("latin1");
    expect(text).toContain("/Count 3");
    expect(text).toContain("(Daniel Seal - timesheet continued)");
    expect(text).toContain("(Page 3 of 3)");
  });
});
