import {describe,it,expect,vi} from 'vitest';
vi.mock('./prisma',()=>({prisma:{}}));
import {matchTaskQuery} from './clive-live';import {canReadSafetyTask} from './safety-reminders';import {canTransition} from './compliance-core';import {nextTaskStatus,canChangeTask} from './task-lifecycle';import {hasCapability,CAPABILITIES as C} from './permission-catalog';import type {QueueTask} from './task-queue';import type {User} from '@prisma/client';
const user={id:'manager',role:'MANAGER',organisationId:'org',permissionOverrides:{[C.PREMISES_VIEW]:true}} as unknown as User;
const rows:QueueTask[]=[{id:'1',source:'premises',title:'Lighting certificate',category:'Compliance',status:'AWAITING_EVIDENCE',priority:'HIGH',owner:'Kellie',ownerId:'k',dueDate:'2020-01-01',awaitingEvidence:true},{id:'2',source:'operational',title:'Completed visit',category:'Operations',status:'COMPLETED',priority:'NORMAL',owner:'Daniel',dueDate:'2020-01-01'},{id:'3',source:'premises',title:'Next service',category:'Compliance',status:'OPEN',priority:'NORMAL',owner:'Daniel',dueDate:'2099-01-01'}];
describe('Safety & Compliance controls',()=>{
 it('requires controlled review before publication',()=>{expect(canTransition('DRAFT','PUBLISHED')).toBe(false);expect(canTransition('UNDER_REVIEW','CHANGES_REQUESTED')).toBe(true);expect(canTransition('CHANGES_REQUESTED','UNDER_REVIEW')).toBe(true);expect(canTransition('APPROVED','DRAFT')).toBe(false);expect(canTransition('PUBLISHED','DRAFT')).toBe(false);expect(canTransition('PUBLISHED','SUPERSEDED')).toBe(true)});
 it('enforces both organisation and source permission on reminders',()=>{expect(canReadSafetyTask(user,{organisationId:'org',cap:C.PREMISES_VIEW})).toBe(true);expect(canReadSafetyTask(user,{organisationId:'elsewhere',cap:C.PREMISES_VIEW})).toBe(false);expect(canReadSafetyTask({...user,permissionOverrides:{[C.PREMISES_VIEW]:false}},{organisationId:'org',cap:C.PREMISES_VIEW})).toBe(false);expect(canReadSafetyTask(user,{organisationId:'org',cap:'unknown'})).toBe(false)});
 it('requires evidence for premises verification',()=>{expect(()=>nextTaskStatus('premises','complete',{status:'OPEN',verificationRequired:true},'a')).toThrow(/evidence/);expect(nextTaskStatus('premises','complete',{status:'AWAITING_EVIDENCE',verificationRequired:true,attachmentCount:1},'a')).toBe('AWAITING_VERIFICATION');expect(()=>nextTaskStatus('premises','complete',{status:'AWAITING_VERIFICATION',verificationRequired:true,attachmentCount:1,completedById:'a'},'a')).toThrow(/different/);expect(nextTaskStatus('premises','complete',{status:'AWAITING_VERIFICATION',verificationRequired:true,attachmentCount:1,completedById:'a'},'b')).toBe('COMPLETED')});
 it('keeps source-managed reminders out of generic completion',()=>{expect(canChangeTask({role:'ADMINISTRATOR',permissionOverrides:null},'operational','safety:org:asset')).toBe(false)});
 it('does not grant approval by assigning an owner',()=>{expect(hasCapability('CARE_ASSISTANT',C.RAMS_APPROVE)).toBe(false);expect(hasCapability('CARE_ASSISTANT',C.POLICY_PUBLISH)).toBe(false)});
 it('answers overdue from live open dates rather than completed history',()=>expect(matchTaskQuery(rows,'What is overdue?').map(x=>x.id)).toEqual(['1']));
 it('finds missing evidence',()=>expect(matchTaskQuery(rows,'What is awaiting evidence?').map(x=>x.id)).toEqual(['1']));
 it('finds owners and does not substitute unrelated tasks for an unknown name',()=>{expect(matchTaskQuery(rows,'What does Kellie own?').map(x=>x.id)).toEqual(['1']);expect(matchTaskQuery(rows,'What does Nobody own?')).toEqual([])});
 it('can retrieve completed history explicitly',()=>expect(matchTaskQuery(rows,'Show completed tasks').map(x=>x.id)).toEqual(['2']));
});
