import type {User} from '@prisma/client';
import {actionRecipients,notifyAction} from './action-notifications';
import {prisma} from './prisma';
import {CAPABILITIES as C,hasCapability} from './permissions';
export async function syncSafetyTasks(actor:User){
 if(!actor.organisationId)return {created:0,resolved:0};
 const org=actor.organisationId,now=new Date(),soon=new Date(now.getTime()+30*86400000),prefix=`safety:${org}:`;
 type Reminder={key:string;title:string;due:Date;href:string;cap:string;ownerId?:string|null;notes:string};const desired:Reminder[]=[];
 const [assets,docs,versions,assignments,people]=await Promise.all([prisma.premisesAsset.findMany({where:{active:true}}),prisma.premisesDocument.findMany({where:{active:true,expiryDate:{lte:soon}}}),prisma.complianceRecordVersion.findMany({where:{organisationId:org,status:{in:['UNDER_REVIEW','AWAITING_APPROVAL','PUBLISHED']},record:{archivedAt:null}},include:{record:true,acknowledgements:true}}),prisma.complianceAssignment.findMany({where:{organisationId:org}}),prisma.staffMember.findMany({where:{active:true,archivedAt:null,userId:{in:(await prisma.user.findMany({where:{organisationId:org,active:true},select:{id:true}})).map(u=>u.id)}}})]);
 const add=(r:Reminder)=>desired.push(r);
 for(const a of assets){if(a.nextDueDate&&a.nextDueDate<=soon)add({key:`asset:${a.id}:${a.nextDueDate.toISOString().slice(0,10)}`,title:`Inspection due: ${a.name}`,due:a.nextDueDate,href:`/dashboard/premises/assets/${a.qrToken}`,cap:C.PREMISES_VIEW,ownerId:people.find(p=>p.displayName===a.responsibleName)?.userId,notes:'Record the actual inspection and its evidence on the asset. This reminder follows the next due date.'});const d=a.details as Record<string,unknown>|null;if(typeof d?.nextService==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(d.nextService)&&new Date(d.nextService)<=soon)add({key:`service:${a.id}:${d.nextService}`,title:`Service due: ${a.name}`,due:new Date(d.nextService),href:`/dashboard/premises/assets/${a.qrToken}`,cap:C.PREMISES_VIEW,notes:'Record the service and next service date on the asset.'})}
 for(const d of docs)add({key:`document:${d.id}:${d.expiryDate!.toISOString().slice(0,10)}`,title:`Renewal due: ${d.title}`,due:d.expiryDate!,href:`/dashboard/premises?section=documents&record=${d.id}`,cap:C.PREMISES_VIEW,ownerId:people.find(p=>p.displayName===d.responsibleName)?.userId,notes:'Review and replace the document through Documents & Insurance. Previous uploaded versions are retained.'});
 for(const v of versions){const cap=v.record.recordType==='RAMS'?C.RAMS_VIEW:v.record.recordType==='COSHH'?C.COSHH_VIEW:C.POLICY_VIEW,href='/dashboard/premises/'+(v.record.recordType==='RAMS'?'rams':v.record.recordType==='COSHH'?'coshh':'policies')+'?record='+v.recordId,meta=(v.structuredContent||{}) as Record<string,unknown>;
 if(v.status!=='PUBLISHED')add({key:`approval:${v.id}:${v.status}`,title:`${v.status==='UNDER_REVIEW'?'Review':'Approval required'}: ${v.title}`,due:v.reviewDate||now,href,cap,ownerId:String((v.status==='UNDER_REVIEW'?meta.reviewerId:meta.approverId)||v.responsibleManagerId||''),notes:'Use the controlled document workflow. Assignment does not grant review or approval rights.'});
 else{if(v.reviewDate&&v.reviewDate<=soon)add({key:`review:${v.id}:${v.reviewDate.toISOString().slice(0,10)}`,title:`Review due: ${v.title}`,due:v.reviewDate,href,cap,ownerId:v.responsibleManagerId,notes:'Create and approve a new controlled revision after reviewing this document.'});if(['POLICY','RAMS'].includes(v.record.recordType)&&meta.acknowledgementRequired!==false){const outstanding=people.filter(p=>assignments.some(a=>a.versionId===v.id&&(a.allStaff||a.userId===p.userId||a.staffRole===p.jobRole))&&!v.acknowledgements.some(a=>a.userId===p.userId));if(outstanding.length)add({key:`ack:${v.id}`,title:`Acknowledgements outstanding: ${v.title}`,due:v.publishedAt||now,href:'/dashboard/premises/reports',cap:C.COMPLIANCE_REPORTS_VIEW,ownerId:v.responsibleManagerId,notes:`${outstanding.length} assigned staff have not acknowledged version ${v.version}. Staff must record their own acknowledgement.`})}}
 }
 let created=0,resolved=0;await prisma.$transaction(async tx=>{for(const d of desired){const sourceKey=prefix+d.key;const existing=await tx.operationalTask.findUnique({where:{sourceKey}});const owner=people.find(p=>p.userId===d.ownerId);const values={title:d.title.slice(0,191),dueDate:d.due,notes:d.notes,details:{organisationId:org,href:d.href,cap:d.cap,sourceManaged:true}};if(!existing){const task=await tx.operationalTask.create({data:{...values,sourceKey,startDate:d.due,endDate:d.due,assignedStaffId:owner?.id,owner:owner?.displayName,createdById:actor.id}});await tx.operationalTaskEvent.create({data:{taskId:task.id,actorId:actor.id,action:'SOURCE_REMINDER_CREATED',details:{reason:d.notes}}});created++;const recipients=(await actionRecipients(tx,d.cap as typeof C[keyof typeof C],C.STAFF_TASKS)).filter(u=>u.organisationId===org&&(!d.ownerId||u.id===d.ownerId));await notifyAction(tx,recipients,'safety:'+task.id,'SAFETY_REMINDER',task.id,d.title.slice(0,191),'/dashboard/staff/tasks?task='+task.id);if(owner)await tx.staffPortalNotification.upsert({where:{key:`safety:${task.id}:${owner.id}`},create:{key:`safety:${task.id}:${owner.id}`,staffId:owner.id,message:d.title.slice(0,191),href:'/staff/tasks'},update:{}})}else await tx.operationalTask.update({where:{id:existing.id},data:values})}const stale=await tx.operationalTask.findMany({where:{sourceKey:{startsWith:prefix,notIn:desired.map(d=>prefix+d.key)},status:{notIn:['COMPLETED','ARCHIVED','CANCELLED']}}});for(const t of stale){await tx.operationalTask.update({where:{id:t.id},data:{status:'COMPLETED'}});await tx.operationalTaskEvent.create({data:{taskId:t.id,actorId:actor.id,action:'SOURCE_REMINDER_RESOLVED',details:{reason:'The source no longer meets this reminder condition. This records reminder resolution, not certification or payment.'}}});resolved++}},{isolationLevel:'Serializable'});return {created,resolved};
}
export function canReadSafetyTask(user:User,details:unknown){const d=(details||{}) as Record<string,unknown>;return d.organisationId===user.organisationId&&typeof d.cap==='string'&&Object.values(C).includes(d.cap as typeof C[keyof typeof C])&&hasCapability(user.role,d.cap as typeof C[keyof typeof C],user.permissionOverrides)}
