import {describe,expect,it} from "vitest";
import {monthlyScreensaverIds,normaliseScreensaverSettings,resolveScreensaverScene,screensaverAllowedOnRoute,screensaverDefaults,screensaverSchema,visualPeriod} from "./screensaver";
describe("kiosk screensaver",()=>{
 it("migrates legacy cached settings",()=>{const settings=normaliseScreensaverSettings({screensaverEnabled:true,idleTimeoutSeconds:15,backgroundAnimationStyle:"halloween"});expect(settings.screensaverEnabled).toBe(true);expect(settings.backgroundAnimationStyle).toBe("october-halloween");expect(settings.wakeTransitionSeconds).toBe(screensaverDefaults.wakeTransitionSeconds)});
 it("uses safe automatic monthly defaults",()=>{expect(screensaverSchema.safeParse(screensaverDefaults).success).toBe(true);expect(screensaverDefaults.idleTimeoutSeconds).toBe(30);expect(screensaverDefaults.backgroundAnimationStyle).toBe("automatic-monthly");expect(screensaverDefaults.wakeTransitionSeconds).toBeGreaterThan(0)});
 it("resolves every local calendar month without overwriting automatic mode",()=>{monthlyScreensaverIds.forEach((id,index)=>expect(resolveScreensaverScene("automatic-monthly",new Date(2026,index,15))).toBe(id));expect(normaliseScreensaverSettings({backgroundAnimationStyle:"automatic-monthly"}).backgroundAnimationStyle).toBe("automatic-monthly")});
 it("accepts all monthly manual selections",()=>monthlyScreensaverIds.forEach(id=>expect(screensaverSchema.safeParse({...screensaverDefaults,backgroundAnimationStyle:id}).success).toBe(true)));
 it("selects configured brightness",()=>{expect(visualPeriod(new Date(2026,6,26,8),screensaverDefaults)).toEqual({mode:"day",brightness:45});expect(visualPeriod(new Date(2026,6,26,20),screensaverDefaults).mode).toBe("evening");expect(visualPeriod(new Date(2026,6,26,23),screensaverDefaults).mode).toBe("night")});
 it("covers ordinary kiosk workflows but never setup, emergency or manager routes",()=>{for(const route of["/","/clock","/register","/visitors","/live","/offline"])expect(screensaverAllowedOnRoute(route)).toBe(true);for(const route of["/setup","/emergency","/dashboard","/dashboard/payroll"])expect(screensaverAllowedOnRoute(route)).toBe(false)});
});
