import {z} from "zod";
const text=z.string().trim().max(6000);const short=z.string().trim().max(191);const date=z.union([z.literal(""),z.string().date()]);
export const contactSchema=z.object({name:short,relationship:short,phone:short,alternativePhone:short,email:z.union([z.literal(""),z.string().email().max(191)]),notes:text}).strict();
export const hrPersonal=z.object({legalName:short.optional(),preferredName:short.optional(),dateOfBirth:date.optional(),addressLine1:short.optional(),addressLine2:short.optional(),town:short.optional(),county:short.optional(),postcode:short.optional(),personalPhone:short.optional(),personalEmail:z.union([z.literal(""),z.string().email().max(191)]).optional(),emergencyContacts:z.array(contactSchema).max(5).optional()}).strict();
export const hrOwnPersonal=hrPersonal.omit({legalName:true,dateOfBirth:true}).strict();
export const hrEmployment=z.object({department:short.optional(),employmentStatus:short.optional(),contractType:short.optional(),workLocation:short.optional(),lineManagerId:z.union([z.literal(""),z.string().uuid()]).optional(),probationEndDate:date.optional(),leavingReason:text.optional(),employmentNotes:text.optional()}).strict();
export const hrOwnMedical=z.object({medicalInformation:text.optional(),allergies:text.optional(),emergencyMedicalInformation:text.optional(),reasonableAdjustments:text.optional()}).strict();
export const hrMedical=hrOwnMedical.extend({workplaceRestrictions:text.optional(),occupationalHealthNotes:text.optional(),reviewDate:date.optional()}).strict();
export const ownHrChange=z.object({key:z.string().uuid(),personal:hrOwnPersonal.optional(),medical:hrOwnMedical.optional(),reason:z.string().trim().min(1).max(6000)}).strict().refine(v=>Object.keys(v.personal||{}).length+Object.keys(v.medical||{}).length>0,"Enter at least one change.");
export const personalFields=[['legalName','Legal name'],['preferredName','Preferred name'],['dateOfBirth','Date of birth'],['addressLine1','Address line 1'],['addressLine2','Address line 2'],['town','Town or city'],['county','County'],['postcode','Postcode'],['personalPhone','Personal telephone'],['personalEmail','Personal email']] as const;
export const employmentFields=[['department','Department / team'],['employmentStatus','Employment status'],['contractType','Contract type'],['workLocation','Work location'],['probationEndDate','Probation end date'],['leavingReason','Leaving reason'],['employmentNotes','Employment notes']] as const;
export const medicalFields=[['medicalInformation','Relevant medical information'],['allergies','Allergies'],['emergencyMedicalInformation','Emergency medical information'],['reasonableAdjustments','Reasonable adjustments'],['workplaceRestrictions','Workplace restrictions'],['occupationalHealthNotes','Occupational-health notes'],['reviewDate','Review date']] as const;
export function ownMedical(value:unknown){const p=hrOwnMedical.safeParse(Object.fromEntries(Object.entries((value||{}) as Record<string,unknown>).filter(([k])=>k in hrOwnMedical.shape)));return p.success?p.data:{}}
