import {fromZonedTime} from "date-fns-tz";
import {z} from "zod";
import {generatePatternOccurrences, type PatternInterval} from "./operations-core";

export const workingDaysInput=z.object({effectiveStart:z.string().date(),days:z.array(z.object({dayOfWeek:z.number().int().min(0).max(6),startTime:z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/),endTime:z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/)}).refine(day=>day.endTime>day.startTime,"End time must be after start time.")).max(7)}).refine(value=>new Set(value.days.map(day=>day.dayOfWeek)).size===value.days.length,"Choose each weekday once.");
export const staffAbsenceInput=z.object({staffId:z.string().uuid(),type:z.enum(["ANNUAL_LEAVE","SICKNESS"]),startDate:z.string().date(),endDate:z.string().date(),notes:z.string().trim().max(2000).optional()}).refine(value=>value.endDate>=value.startDate&&Date.parse(value.endDate)-Date.parse(value.startDate)<=366*86400000,"Choose a valid absence of up to one year.");
type Shift={premisesName?:string|null;staffId:string;date:Date;startAt:Date;endAt:Date;status:string;role?:string|null;patternId?:string|null;generationKey:string;staff:{displayName:string;startDate?:Date;endDate?:Date|null}};
type Pattern={id:string;staffId:string;effectiveStart:Date;effectiveEnd:Date|null;timezone:string;cycleWeeks:number;intervals:PatternInterval[];staff:{displayName:string;startDate:Date;endDate:Date|null}};
type Absence={staffId:string;startDate:Date;endDate:Date;startTime?:string|null;endTime?:string|null};
export function plannedStaffShifts(patterns:Pattern[],stored:Shift[],absences:Absence[],start:Date,end:Date):Shift[]{
 const projected:Shift[]=patterns.flatMap(pattern=>generatePatternOccurrences({patternId:pattern.id,effectiveStart:pattern.effectiveStart,effectiveEnd:pattern.effectiveEnd,rangeStart:start,rangeEnd:end,timezone:pattern.timezone,cycleWeeks:pattern.cycleWeeks,intervals:pattern.intervals}).map(shift=>({...shift,staffId:pattern.staffId,patternId:pattern.id,status:"SCHEDULED",staff:pattern.staff})));
 const storedKeys=new Set(stored.map(shift=>shift.generationKey));
 return [...stored,...projected.filter(shift=>!storedKeys.has(shift.generationKey))].filter(shift=>shift.status!=="CANCELLED"&&(!shift.staff.startDate||shift.date>=shift.staff.startDate)&&(!shift.staff.endDate||shift.date<=shift.staff.endDate)&&!absences.some(absence=>!absence.startTime&&absence.staffId===shift.staffId&&absence.startDate<=shift.date&&absence.endDate>=shift.date)).flatMap(shift=>{
 let parts=[shift];for(const a of absences.filter(a=>a.startTime&&a.endTime&&a.staffId===shift.staffId&&a.startDate<=shift.date&&a.endDate>=shift.date)){const key=shift.date.toISOString().slice(0,10),start=fromZonedTime(key+"T"+a.startTime+":00","Europe/London"),end=fromZonedTime(key+"T"+a.endTime+":00","Europe/London");parts=parts.flatMap(p=>end<=p.startAt||start>=p.endAt?[p]:[...(start>p.startAt?[{...p,endAt:start,generationKey:p.generationKey+":before-leave"}]:[]),...(end<p.endAt?[{...p,startAt:end,generationKey:p.generationKey+":after-leave"}]:[])]); }return parts;});
}
