import {describe,it,expect} from "vitest";
import {readFileSync} from "node:fs";
import {requestInput,portalPin,staffDateRange,requestReviewAllowed} from "./staff-area-input";
import {hasCapability,CAPABILITIES} from "./permission-catalog";
import {plannedStaffShifts} from "./staff-planning";
import {canReviewStaffRequest} from "./staff-task-access";
import type {User} from "@prisma/client";
describe("Staff Area security and request rules",()=>{
 it("requires a separate sufficiently long numeric portal PIN",()=>{expect(portalPin.safeParse('1234').success).toBe(false);expect(portalPin.safeParse('abcdefgh').success).toBe(false);expect(portalPin.safeParse('93746182').success).toBe(true)});
 it("rejects inverted dates and incomplete partial days",()=>{const base={key:crypto.randomUUID(),type:'LEAVE',startDate:'2026-10-12',endDate:'2026-10-13'};expect(requestInput.safeParse(base).success).toBe(true);expect(requestInput.safeParse({...base,endDate:'2026-10-01'}).success).toBe(false);expect(requestInput.safeParse({...base,startTime:'09:00'}).success).toBe(false)});
 it("requires a concern description and declaration",()=>{const base={key:crypto.randomUUID(),type:'CONCERN'};expect(requestInput.safeParse(base).success).toBe(false);expect(requestInput.safeParse({...base,description:'A concern',declaration:true}).success).toBe(true)});
 it("allows a self-certification draft without declaring it submitted",()=>{const v={key:crypto.randomUUID(),type:'SICKNESS',startDate:'2026-09-22',endDate:'2026-09-23',selfCertification:'Draft',draft:true};expect(requestInput.safeParse(v).success).toBe(true);expect(requestInput.safeParse({...v,draft:false}).success).toBe(false)});
 it("does not automatically grant confidential review to administrators or directors",()=>{for(const role of ['ADMINISTRATOR','DIRECTOR','MANAGER'] as const)expect(hasCapability(role,CAPABILITIES.STAFF_CONCERNS_REVIEW)).toBe(false);expect(hasCapability('MANAGER',CAPABILITIES.STAFF_CONCERNS_REVIEW,{'staff-concerns.review':true})).toBe(true)});
 it("excludes a named reviewer even with explicit permission",()=>{expect(requestReviewAllowed('CONCERN',['staff-concerns.review'],'reviewer',['reviewer'])).toBe(false);const user={id:'reviewer',name:'Test Manager',email:'manager@example.test',username:'manager',organisationId:'org',role:'ADMINISTRATOR',permissionOverrides:{'staff-concerns.review':true}} as unknown as User;expect(canReviewStaffRequest(user,{type:'CONCERN',organisationId:'org',involvedUserIds:[],details:{peopleInvolved:'Test Manager'}})).toBe(false);expect(canReviewStaffRequest(user,{type:'CONCERN',organisationId:'other',involvedUserIds:[],details:{}})).toBe(false)});
 it("validates calendar months",()=>{expect(()=>staffDateRange('2026-13')).toThrow();expect(staffDateRange('2026-02').end.toISOString()).toBe('2026-03-01T00:00:00.000Z')});
 it("splits partial-day leave without removing the whole shift",()=>{const date=new Date('2026-09-22'),shift={staffId:'s',date,startAt:new Date('2026-09-22T08:00:00Z'),endAt:new Date('2026-09-22T16:00:00Z'),status:'SCHEDULED',generationKey:'s',staff:{displayName:'Staff'}};const result=plannedStaffShifts([],[shift],[{staffId:'s',startDate:date,endDate:date,startTime:'12:00',endTime:'14:00'}],date,date);expect(result).toHaveLength(2);expect(result[0].endAt.toISOString()).toBe('2026-09-22T11:00:00.000Z');expect(result[1].startAt.toISOString()).toBe('2026-09-22T13:00:00.000Z')});
 it("uses an independent staff PWA identity and scope",()=>{const manifest=JSON.parse(readFileSync('public/staff/manifest.webmanifest','utf8'));expect(manifest.name).toBe('STARS Staff');expect(manifest.scope).toBe('/staff/');expect(manifest.start_url).toBe('/staff/');expect(manifest.id).not.toBe('/');expect(manifest.icons.map((i:{sizes:string})=>i.sizes)).toEqual(['192x192','512x512'])});
 it("never caches authenticated staff pages or API responses",()=>{const sw=readFileSync('public/staff/sw.js','utf8');expect(sw).toContain('u.pathname.startsWith("/api/")');expect(sw).not.toContain('cache.put');expect(sw).not.toContain('"/staff/",');const root=readFileSync('public/sw.js','utf8');expect(root).toContain('key.startsWith("stars-connect-shell-")');expect(root).toContain('url.pathname.startsWith("/staff/")')});
});
