import { describe, expect, it } from "vitest";
import { studentRecordPdf } from "./student-record-pdf";

const tinyJpeg = Buffer.from("/9j/4AAQSkZJRgABAQAAAQABAAD/2Q==", "base64");

describe("complete student record PDF", () => {
  it("creates a branded confidential PDF and paginates long records", () => {
    const pdf = studentRecordPdf({
      logoJpeg: tinyJpeg,
      organisationName: "STARS Day Service",
      studentName: "Example Student",
      studentReference: "STU-001",
      generatedBy: "Alex Administrator",
      generatedAt: "16/08/2026 17:30",
      sections: [{
        title: "Attendance history",
        rows: Array.from({ length: 80 }, (_, index) => ({ label: `Day ${index + 1}`, value: "Present with an attendance record retained by STARS Connect" })),
      }],
    });
    const source = pdf.toString("latin1");
    expect(source.startsWith("%PDF-1.4")).toBe(true);
    expect(source).toContain("CONFIDENTIAL");
    expect(source).toContain("COMPLETE STUDENT RECORD");
    expect(source).toContain("Example Student");
    expect(source).toContain("STU-001");
    expect(source).toContain("Generated by Alex Administrator");
    expect(source.match(/\/Type \/Page\b/g)?.length).toBeGreaterThan(1);
  });

  it("renders RAMS as a landscape risk matrix rather than a student record", () => {
    const pdf = studentRecordPdf({
      logoJpeg: tinyJpeg,
      organisationName: "STARS Day Service",
      studentName: "RAMS - Community outing",
      studentReference: "RAMS-2026-001 | Version 1 | DRAFT",
      generatedBy: "Alex Administrator",
      generatedAt: "16/08/2026 18:00",
      sections: [
        { title: "Document control", rows: [{ label: "Status", value: "DRAFT" }, { label: "Assessment date", value: "16/08/2026" }, { label: "Review date", value: "16/08/2027" }, { label: "Responsible person", value: "Team Leader" }, { label: "Assessment author", value: "Alex Administrator" }] },
        { title: "Activity and scope", rows: [{ label: "Activity / task", value: "Community outing" }, { label: "Location", value: "Local park" }, { label: "Selected students", value: "Example Student" }, { label: "Assigned staff", value: "Team Leader" }] },
        { title: "Hazard and risk assessment", rows: [{ label: "Hazard 1: Road traffic", value: "Who may be harmed: Students and staff\nHow: Collision while crossing\nExisting controls: Staff supervision\nInitial risk: 4 x 4 = 16\nFurther controls: Use designated crossing\nResidual risk: 2 x 3 = 6\nOwner / target: Team Leader / Before departure" }] },
        { title: "Method statement", rows: [{ label: "Overview", value: "Brief staff and students before departure." }, { label: "1. Preparation", value: "Check attendance and emergency contacts.\nResponsible: Team Leader\nSafety checks: Head count complete\nStop-work conditions: Missing person\nEmergency response: Contact emergency services" }] },
        { title: "Equipment and emergency arrangements", rows: [{ label: "PPE", value: "High visibility vest" }, { label: "Equipment", value: "First aid kit" }, { label: "Emergency arrangements", value: "Call 999" }] },
        { title: "Readiness checklist", rows: [{ label: "Staff briefed", value: "Complete" }] },
        { title: "Approval and publication", rows: [{ label: "Approved", value: "Not approved" }, { label: "Important notice", value: "Pilot draft" }] },
      ],
    });
    const source = pdf.toString("latin1");
    expect(source).toContain("RAMS");
    expect(source).toContain("Community outing");
    expect(source).toContain("FURTHER CONTROLS");
    expect(source).toContain("SAFE METHOD");
    expect(source).toContain("Staff briefing and acknowledgement");
    expect(source).toContain("PRINTED NAME");
    expect(source).toContain("I confirm that I have read and understood this RAMS");
    expect(source).toContain("/MediaBox [0 0 842 595]");
    expect(source).not.toContain("AI-generated");
    expect(source).not.toContain("COMPLETE STUDENT RECORD");
  });
});
