export type StudentRecordPdfRow = { label: string; value: string };
export type StudentRecordPdfSection = { title: string; rows: StudentRecordPdfRow[] };

export type StudentRecordPdfInput = {
  logoJpeg: Buffer;
  organisationName: string;
  studentName: string;
  studentReference: string;
  generatedBy: string;
  generatedAt: string;
  sections: StudentRecordPdfSection[];
};

const PAGE_WIDTH = 595;
const PAGE_HEIGHT = 842;
const PURPLE = "0.32 0.13 0.36";
const PURPLE_SOFT = "0.97 0.95 0.98";
const INK = "0.13 0.11 0.14";
const MUTED = "0.40 0.37 0.41";
const BORDER = "0.87 0.84 0.88";

function esc(value: string) {
  return value.normalize("NFKD").replace(/[^\x20-\x7E]/g, "").replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");
}

function text(value: string, x: number, y: number, size = 9, bold = false, colour = INK) {
  return `BT /${bold ? "F2" : "F1"} ${size} Tf ${colour} rg ${x} ${y} Td (${esc(value)}) Tj ET`;
}

function rect(x: number, y: number, width: number, height: number, fill: string, stroke?: string) {
  return `${fill} rg ${stroke || fill} RG ${x} ${y} ${width} ${height} re B`;
}

function line(x1: number, y1: number, x2: number, y2: number, colour = BORDER) {
  return `${colour} RG 0.6 w ${x1} ${y1} m ${x2} ${y2} l S`;
}

function wrap(value: string, maximum = 78) {
  const result: string[] = [];
  for (const paragraph of String(value || "Not recorded").replace(/\r/g, "").split("\n")) {
    const words = paragraph.trim().split(/\s+/).filter(Boolean);
    if (!words.length) { result.push(""); continue; }
    let current = "";
    for (const word of words) {
      if (!current) current = word;
      else if (`${current} ${word}`.length <= maximum) current += ` ${word}`;
      else { result.push(current); current = word; }
    }
    if (current) result.push(current);
  }
  return result.length ? result : ["Not recorded"];
}

function pageHeader(input: StudentRecordPdfInput, continued: boolean) {
  return [
    rect(0, 0, PAGE_WIDTH, PAGE_HEIGHT, "1 1 1"),
    "q 100 0 0 73 42 747 cm /Logo Do Q",
    rect(354, 758, 199, 64, PURPLE),
    text("CONFIDENTIAL", 370, 801, 7.5, true, "1 1 1"),
    text("COMPLETE STUDENT RECORD", 370, 779, 10.5, true, "1 1 1"),
    line(42, 735, 553, 735, PURPLE),
    text(continued ? `${input.studentName} - record continued` : input.studentName, 42, 710, 15, true),
    text(`Reference: ${input.studentReference}`, 42, 693, 8.5, false, MUTED),
  ];
}

export function studentRecordPdf(input: StudentRecordPdfInput) {
  const pages: string[][] = [];
  let commands = pageHeader(input, false);
  let y = 660;
  const newPage = () => { pages.push(commands); commands = pageHeader(input, true); y = 660; };
  const ensure = (height: number) => { if (y - height < 72) newPage(); };

  for (const section of input.sections) {
    const rows = section.rows.filter(row => row.value.trim());
    if (!rows.length) continue;
    ensure(42);
    commands.push(rect(42, y - 5, 511, 26, PURPLE_SOFT, BORDER), text(section.title.toUpperCase(), 52, y + 4, 8, true, PURPLE));
    y -= 34;
    for (const row of rows) {
      const valueLines = wrap(row.value);
      const height = Math.max(29, 14 + valueLines.length * 11);
      ensure(height);
      commands.push(text(row.label, 50, y, 7.3, true, MUTED));
      valueLines.forEach((value, index) => commands.push(text(value, 180, y - index * 11, 8.2)));
      commands.push(line(42, y - height + 8, 553, y - height + 8));
      y -= height;
    }
    y -= 8;
  }
  pages.push(commands);

  const pageCount = pages.length;
  const regularRef = 3 + pageCount * 2;
  const boldRef = regularRef + 1;
  const logoRef = boldRef + 1;
  const pageRefs = pages.map((_, index) => 3 + index * 2);
  const objects: Array<string | Buffer> = [
    "<< /Type /Catalog /Pages 2 0 R >>",
    `<< /Type /Pages /Kids [${pageRefs.map(ref => `${ref} 0 R`).join(" ")}] /Count ${pageCount} >>`,
  ];
  pages.forEach((page, index) => {
    page.push(
      line(42, 55, 553, 55),
      text(`Generated by ${input.generatedBy} on ${input.generatedAt}`, 42, 39, 7, false, MUTED),
      text(input.organisationName, 42, 22, 7, false, MUTED),
      text(`Page ${index + 1} of ${pageCount}`, 503, 22, 7, false, MUTED),
    );
    const body = page.join("\n");
    const pageRef = 3 + index * 2;
    objects.push(
      `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${PAGE_WIDTH} ${PAGE_HEIGHT}] /Resources << /Font << /F1 ${regularRef} 0 R /F2 ${boldRef} 0 R >> /XObject << /Logo ${logoRef} 0 R >> >> /Contents ${pageRef + 1} 0 R >>`,
      `<< /Length ${Buffer.byteLength(body)} >>\nstream\n${body}\nendstream`,
    );
  });
  objects.push(
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>",
    Buffer.concat([Buffer.from(`<< /Type /XObject /Subtype /Image /Width 260 /Height 189 /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${input.logoJpeg.length} >>\nstream\n`), input.logoJpeg, Buffer.from("\nendstream")]),
  );
  let pdf = Buffer.from("%PDF-1.4\n", "latin1");
  const offsets = [0];
  objects.forEach((object, index) => {
    offsets.push(pdf.length);
    pdf = Buffer.concat([pdf, Buffer.from(`${index + 1} 0 obj\n`, "latin1"), Buffer.isBuffer(object) ? object : Buffer.from(object, "latin1"), Buffer.from("\nendobj\n", "latin1")]);
  });
  const xref = pdf.length;
  const trailer = `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n${offsets.slice(1).map(offset => `${String(offset).padStart(10, "0")} 00000 n `).join("\n")}\ntrailer << /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;
  return Buffer.concat([pdf, Buffer.from(trailer, "latin1")]);
}
