import { describe, expect, it } from "vitest";
import { studentRecordPdf } from "./student-record-pdf";

const tinyJpeg = Buffer.from("/9j/4AAQSkZJRgABAQAAAQABAAD/2Q==", "base64");

describe("complete student record PDF", () => {
  it("creates a branded confidential PDF and paginates long records", () => {
    const pdf = studentRecordPdf({
      logoJpeg: tinyJpeg,
      organisationName: "STARS Day Service",
      studentName: "Example Student",
      studentReference: "STU-001",
      generatedBy: "Alex Administrator",
      generatedAt: "16/08/2026 17:30",
      sections: [{
        title: "Attendance history",
        rows: Array.from({ length: 80 }, (_, index) => ({ label: `Day ${index + 1}`, value: "Present with an attendance record retained by STARS Connect" })),
      }],
    });
    const source = pdf.toString("latin1");
    expect(source.startsWith("%PDF-1.4")).toBe(true);
    expect(source).toContain("CONFIDENTIAL");
    expect(source).toContain("COMPLETE STUDENT RECORD");
    expect(source).toContain("Example Student");
    expect(source).toContain("STU-001");
    expect(source).toContain("Generated by Alex Administrator");
    expect(source.match(/\/Type \/Page\b/g)?.length).toBeGreaterThan(1);
  });
});

