import {describe,it,expect} from "vitest";
import {queueCounts,requestTask,sortTasks,taskClosed,taskStatus,taskTiming,type QueueTask,type RequestRow} from "./task-queue";
const task=(id:string,overrides:Partial<QueueTask>={}):QueueTask=>({id,source:"operational",title:id,category:"Operations",status:"OPEN",priority:"NORMAL",owner:"Unassigned",...overrides});
const request=(overrides:Partial<RequestRow>={}):RequestRow=>({id:"request-1",type:"PROFILE",status:"COMPLETED",createdAt:"2026-09-23T14:00:00Z",staff:{displayName:"Example Employee"},details:{description:"Contact details updated"},events:[],documents:[],...overrides});
describe("management task queue",()=>{
 it("labels contact update audit records without turning them into decisions",()=>{const row=requestTask(request(),[],"me");expect(row.title).toBe("Contact details updated — Example Employee");expect(row.decision).toBe(false);expect(taskClosed(row.status)).toBe(true)});
 it("retains separate completed submissions and their identifiers",()=>{const rows=[requestTask(request(),[],"me"),requestTask(request({id:"request-2"}),[],"me")];expect(sortTasks(rows)).toHaveLength(2);expect(new Set(rows.map(r=>r.id)).size).toBe(2)});
 it("counts assigned-to-me and unassigned authorised requests, not another reviewer",()=>{const rows=[undefined,"me","another"].map((assignedUserId,i)=>requestTask(request({id:String(i),status:"NEW",assignedUserId}),[],"me"));expect(queueCounts(rows).decision).toBe(2)});
 it("keeps confidential details out of queue subjects and descriptions",()=>{const row=requestTask(request({type:"CONCERN",details:{description:"PRIVATE CONTENT",peopleInvolved:"PRIVATE NAME"}}),[],"me");expect(JSON.stringify(row)).not.toContain("PRIVATE")});
 it("orders urgent, overdue and decision work ahead of historical billing and closed records",()=>{const rows=[task("history",{historical:true,dueDate:"2026-01-31"}),task("closed",{status:"COMPLETED"}),task("decision",{decision:true}),task("overdue",{dueDate:"2026-09-22"}),task("urgent",{priority:"URGENT"})];expect(sortTasks(rows,"2026-09-24").map(r=>r.id)).toEqual(["urgent","overdue","decision","history","closed"]);expect(rows[0].status).toBe("OPEN")});
 it("sorts ties deterministically",()=>{expect(sortTasks([task("z"),task("a")]).map(r=>r.id)).toEqual(["a","z"])});
 it("uses the current calendar week and excludes completed work from counts",()=>{const rows=[task("this week",{dueDate:"2026-09-27",awaitingEvidence:true}),task("next week",{dueDate:"2026-09-28"}),task("overdue",{dueDate:"2026-09-23"}),task("closed",{dueDate:"2026-09-23",status:"COMPLETED"})];expect(queueCounts(rows,"2026-09-24")).toEqual({decision:0,week:1,overdue:1,evidence:1})});
 it("keeps due today out of overdue and presents overdue evidence clearly",()=>{expect(taskTiming(task("today",{dueDate:"2026-09-24"}),"2026-09-24").overdue).toBe(false);expect(taskStatus(task("proof",{status:"AWAITING_EVIDENCE"}),"2026-09-24").label).toBe("Awaiting evidence")});
 it("treats reviewed confirmations as closed and pending replies as waiting",()=>{expect(taskClosed("REVIEWED")).toBe(true);expect(taskStatus(task("reply",{source:"confirmation",status:"PENDING"})).label).toBe("Awaiting staff confirmation")});
 it("uses the London date for overnight event deadlines",()=>{expect(taskTiming(task("event",{dueDate:"2026-09-23T23:30:00Z"}),"2026-09-24").overdue).toBe(false)});
});
