import "fake-indexeddb/auto";
import {beforeEach,afterEach,it,expect,vi} from "vitest";
import {newDraft,loadLocal,saveLocal,syncDraft,type Draft} from "./vehicle-local";
import {db} from "./local-db";
let draft:Draft;
beforeEach(async()=>{await (await db()).clear("metadata");draft=newDraft({id:"staff-a",name:"Sample Staff"},{id:crypto.randomUUID(),name:"Sample Bus",registration:"TEST 1",fuelType:"DIESEL",config:{},status:"ACTIVE",mileage:100,checks:[]})});
afterEach(()=>vi.unstubAllGlobals());
it("preserves draft answers and photographs across database reopen",async()=>{draft.images=[{id:crypto.randomUUID(),blob:new Blob(["image-data"],{type:"image/jpeg"})}];draft.step=4;await saveLocal("draft:staff-a",draft);(await db()).close();const saved=await loadLocal<Draft>("draft:staff-a");expect(saved?.step).toBe(4);expect(await saved?.images[0].blob.text()).toBe("image-data");expect(await loadLocal("draft:staff-b")).toBeUndefined()});
it("does not mark a failed upload as synced",async()=>{draft.state="PENDING";await saveLocal("draft:staff-a",draft);vi.stubGlobal("fetch",vi.fn().mockResolvedValueOnce(Response.json({user:{id:"staff-a"}})).mockResolvedValueOnce(Response.json({error:"Offline"},{status:503})));await expect(syncDraft(draft)).rejects.toThrow("Offline");expect((await loadLocal<Draft>("draft:staff-a"))?.state).toBe("PENDING")});
it("does not sync a draft under a different account",async()=>{vi.stubGlobal("fetch",vi.fn().mockResolvedValue(Response.json({user:{id:"staff-b"}})));await expect(syncDraft(draft)).rejects.toThrow("account that started");expect(fetch).toHaveBeenCalledTimes(1)});
it("uses the same check and image UUIDs on retries",async()=>{draft.state="PENDING";draft.images=[{id:crypto.randomUUID(),blob:new Blob(["image"])}];const calls:RequestInit[]=[];vi.stubGlobal("fetch",vi.fn(async(url:string,options?:RequestInit)=>{if(options?.method)calls.push(options);return Response.json(url.includes("vehicles")?{user:{id:"staff-a"}}:url.includes("evidence")?{id:draft.images[0].id}:{outcome:"PASSED"})}));await syncDraft(draft);await syncDraft(draft);expect((calls[0].body as FormData).get("id")).toBe((calls[2].body as FormData).get("id"));expect(JSON.parse(String(calls[1].body)).id).toBe(JSON.parse(String(calls[3].body)).id);expect((await loadLocal<Draft>("draft:staff-a"))?.state).toBe("SYNCED")});
it("sends staff uploads through the staff-authenticated endpoints",async()=>{draft.state="PENDING";draft.images=[{id:crypto.randomUUID(),blob:new Blob(["image"])}];const urls:string[]=[];vi.stubGlobal("fetch",vi.fn(async(url:string)=>{urls.push(url);return Response.json(url.includes("vehicles")?{user:{id:"staff-a"}}:url.includes("evidence")?{id:draft.images[0].id}:{outcome:"PASSED"})}));await syncDraft(draft,"/api/staff-area/vehicle");expect(urls).toEqual(["/api/staff-area/vehicle/vehicles","/api/staff-area/vehicle/evidence","/api/staff-area/vehicle/checks"])});

it("starts a fresh UK day while retaining unfinished photographs",async()=>{const {rollDailyDraft,unfinishedChecks}=await import("./vehicle-local");draft.clientStartedAt="2026-09-22T10:00:00Z";draft.state="PENDING";draft.images=[{id:crypto.randomUUID(),blob:new Blob(["retained"])}];const fresh=await rollDailyDraft(draft,[draft.vehicle],new Date("2026-09-22T23:01:00Z"));expect(fresh?.id).not.toBe(draft.id);expect(fresh?.state).toBe("DRAFT");expect(fresh?.images).toEqual([]);expect(fresh?.initialImageId).toBe("");const archived=await unfinishedChecks(draft.userId);expect(archived[0].id).toBe(draft.id);expect(await archived[0].images[0].blob.text()).toBe("retained");expect(await unfinishedChecks("another-user")).toEqual([])});
it("keeps a same-day draft and does not queue submitted previous days",async()=>{const {rollDailyDraft,unfinishedChecks}=await import("./vehicle-local");draft.clientStartedAt="2026-09-22T10:00:00Z";expect(await rollDailyDraft(draft,[draft.vehicle],new Date("2026-09-22T12:00:00Z"))).toBe(draft);draft.state="SYNCED";await rollDailyDraft(draft,[draft.vehicle],new Date("2026-09-23T12:00:00Z"));expect(await unfinishedChecks(draft.userId)).toEqual([])});
it("amends with a new submission ID and renewed declaration while retaining evidence",async()=>{const {amendDraft}=await import("./vehicle-local");draft.state="SYNCED";draft.clientStartedAt="2026-09-22T10:00:00Z";draft.initialImageId="existing-photo";draft.declaration=true;const amended=amendDraft(draft,new Date("2026-09-22T12:00:00Z"));expect(amended.id).not.toBe(draft.id);expect(amended.amendmentOf).toBe(draft.id);expect(amended.declaration).toBe(false);expect(amended.initialImageId).toBe("existing-photo");expect(()=>amendDraft(draft,new Date("2026-09-23T12:00:00Z"))).toThrow("today")});

it("loads only the signed-in person's latest check in each entry point",async()=>{const {latestDailyDraft}=await import("./vehicle-local");vi.stubGlobal("fetch",vi.fn().mockImplementation(async()=>Response.json([{id:"saved",userId:draft.userId,staffName:draft.staffName,clientStartedAt:new Date().toISOString(),mileage:102,outcome:"PASSED",revision:2,snapshot:{initialImageId:"photo",answers:[{key:"fuel",response:"PASS",severity:null,notes:"",imageIds:[],secured:false}]}}])));for(const api of ["/api/fleet","/api/staff-area/vehicle","/api/driver/vehicle"]){const saved=await latestDailyDraft({id:draft.userId,name:draft.staffName},draft.vehicle,api);expect(saved.id).toBe("saved");expect(saved.state).toBe("SYNCED");expect(saved.answers[0].severity).toBeUndefined();expect(fetch).toHaveBeenLastCalledWith(expect.stringContaining(api+"/checks?vehicle="),{cache:"no-store"});expect(fetch).toHaveBeenLastCalledWith(expect.stringContaining("&own=1&from="),expect.anything())}});
