import {CAPABILITIES as C} from "@/lib/permissions";
import {recordPremisesInspection} from "@/lib/premises-inspections";
import {Prisma} from "@prisma/client";
import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { withRole, withAnyCapability, jsonError, requestContext } from "@/lib/api";
import { audit } from "@/lib/audit";
import { actionSchema, assetSchema, inspectionSchema, premisesDocumentSchema } from "@/lib/premises-input";

const date=(value?:string|null)=>value?new Date(`${value}T00:00:00Z`):null;
const assetData=(p:ReturnType<typeof assetSchema.parse>,userId:string)=>({...(p.reference!==undefined?{reference:p.reference||null}:{}),...(p.details?{details:p.details as Prisma.InputJsonValue}:{}),name:p.name,category:p.category,location:p.location||null,manufacturer:p.manufacturer||null,model:p.model||null,serialNumber:p.serialNumber||null,responsibleName:p.responsibleName||null,serviceProvider:p.serviceProvider||null,recurrenceDays:p.recurrenceDays||null,nextDueDate:date(p.nextDueDate),notes:p.notes||null,updatedById:userId});
const actionData=(p:ReturnType<typeof actionSchema.parse>,userId:string)=>({assetId:p.assetId||null,inspectionId:p.inspectionId||null,title:p.title,priority:p.priority,status:p.status,assignedTo:p.assignedTo||null,dueDate:date(p.dueDate),completedAt:p.status==="COMPLETED"?new Date():null,notes:p.notes||null,updatedById:userId});
const documentData=(p:ReturnType<typeof premisesDocumentSchema.parse>,userId:string)=>({responsibleName:p.responsibleName||null,assetId:p.assetId||null,title:p.title,documentType:p.documentType,reference:p.reference||null,provider:p.provider||null,issuedDate:date(p.issuedDate),expiryDate:date(p.expiryDate),documentUrl:p.documentUrl||null,notes:p.notes||null,updatedById:userId});

export async function GET(req:NextRequest){return withRole(req,"DIRECTOR",async()=>{const[assets,inspections,actions,documents]=await Promise.all([
  prisma.premisesAsset.findMany({where:{active:true},include:{_count:{select:{inspections:true,actions:true,documents:true}}},orderBy:[{nextDueDate:"asc"},{name:"asc"}]}),
  prisma.premisesInspection.findMany({include:{asset:{select:{name:true,category:true}}},orderBy:{completedDate:"desc"},take:250}),
  prisma.premisesCorrectiveAction.findMany({where:{status:{not:"ARCHIVED"}},include:{asset:{select:{name:true}}},orderBy:[{status:"asc"},{dueDate:"asc"}]}),
  prisma.premisesDocument.findMany({where:{active:true},include:{asset:{select:{name:true}}},orderBy:[{expiryDate:"asc"},{title:"asc"}]})]);
  return NextResponse.json({assets,inspections,actions,documents});
})}

export async function POST(req:NextRequest){const body=await req.json().catch(()=>null);return withAnyCapability(req,[C.PREMISES_MANAGE,...(body?.type==="asset"?[C.ASSET_MANAGE]:body?.type==="inspection"?[C.INSPECTION_COMPLETE]:[])],async user=>{const type=body?.type,data=body?.data;
  if(type==="asset"){const p=assetSchema.safeParse(data);if(!p.success)return jsonError("Please check the asset details.",422);const row=await prisma.premisesAsset.create({data:{...assetData(p.data,user.id),createdById:user.id}});await audit("PREMISES_ASSET_CREATED",{actorType:"USER",actorId:user.id,entityType:"PremisesAsset",entityId:row.id,afterValue:row,...requestContext(req)});return NextResponse.json(row,{status:201})}
  if(type==="inspection"){const p=inspectionSchema.safeParse(data);if(!p.success)return jsonError("Please check the inspection details.",422);return NextResponse.json(await recordPremisesInspection(user,p.data),{status:201})}
  if(type==="action"){if(data?.status==="COMPLETED")return jsonError("Create the action first, then complete it in Tasks with evidence and verification.",409);const p=actionSchema.safeParse(data);if(!p.success)return jsonError("Please check the corrective action.",422);const row=await prisma.premisesCorrectiveAction.create({data:{...actionData(p.data,user.id),createdById:user.id}});await audit("PREMISES_ACTION_CREATED",{actorType:"USER",actorId:user.id,entityType:"PremisesCorrectiveAction",entityId:row.id,afterValue:row,...requestContext(req)});return NextResponse.json(row,{status:201})}
  if(type==="document"){const p=premisesDocumentSchema.safeParse(data);if(!p.success)return jsonError("Please check the document details.",422);const row=await prisma.premisesDocument.create({data:{...documentData(p.data,user.id),createdById:user.id}});await audit("PREMISES_DOCUMENT_CREATED",{actorType:"USER",actorId:user.id,entityType:"PremisesDocument",entityId:row.id,afterValue:row,...requestContext(req)});return NextResponse.json(row,{status:201})}
  return jsonError("Unsupported premises record type.",422);
})}

export async function PATCH(req:NextRequest){return withRole(req,"DIRECTOR",async user=>{const body=await req.json().catch(()=>null),id=String(body?.id||""),type=body?.type;if(!id)return jsonError("Record id is required.",422);
  if(body?.data){
    if(type==="asset"){const p=assetSchema.safeParse(body.data);if(!p.success)return jsonError("Please check the asset details.",422);const before=await prisma.premisesAsset.findUnique({where:{id}});if(!before)return jsonError("Asset not found.",404);const row=await prisma.premisesAsset.update({where:{id},data:assetData(p.data,user.id)});await audit("PREMISES_ASSET_UPDATED",{actorType:"USER",actorId:user.id,entityType:"PremisesAsset",entityId:id,beforeValue:before,afterValue:row,...requestContext(req)});return NextResponse.json(row)}
    if(type==="inspection"){const p=inspectionSchema.safeParse(body.data);if(!p.success)return jsonError("Please check the inspection details.",422);return NextResponse.json(await recordPremisesInspection(user,p.data,id))}
    if(type==="action"){if(body.data?.status==="COMPLETED")return jsonError("Complete this action in Tasks so evidence and verification are recorded.",409);const p=actionSchema.safeParse(body.data);if(!p.success)return jsonError("Please check the corrective action.",422);const before=await prisma.premisesCorrectiveAction.findUnique({where:{id}});if(!before)return jsonError("Action not found.",404);if(before.status==="ARCHIVED")return jsonError("Restore this task from Tasks before editing it.",409);const row=await prisma.premisesCorrectiveAction.update({where:{id},data:actionData(p.data,user.id)});await audit("PREMISES_ACTION_UPDATED",{actorType:"USER",actorId:user.id,entityType:"PremisesCorrectiveAction",entityId:id,beforeValue:before,afterValue:row,...requestContext(req)});return NextResponse.json(row)}
    if(type==="document"){const p=premisesDocumentSchema.safeParse(body.data);if(!p.success)return jsonError("Please check the document details.",422);const before=await prisma.premisesDocument.findUnique({where:{id}});if(!before)return jsonError("Document not found.",404);const row=await prisma.premisesDocument.update({where:{id},data:documentData({...p.data,documentUrl:p.data.documentUrl||before.documentUrl},user.id)});await audit("PREMISES_DOCUMENT_UPDATED",{actorType:"USER",actorId:user.id,entityType:"PremisesDocument",entityId:id,beforeValue:before,afterValue:row,...requestContext(req)});return NextResponse.json(row)}
  }
  if(type==="action"){const before=await prisma.premisesCorrectiveAction.findUnique({where:{id}});if(!before)return jsonError("Action not found.",404);if(before.status==="ARCHIVED")return jsonError("Restore this task from Tasks before editing it.",409);const status=String(body.status||"");if(status==="COMPLETED")return jsonError("Complete this action in Tasks so evidence and verification are recorded.",409);if(!["OPEN","IN_PROGRESS","COMPLETED"].includes(status))return jsonError("Invalid action status.",422);const row=await prisma.premisesCorrectiveAction.update({where:{id},data:{status,completedAt:status==="COMPLETED"?new Date():null,updatedById:user.id}});await audit("PREMISES_ACTION_STATUS_CHANGED",{actorType:"USER",actorId:user.id,entityType:"PremisesCorrectiveAction",entityId:id,beforeValue:before,afterValue:row,...requestContext(req)});return NextResponse.json(row)}
  if(type==="asset"){const row=await prisma.premisesAsset.update({where:{id},data:{active:false,updatedById:user.id}});await audit("PREMISES_ASSET_ARCHIVED",{actorType:"USER",actorId:user.id,entityType:"PremisesAsset",entityId:id,afterValue:row,...requestContext(req)});return NextResponse.json(row)}
  if(type==="document"){const row=await prisma.premisesDocument.update({where:{id},data:{active:false,updatedById:user.id}});await audit("PREMISES_DOCUMENT_ARCHIVED",{actorType:"USER",actorId:user.id,entityType:"PremisesDocument",entityId:id,afterValue:row,...requestContext(req)});return NextResponse.json(row)}
  return jsonError("Unsupported update.",422);
})}