import {randomUUID} from "crypto";
import {NextRequest,NextResponse} from "next/server";
import sharp from "sharp";
import {prisma} from "@/lib/prisma";
import {withCapability,jsonError} from "@/lib/api";
import {CAPABILITIES} from "@/lib/permissions";
import {storeDocument,loadDocument} from "@/lib/documents";
import {audit} from "@/lib/audit";
export async function POST(req:NextRequest,{params}:{params:Promise<{id:string}>}){return withCapability(req,CAPABILITIES.STUDENT_CARE_EDIT,async user=>{const {id}=await params;if(!await prisma.student.findUnique({where:{id}}))return jsonError("Client not found",404);const form=await req.formData(),file=form.get("photo");if(!(file instanceof File)||file.size>8*1024*1024||!file.type.startsWith("image/"))return jsonError("Choose an image smaller than 8 MB.",422);let content:Buffer;try{content=await sharp(Buffer.from(await file.arrayBuffer()),{limitInputPixels:25000000}).rotate().resize(640,640,{fit:"inside",withoutEnlargement:true}).jpeg({quality:85}).toBuffer();}catch{return jsonError("The image could not be read.",422)}const now=new Date();const doc=await storeDocument({documentNumber:`student-photo-${id}-${randomUUID()}`,documentType:"STUDENT_PHOTO",periodStart:now,periodEnd:now,version:1,createdById:user.id,generationSource:"MANAGER",sourceType:"StudentPhoto",sourceId:id,mimeType:"image/jpeg",content});await prisma.student.update({where:{id},data:{profilePhotoUrl:`/api/students/${id}/photo?document=${doc.id}`}});await audit("STUDENT_PHOTO_UPDATED",{actorType:"USER",actorId:user.id,entityType:"Student",entityId:id});return NextResponse.json({ok:true});});}
export async function GET(req:NextRequest,{params}:{params:Promise<{id:string}>}){return withCapability(req,CAPABILITIES.STUDENT_CARE,async()=>{const {id}=await params;const student=await prisma.student.findUnique({where:{id}});const docId=student?.profilePhotoUrl?.split("document=")[1];const doc=docId?await prisma.documentRecord.findFirst({where:{id:docId,sourceType:"StudentPhoto",sourceId:id}}):null;if(!doc)return jsonError("Photo not found",404);return new NextResponse(await loadDocument(doc.storagePath),{headers:{"content-type":"image/jpeg","cache-control":"private, no-store"}});});}
