import {NextRequest} from "next/server";
import {z} from "zod";
import {withCapability,jsonError} from "@/lib/api";
import {staffJson} from "@/lib/staff-area-auth";
import {CAPABILITIES,hasCapability} from "@/lib/permission-catalog";
import {hrBaseline,saveHr} from "@/lib/staff-hr-service";
import {prisma} from "@/lib/prisma";
import {hrPersonal,hrEmployment,hrMedical} from "@/lib/staff-hr";
export async function GET(req:NextRequest){return withCapability(req,CAPABILITIES.STAFF_HR_VIEW,async user=>{const id=req.nextUrl.searchParams.get("staffId")||"";const medical=hasCapability(user.role,CAPABILITIES.STAFF_MEDICAL_VIEW,user.permissionOverrides);const data=await prisma.$transaction(async tx=>{const b=await hrBaseline(tx,id);await tx.auditLog.create({data:{actorType:"USER",actorId:user.id,action:medical?"STAFF_MEDICAL_READ":"STAFF_HR_READ",entityType:"StaffHrRecord",entityId:id}});return {staffId:id,name:b.staff.displayName,personal:b.personal,employment:b.employment,...(medical?{medical:b.medical}:{}),version:b.record?.version||0,history:(await tx.staffHrEvent.findMany({where:{staffId:id},orderBy:{createdAt:"desc"},take:100})).filter(e=>medical||JSON.stringify((e.beforeValue as Record<string,unknown>).medical)===JSON.stringify((e.afterValue as Record<string,unknown>).medical)).map(e=>medical?e:{...e,reason:"HR record updated",beforeValue:{personal:(e.beforeValue as Record<string,unknown>).personal,employment:(e.beforeValue as Record<string,unknown>).employment},afterValue:{personal:(e.afterValue as Record<string,unknown>).personal,employment:(e.afterValue as Record<string,unknown>).employment}})}});return staffJson({...data,staff:await prisma.staffMember.findMany({where:{active:true},select:{id:true,displayName:true}}),canEdit:hasCapability(user.role,CAPABILITIES.STAFF_EMPLOYMENT_EDIT,user.permissionOverrides),canMedicalEdit:medical&&hasCapability(user.role,CAPABILITIES.STAFF_MEDICAL_EDIT,user.permissionOverrides)});})}
export async function POST(req:NextRequest){return withCapability(req,CAPABILITIES.STAFF_HR_VIEW,async user=>{const p=z.object({staffId:z.string().uuid(),version:z.number().int(),personal:hrPersonal.optional(),employment:hrEmployment.optional(),medical:hrMedical.optional(),reason:z.string().trim().min(1).max(6000)}).strict().safeParse(await req.json());if(!p.success)return jsonError(p.error.issues[0].message,422);const v=p.data;if((v.personal||v.employment)&&!hasCapability(user.role,CAPABILITIES.STAFF_EMPLOYMENT_EDIT,user.permissionOverrides))return jsonError("Employment edit permission required.",403);if(v.medical&&(!hasCapability(user.role,CAPABILITIES.STAFF_MEDICAL_VIEW,user.permissionOverrides)||!hasCapability(user.role,CAPABILITIES.STAFF_MEDICAL_EDIT,user.permissionOverrides)))return jsonError("Medical view and edit permission required.",403);try{await prisma.$transaction(async tx=>{await tx.staffMember.update({where:{id:v.staffId},data:{updatedAt:new Date()}});const old=await tx.staffHrRecord.findUnique({where:{staffId:v.staffId}});if((old?.version||0)!==v.version)throw Error("This profile changed. Reload before saving.");await saveHr(tx,v.staffId,v,user.id,v.reason)},{isolationLevel:"Serializable"});return staffJson({ok:true})}catch{return jsonError("Unable to save. Reload the profile and check your entries.",409)}})}
