ALTER TABLE PremisesAsset ADD COLUMN qrToken CHAR(36) NULL, ADD COLUMN reference VARCHAR(80) NULL, ADD COLUMN status VARCHAR(30) NOT NULL DEFAULT 'OPERATIONAL', ADD COLUMN details JSON NULL;
UPDATE PremisesAsset SET qrToken = UUID() WHERE qrToken IS NULL;
ALTER TABLE PremisesAsset MODIFY qrToken CHAR(36) NOT NULL, ADD UNIQUE INDEX PremisesAsset_qrToken_key(qrToken), ADD UNIQUE INDEX PremisesAsset_reference_key(reference);
ALTER TABLE PremisesCorrectiveAction ADD COLUMN assignedUserId CHAR(36) NULL, ADD COLUMN evidenceUrl VARCHAR(500) NULL, ADD COLUMN verificationRequired BOOLEAN NOT NULL DEFAULT false, ADD COLUMN completedById CHAR(36) NULL, ADD COLUMN verifiedById CHAR(36) NULL, ADD COLUMN verifiedAt DATETIME(3) NULL;
ALTER TABLE ComplianceRecordVersion MODIFY status ENUM('DRAFT','UNDER_REVIEW','AWAITING_APPROVAL','APPROVED','PUBLISHED','SUPERSEDED','ARCHIVED','CHANGES_REQUESTED') NOT NULL DEFAULT 'DRAFT';

ALTER TABLE `PremisesInspection` ADD COLUMN `evidence` JSON NULL;
