import {NextRequest,NextResponse} from "next/server";
import sharp from "sharp";
import {prisma} from "@/lib/prisma";
import {withCapability,jsonError} from "@/lib/api";
import {CAPABILITIES} from "@/lib/permissions";
import {careFields} from "@/lib/care-fields";
import {carePdf} from "@/lib/care-pdf";
import {loadDocument} from "@/lib/documents";
import {audit} from "@/lib/audit";
export async function GET(req:NextRequest,{params}:{params:Promise<{id:string}>}){return withCapability(req,CAPABILITIES.STUDENT_CARE,async user=>{const {id}=await params,student=await prisma.student.findUnique({where:{id}});if(!student)return jsonError("Student not found",404);const info=(student.careInformation||{}) as Record<string,string>;let photo;const docId=student.profilePhotoUrl?.split("document=")[1];if(docId){const doc=await prisma.documentRecord.findFirst({where:{id:docId,sourceType:"StudentPhoto",sourceId:id}});if(doc){const data=await loadDocument(doc.storagePath),meta=await sharp(data).metadata();photo={data,width:meta.width!,height:meta.height!}}}const lines=[`Name: ${student.firstName} ${student.lastName}`,`Known as: ${student.displayName}`,`Emergency contact: ${student.emergencyContactName||"Not supplied"}`,`Relationship: ${student.emergencyContactRelationship||"Not supplied"}`,`Telephone: ${student.emergencyContactPhone||"Not supplied"} / ${student.emergencyContactAlternativePhone||""}`,`Last updated: ${info.updatedAt||"Not recorded"}`,"Prepared from supplied information; verify and keep current.","Structured to cover Metropolitan Police Herbert Protocol information.",...careFields.filter(([k])=>!["hazards","controls","method","emergency","review"].includes(k)).flatMap(([k,label])=>["",label,info[k]||"NOT PROVIDED"]),"",`Exported by: ${user.name} on ${new Date().toISOString()}`];await audit("HERBERT_PROTOCOL_DOWNLOADED",{actorType:"USER",actorId:user.id,entityType:"Student",entityId:id});return new NextResponse(carePdf("Herbert Protocol - confidential student profile",lines,photo),{headers:{"content-type":"application/pdf","content-disposition":`attachment; filename="herbert-protocol-${id}.pdf"`,"cache-control":"private, no-store"}});});}
