import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { prisma } from "@/lib/prisma";
import { CAPABILITIES, requireCapability } from "@/lib/permissions";
import { smtpEnvironment } from "@/lib/smtp";
import { loadSmtpEnv, saveSmtpSettings } from "@/lib/smtp-settings";
import { audit } from "@/lib/audit";
import { requestContext } from "@/lib/api";
import { requireRole } from "@/lib/security";

const schema=z.object({host:z.string().trim().min(1).max(191),port:z.number().int().min(1).max(65535),secure:z.boolean(),username:z.string().trim().max(191),password:z.string().max(500).optional(),clearCredentials:z.boolean().optional(),fromName:z.string().trim().min(1).max(120),fromEmail:z.email().max(191)});
export async function GET(req:NextRequest){try{const user=await requireCapability(CAPABILITIES.REPORT_SETTINGS_MANAGE),config=smtpEnvironment(await loadSmtpEnv()),[lastSuccess,lastFailure,lastTest,lastHealth,lastScheduled]=await Promise.all([prisma.mailOperation.findFirst({where:{operationType:"TEST_EMAIL",status:"SUCCESS"},orderBy:{createdAt:"desc"}}),prisma.mailOperation.findFirst({where:{operationType:"TEST_EMAIL",status:"FAILED"},orderBy:{createdAt:"desc"}}),prisma.mailOperation.findFirst({where:{operationType:"TEST_EMAIL"},orderBy:{createdAt:"desc"}}),prisma.mailOperation.findFirst({where:{operationType:"SMTP_HEALTH"},orderBy:{createdAt:"desc"}}),prisma.scheduledJobRun.findFirst({where:{jobType:"DAILY_ATTENDANCE"},orderBy:{startedAt:"desc"}})]);await audit("EMAIL_SETTINGS_VIEWED",{actorType:"USER",actorId:user.id,entityType:"MailConfiguration",...requestContext(req)});return NextResponse.json({...config,lastSuccessfulTestAt:lastSuccess?.createdAt||null,lastFailedTestAt:lastFailure?.createdAt||null,lastTestRecipient:lastTest?.recipient||null,lastSafeSmtpSummary:lastTest?.safeSummary||lastHealth?.safeSummary||null,lastHealth:lastHealth?{checkedAt:lastHealth.createdAt,status:lastHealth.status,category:lastHealth.safeCategory,summary:lastHealth.safeSummary,durationMs:lastHealth.durationMs}:null,lastScheduledResult:lastScheduled?{startedAt:lastScheduled.startedAt,status:lastScheduled.status,summary:lastScheduled.safeSummary,reportId:lastScheduled.reportId}:null})}catch{return NextResponse.json({error:"You do not have permission to view email settings."},{status:403})}}
export async function PUT(req:NextRequest){try{const user=await requireRole("ADMINISTRATOR"),parsed=schema.safeParse(await req.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:parsed.error.issues[0]?.message||"Check the SMTP details."},{status:422});const existing=smtpEnvironment(await loadSmtpEnv()),hasUsername=Boolean(parsed.data.username||existing.usernameConfigured),hasPassword=Boolean(parsed.data.password||existing.passwordConfigured);if(hasUsername!==hasPassword&&!parsed.data.clearCredentials)return NextResponse.json({error:"Username and password must both be configured."},{status:422});const result=await saveSmtpSettings(parsed.data,user.id);await audit("SMTP_CONFIGURATION_UPDATED",{actorType:"USER",actorId:user.id,entityType:"MailConfiguration",afterValue:{host:parsed.data.host,port:parsed.data.port,secure:parsed.data.secure,usernameConfigured:!!parsed.data.username,fromName:parsed.data.fromName,fromEmail:parsed.data.fromEmail,...result},...requestContext(req)});return NextResponse.json({ok:true,summary:"SMTP settings saved securely."})}catch(error){return NextResponse.json({error:error instanceof Error&&error.message==="SETTINGS_ENCRYPTION_KEY_REQUIRED"?"SETTINGS_ENCRYPTION_KEY must be configured on the VPS before saving an SMTP password.":"You do not have permission to update email settings."},{status:error instanceof Error&&error.message==="SETTINGS_ENCRYPTION_KEY_REQUIRED"?503:403})}}
