ALTER TABLE `Student`
  ADD COLUMN `dateOfBirth` DATE NULL,
  ADD COLUMN `addressLine1` VARCHAR(191) NULL,
  ADD COLUMN `addressLine2` VARCHAR(191) NULL,
  ADD COLUMN `town` VARCHAR(120) NULL,
  ADD COLUMN `postcode` VARCHAR(20) NULL,
  ADD COLUMN `phone` VARCHAR(40) NULL,
  ADD COLUMN `email` VARCHAR(191) NULL,
  ADD COLUMN `nhsNumber` VARCHAR(32) NULL,
  ADD COLUMN `hospitalNumber` VARCHAR(64) NULL,
  ADD COLUMN `gpName` VARCHAR(120) NULL,
  ADD COLUMN `gpSurgery` VARCHAR(191) NULL,
  ADD COLUMN `gpPhone` VARCHAR(40) NULL,
  ADD COLUMN `secondaryEmergencyContact` JSON NULL,
  ADD COLUMN `medicalProfile` JSON NULL,
  ADD COLUMN `personCentredProfile` JSON NULL,
  ADD COLUMN `lastInformationReviewAt` DATETIME(3) NULL,
  ADD COLUMN `nextInformationReviewAt` DATETIME(3) NULL;

CREATE TABLE `InformationReviewRequest` (
  `id` CHAR(36) NOT NULL,
  `organisationId` CHAR(36) NOT NULL,
  `studentId` CHAR(36) NOT NULL,
  `tokenHash` CHAR(64) NOT NULL,
  `status` ENUM('DRAFT','SENT','OPENED','IN_PROGRESS','SUBMITTED','UNDER_REVIEW','PARTIALLY_APPROVED','COMPLETED','EXPIRED','REVOKED') NOT NULL DEFAULT 'DRAFT',
  `source` ENUM('ONLINE','PAPER','ASSISTED') NOT NULL DEFAULT 'ONLINE',
  `verifyDateOfBirth` BOOLEAN NOT NULL DEFAULT false,
  `verificationFailures` INTEGER NOT NULL DEFAULT 0,
  `lockedUntil` DATETIME(3) NULL,
  `expiresAt` DATETIME(3) NOT NULL,
  `openedAt` DATETIME(3) NULL,
  `submittedAt` DATETIME(3) NULL,
  `completedAt` DATETIME(3) NULL,
  `revokedAt` DATETIME(3) NULL,
  `lastSavedAt` DATETIME(3) NULL,
  `sentAt` DATETIME(3) NULL,
  `sentTo` VARCHAR(191) NULL,
  `createdById` CHAR(36) NOT NULL,
  `reviewedById` CHAR(36) NULL,
  `baselineSnapshot` JSON NOT NULL,
  `draftAnswers` JSON NULL,
  `nextReviewDate` DATE NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  UNIQUE INDEX `InformationReviewRequest_tokenHash_key` (`tokenHash`),
  INDEX `InformationReviewRequest_organisationId_status_expiresAt_idx` (`organisationId`, `status`, `expiresAt`),
  INDEX `InformationReviewRequest_studentId_createdAt_idx` (`studentId`, `createdAt`),
  PRIMARY KEY (`id`),
  CONSTRAINT `InformationReviewRequest_organisationId_fkey` FOREIGN KEY (`organisationId`) REFERENCES `Organisation` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `InformationReviewRequest_studentId_fkey` FOREIGN KEY (`studentId`) REFERENCES `Student` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `InformationReviewSubmission` (
  `id` CHAR(36) NOT NULL,
  `reviewRequestId` CHAR(36) NOT NULL,
  `version` INTEGER NOT NULL DEFAULT 1,
  `answers` JSON NOT NULL,
  `declarationName` VARCHAR(120) NOT NULL,
  `declarationCapacity` VARCHAR(120) NOT NULL,
  `signatureData` LONGTEXT NULL,
  `declaredAt` DATETIME(3) NOT NULL,
  `submittedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE INDEX `InformationReviewSubmission_reviewRequestId_version_key` (`reviewRequestId`, `version`),
  PRIMARY KEY (`id`),
  CONSTRAINT `InformationReviewSubmission_reviewRequestId_fkey` FOREIGN KEY (`reviewRequestId`) REFERENCES `InformationReviewRequest` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `RecordChangeProposal` (
  `id` CHAR(36) NOT NULL,
  `reviewRequestId` CHAR(36) NOT NULL,
  `category` VARCHAR(80) NOT NULL,
  `fieldKey` VARCHAR(120) NOT NULL,
  `currentValue` JSON NULL,
  `submittedValue` JSON NULL,
  `approvedValue` JSON NULL,
  `critical` BOOLEAN NOT NULL DEFAULT false,
  `status` ENUM('PENDING','APPROVED','REJECTED') NOT NULL DEFAULT 'PENDING',
  `reviewNote` VARCHAR(500) NULL,
  `reviewedById` CHAR(36) NULL,
  `reviewedAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  UNIQUE INDEX `RecordChangeProposal_reviewRequestId_fieldKey_key` (`reviewRequestId`, `fieldKey`),
  INDEX `RecordChangeProposal_reviewRequestId_status_critical_idx` (`reviewRequestId`, `status`, `critical`),
  PRIMARY KEY (`id`),
  CONSTRAINT `RecordChangeProposal_reviewRequestId_fkey` FOREIGN KEY (`reviewRequestId`) REFERENCES `InformationReviewRequest` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `StudentConsentHistory` (
  `id` CHAR(36) NOT NULL,
  `studentId` CHAR(36) NOT NULL,
  `reviewRequestId` CHAR(36) NULL,
  `consentType` VARCHAR(80) NOT NULL,
  `previousValue` JSON NULL,
  `newValue` JSON NOT NULL,
  `providedByName` VARCHAR(120) NOT NULL,
  `providedAt` DATETIME(3) NOT NULL,
  `approvedById` CHAR(36) NULL,
  `approvedAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  INDEX `StudentConsentHistory_studentId_consentType_createdAt_idx` (`studentId`, `consentType`, `createdAt`),
  PRIMARY KEY (`id`),
  CONSTRAINT `StudentConsentHistory_studentId_fkey` FOREIGN KEY (`studentId`) REFERENCES `Student` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `StudentConsentHistory_reviewRequestId_fkey` FOREIGN KEY (`reviewRequestId`) REFERENCES `InformationReviewRequest` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
