import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import type { Prisma } from "@prisma/client";
import { withCapability, jsonError } from "@/lib/api";
import { CAPABILITIES } from "@/lib/permissions";
import { prisma } from "@/lib/prisma";
import { requireOrganisation } from "@/lib/compliance-service";
import { createOperation } from "@/lib/operations-service";
const schema=z.object({title:z.string().min(1).max(191),type:z.string().min(1).max(80),description:z.string().max(10000).optional(),internalNotes:z.string().max(10000).optional(),startAt:z.iso.datetime(),endAt:z.iso.datetime(),timezone:z.string().max(80).default("Europe/London"),location:z.string().max(191).optional(),premisesName:z.string().max(191).optional(),roomName:z.string().max(120).optional(),requiredStaffCount:z.number().int().min(0).max(100).default(0),requiresCompliance:z.boolean().default(false),recurrenceRule:z.object({frequency:z.enum(["DAILY","WEEKLY","MONTHLY"]),interval:z.number().int().min(1).max(52).optional(),count:z.number().int().min(1).max(90).optional(),until:z.iso.datetime().optional()}).optional()}).refine(v=>new Date(v.endAt)>new Date(v.startAt),{message:"End time must be after start time."});
export async function GET(req:NextRequest){return withCapability(req,CAPABILITIES.OPERATIONS_VIEW,async user=>{const organisationId=requireOrganisation(user),start=req.nextUrl.searchParams.get("start"),end=req.nextUrl.searchParams.get("end");const occurrences=await prisma.operationOccurrence.findMany({where:{organisationId,...(start||end?{startAt:{...(start?{gte:new Date(start)}:{}),...(end?{lte:new Date(end)}:{})}}:{})},include:{operation:{select:{title:true,type:true}},assignments:{where:{status:"ASSIGNED"},select:{id:true}},attendees:{select:{id:true}}},orderBy:{startAt:"asc"},take:250});return NextResponse.json({occurrences});});}
export async function POST(req:NextRequest){return withCapability(req,CAPABILITIES.OPERATIONS_CREATE,async user=>{const p=schema.safeParse(await req.json().catch(()=>null));if(!p.success)return jsonError("Please check the operation details.",422);try{return NextResponse.json(await createOperation(user,{...p.data,recurrenceRule:p.data.recurrenceRule as Prisma.InputJsonValue | undefined}),{status:201});}catch(error){return jsonError(error instanceof Error?error.message:"Request failed.",Number((error as {status?:number}).status??500));}});}
