"use client";import{appConfirm}from"@/lib/app-dialog";
import Link from "next/link";
import { useEffect,useState } from "react";
import { Clock3,ClipboardCheck,Siren,ShieldCheck,Wifi,WifiOff,AlertTriangle,RefreshCw,UserRoundCheck } from "lucide-react";
import { Header } from "@/components/header";
import { clearUnprovisionedQueue,getSyncSnapshot,inspectUnprovisionedQueue,syncNow } from "@/lib/local-db";
import { hasDeviceCredential } from "@/lib/kiosk-context";

type Snapshot={queued:number;conflicts:number;lastSync?:string;syncError?:string;rejectionCategory?:string;syncing?:boolean};
export default function Home(){const[now,setNow]=useState(new Date()),[online,setOnline]=useState(true),[provisioned,setProvisioned]=useState(false),[queueOpen,setQueueOpen]=useState(false),[queueItems,setQueueItems]=useState<Array<{id:string;operation:string;createdAt:string}>>([]),[sync,setSync]=useState<Snapshot>({queued:0,conflicts:0});useEffect(()=>{setOnline(navigator.onLine);const tick=setInterval(()=>setNow(new Date()),1000);const refresh=async()=>{setOnline(navigator.onLine);const authorised=hasDeviceCredential(localStorage);setProvisioned(authorised);setSync(await getSyncSnapshot() as Snapshot);if(authorised&&navigator.onLine)await syncNow()};const status=(e:Event)=>setSync((e as CustomEvent).detail);refresh();addEventListener("online",refresh);addEventListener("offline",refresh);addEventListener("focus",refresh);addEventListener("stars-connect-sync",status);return()=>{clearInterval(tick);removeEventListener("online",refresh);removeEventListener("offline",refresh);removeEventListener("focus",refresh);removeEventListener("stars-connect-sync",status)}},[]);
async function inspectDesktopQueue(){const details=await inspectUnprovisionedQueue();setQueueItems(details.items);setQueueOpen(true)}
async function clearDesktopQueue(){const details=await inspectUnprovisionedQueue();if(!details.count||!await appConfirm(`Permanently clear ${details.count} stale queued upload(s) from this unprovisioned browser?`))return;await clearUnprovisionedQueue();setQueueOpen(false);setSync(await getSyncSnapshot() as Snapshot)}
return <main className="shell"><Header/><div className="content"><section className="kiosk-head"><div><p className="muted" style={{margin:"0 0 8px"}}>Attendance and Register Management</p><h1 className="page-title">Good {now.getHours()<12?"morning":now.getHours()<18?"afternoon":"evening"}</h1><p style={{fontSize:20,marginBottom:0}}>{new Intl.DateTimeFormat("en-GB",{timeZone:"Europe/London",weekday:"long",day:"numeric",month:"long",year:"numeric"}).format(now)}</p></div><div className="clock-display"><strong>{now.toLocaleTimeString("en-GB",{timeZone:"Europe/London",hour:"2-digit",minute:"2-digit"})}</strong><span className={`status ${online?"online":"offline"}`}>{online?<Wifi size={16}/>:<WifiOff size={16}/>} {sync.syncing?"Syncing":online?"Online":"Offline"}</span></div></section>{provisioned&&sync.syncError&&<div className="alert alert-warning" style={{marginBottom:18}}><AlertTriangle size={18}/> {sync.syncError}{sync.rejectionCategory&&<small> ({sync.rejectionCategory.replaceAll("_"," ")})</small>} <button className="btn ghost" onClick={()=>syncNow()}><RefreshCw size={16}/>Retry</button></div>}{!provisioned&&<div className="alert alert-warning" style={{marginBottom:18}}><AlertTriangle size={18}/><div><b>This browser is not a kiosk device.</b><p style={{margin:0}}>Device synchronisation is inactive. Manager sign-in remains available and is separate from device provisioning.{sync.queued?` ${sync.queued} stale local upload(s) can be inspected or cleared.`:""}</p>{queueOpen&&<div><p className="muted">This clears only the unprovisioned browser queue; provisioned device queues are protected.</p>{queueItems.map(item=><small key={item.id} style={{display:"block"}}>{item.operation.replaceAll("_"," ")}  |  {new Date(item.createdAt).toLocaleString("en-GB")}</small>)}</div>}</div>{sync.queued>0&&<><button className="btn secondary" onClick={()=>queueOpen?setQueueOpen(false):inspectDesktopQueue()}>{queueOpen?"Hide queue details":"Inspect stale queue"}</button>{queueOpen&&<button className="btn danger" onClick={clearDesktopQueue}>Clear stale queue</button>}</>}<Link className="btn secondary" href="/setup">Provision this device</Link></div>}<div className="grid tiles"><Link className="card tile clock" href="/clock"><Clock3/><span>Clock In / Out</span></Link><Link className="card tile students" href="/register"><ClipboardCheck/><span>Student Register</span></Link><Link className="card tile visitors" href="/visitors"><UserRoundCheck/><span>Visitor Sign In / Out</span></Link><Link className="card tile emergency" href="/emergency"><Siren/><span>Emergency Register</span></Link></div><div className="kiosk-manager-action"><Link className="btn secondary" href="/login"><ShieldCheck size={19}/>Manager Login</Link></div></div></main>}

