"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
import { Clock3,ClipboardCheck,Siren,ShieldCheck,Wifi,WifiOff,Tablet,AlertTriangle,RefreshCw } from "lucide-react";
import { Header } from "@/components/header";
import { getSyncSnapshot,syncNow } from "@/lib/local-db";

type Snapshot={queued:number;conflicts:number;lastSync?:string;syncError?:string;syncing?:boolean};
export default function Home(){const[now,setNow]=useState(new Date()),[online,setOnline]=useState(true),[sync,setSync]=useState<Snapshot>({queued:0,conflicts:0});useEffect(()=>{setOnline(navigator.onLine);const tick=setInterval(()=>setNow(new Date()),1000);const refresh=async()=>{setOnline(navigator.onLine);setSync(await getSyncSnapshot() as Snapshot);if(navigator.onLine)await syncNow()};const status=(e:Event)=>setSync((e as CustomEvent).detail);refresh();addEventListener("online",refresh);addEventListener("offline",refresh);addEventListener("focus",refresh);addEventListener("stars-connect-sync",status);return()=>{clearInterval(tick);removeEventListener("online",refresh);removeEventListener("offline",refresh);removeEventListener("focus",refresh);removeEventListener("stars-connect-sync",status)}},[]);
return <main className="shell"><Header/><div className="content"><section className="kiosk-head"><div><p className="muted" style={{margin:"0 0 8px"}}>Attendance and Register Management</p><h1 className="page-title">Good {now.getHours()<12?"morning":now.getHours()<18?"afternoon":"evening"}</h1><p style={{fontSize:20,marginBottom:0}}>{new Intl.DateTimeFormat("en-GB",{timeZone:"Europe/London",weekday:"long",day:"numeric",month:"long",year:"numeric"}).format(now)}</p></div><div className="clock-display"><strong>{now.toLocaleTimeString("en-GB",{timeZone:"Europe/London",hour:"2-digit",minute:"2-digit"})}</strong><span className={`status ${online?"online":"offline"}`}>{online?<Wifi size={16}/>:<WifiOff size={16}/>} {sync.syncing?"Syncing":online?"Online":"Offline"}</span></div></section>{sync.syncError&&<div className="alert alert-warning" style={{marginBottom:18}}><AlertTriangle size={18}/> {sync.syncError} <button className="btn ghost" onClick={()=>syncNow()}><RefreshCw size={16}/>Retry</button></div>}<div className="grid tiles"><Link className="card tile clock" href="/clock"><Clock3/><span>Clock In / Out</span></Link><Link className="card tile students" href="/register"><ClipboardCheck/><span>Student Register</span></Link><Link className="card tile emergency" href="/emergency"><Siren/><span>Emergency Register</span></Link><Link className="card tile login" href="/login"><ShieldCheck/><span>Manager Login</span></Link></div><div className="card meta-bar"><Tablet size={20}/><b>{typeof window!=="undefined"?localStorage.getItem("pulse-device-name")||"Unprovisioned tablet":"Tablet"}</b><span className="muted">Last synced {sync.lastSync?new Date(sync.lastSync).toLocaleTimeString("en-GB"):"not yet"}</span><span className="muted">{sync.queued} queued upload{sync.queued===1?"":"s"}</span><span className="muted">{sync.conflicts} local conflict{sync.conflicts===1?"":"s"}</span><span className="muted" style={{marginLeft:"auto"}}>STARS Connect v1.0</span></div></div></main>}
