import {withStaff} from "@/lib/staff-area-auth";
import type {User} from "@prisma/client";
import {NextRequest,NextResponse} from "next/server";
import {z} from "zod";
import {createHash} from "crypto";
import {withCapability,jsonError} from "@/lib/api";
import {CAPABILITIES,hasCapability} from "@/lib/permission-catalog";
import {prisma,auditAction,jsonValue,actionRecipients,notifyAction} from "@/lib/action-notifications";
import {medicationInput,medicationEstimate,medicationTaskStates,terminalMedicationStates} from "@/lib/medication";
import {changeMedicationStock,reconcileMedication,refreshMedications} from "@/lib/medication-service";
const reply=(data:unknown)=>NextResponse.json(data,{headers:{"cache-control":"private, no-store"}});
const authorised=(req:NextRequest,handler:(user:User)=>Promise<NextResponse>)=>req.nextUrl.pathname.startsWith("/api/staff-area/")?withStaff(req,i=>handler(i.user),CAPABILITIES.MEDICATION_VIEW):withCapability(req,CAPABILITIES.MEDICATION_VIEW,handler);
export async function GET(req:NextRequest){return authorised(req,async user=>{
 const client=req.nextUrl.searchParams.get("client");const [rows,clients,staff]=await Promise.all([prisma.clientMedication.findMany({where:client?{studentId:client}:{},include:{student:{select:{displayName:true}},events:{orderBy:{createdAt:"desc"}}},orderBy:{name:"asc"}}),prisma.student.findMany({select:{id:true,displayName:true,medicalProfile:true},orderBy:{displayName:"asc"}}),prisma.staffMember.findMany({where:{active:true},select:{id:true,displayName:true}})]);
 const tasks=await prisma.operationalTask.findMany({where:{sourceKey:{startsWith:"medication:"}},include:{events:{orderBy:{createdAt:"asc"}}}});
 await prisma.auditLog.create({data:{action:"MEDICATION_STOCK_VIEWED",actorType:"USER",actorId:user.id,entityType:"ClientMedication",entityId:client||"overview"}});
 return reply({rows:rows.map(m=>({...m,estimate:medicationEstimate(m),task:tasks.find(t=>t.id===m.activeTaskId),taskHistory:tasks.filter(t=>t.sourceKey?.startsWith(`medication:${m.id}:`))})),clients:clients.map(c=>({id:c.id,displayName:c.displayName,hasLegacy:!!c.medicalProfile})),staff,capabilities:Object.values(CAPABILITIES).filter(c=>hasCapability(user.role,c,user.permissionOverrides))});
})}
const stock=z.object({key:z.string().uuid(),id:z.string().uuid(),version:z.number().int(),action:z.enum(["CONFIRM","RECEIVED","ADJUST","CORRECT","MISSED","REFUSED","WITHHELD"]),quantity:z.number().min(0).max(9999999999).optional(),amount:z.number().positive().max(9999999999).optional(),reason:z.string().trim().min(1).max(6000),relatedReference:z.string().max(500).optional(),correctsEventId:z.string().uuid().optional()}).strict();
export async function POST(req:NextRequest){return authorised(req,async user=>{
 const body=await req.json().catch(()=>null);if(!body)return jsonError("Check the medication details.",422);
 const can=(cap:typeof CAPABILITIES[keyof typeof CAPABILITIES])=>hasCapability(user.role,cap,user.permissionOverrides);
 try{
 if(body.action==="refresh"){if(!can(CAPABILITIES.MEDICATION_MANAGE))return jsonError("Reminder management permission required.",403);return reply({checked:await refreshMedications(user.id)})}
 if(body.action==="import"){if(!can(CAPABILITIES.MEDICATION_MANAGE))return jsonError("Medication management permission required.",403);const c=await prisma.student.findUniqueOrThrow({where:{id:String(body.studentId)}});const profile=c.medicalProfile as Record<string,unknown>|null;let count=0;await prisma.$transaction(async tx=>{for(const category of ["currentMedication","emergencyMedication"]){const raw=profile?.[category];const list=Array.isArray(raw)?raw:typeof raw==="string"&&raw.trim()?[{name:raw}]:[];for(let i=0;i<list.length;i++){const entry=list[i] as {name?:string;dosage?:string;frequency?:string};if(!entry.name?.trim())continue;const sourceKey=`legacy:${c.id}:${category}:${i}`;await tx.clientMedication.upsert({where:{sourceKey},update:{},create:{studentId:c.id,sourceKey,name:entry.name.slice(0,191),notes:[entry.name,entry.dosage,entry.frequency,"Imported care information — confirm dose, units and stock before estimating."].filter(Boolean).join("\n"),prn:category==="emergencyMedication"}});count++}}await auditAction(tx,user.id,"MEDICATION_LEGACY_LINKED","Student",c.id,null,{count})});return reply({count})}
 if(body.action==="save"){
 if(!can(CAPABILITIES.MEDICATION_MANAGE))return jsonError("Medication management permission required.",403);
 const p=medicationInput.safeParse(body.medication);if(!p.success)return jsonError(p.error.issues[0].message,422);const v=p.data;if(!String(body.reason||"").trim())return jsonError("Enter a reason for the medication update.",422);
 if(!await prisma.student.findUnique({where:{id:v.studentId}}))return jsonError("Client unavailable.",404);
 if(v.responsibleStaffId&&!await prisma.staffMember.findFirst({where:{id:v.responsibleStaffId,active:true}}))return jsonError("Choose an active responsible staff member.",422);
 const result=await prisma.$transaction(async tx=>{const before=body.id?await tx.clientMedication.findUniqueOrThrow({where:{id:String(body.id)}}):null;if(before&&before.studentId!==v.studentId)throw Error("A medication cannot be moved to another client.");if(before&&!(await tx.clientMedication.updateMany({where:{id:before.id,version:Number(body.version)},data:{version:{increment:1}}})).count)throw Error("This medication changed. Reload before saving.");const estimate=before?medicationEstimate(before):null;const rateChanged=before&&(Number(before.dose)!==v.dose||Number(before.administrations)!==v.administrations||before.prn!==v.prn||Number(before.manualDailyUsage)!==v.manualDailyUsage||JSON.stringify(before.weekdayUsage)!==JSON.stringify(v.weekdayUsage));const rebase=before&&before.unit!==v.unit?{quantity:null,confirmedAt:null,stockAt:null}:rateChanged&&estimate?.estimatedQuantity!==null?{quantity:estimate?.estimatedQuantity,stockAt:new Date()}:{};const data={...v,...rebase,weekdayUsage:v.weekdayUsage===null?Prisma.JsonNull:jsonValue(v.weekdayUsage)};const row=before?await tx.clientMedication.update({where:{id:before.id},data}):await tx.clientMedication.create({data});await tx.medicationStockEvent.create({data:{medicationId:row.id,requestKey:crypto.randomUUID(),action:"DETAILS_UPDATED",previousQuantity:before?.quantity,newQuantity:row.quantity,changeAmount:before?.quantity!=null&&row.quantity!=null?Number(row.quantity)-Number(before.quantity):null,reason:String(body.reason||"").trim()||"Medication details saved",actorId:user.id,details:jsonValue({before,after:row})}});await auditAction(tx,user.id,"MEDICATION_UPDATED","ClientMedication",row.id,{version:before?.version},{version:row.version});await reconcileMedication(tx,row,user.id);return row},{isolationLevel:"Serializable"});return reply(result);
 }
 if(body.action==="task"){
 if(!can(CAPABILITIES.MEDICATION_COMPLETE))return jsonError("Medication action permission required.",403);
 const p=z.object({id:z.string().uuid(),status:z.enum(medicationTaskStates),reason:z.string().trim().min(1).max(6000),requestNotes:z.string().max(6000).default(""),providerNotes:z.string().max(6000).default(""),reference:z.string().max(191).default(""),requestedDate:z.string().date().optional(),expectedDate:z.string().date().optional(),assignedStaffId:z.string().uuid().nullable().optional()}).safeParse(body.task);if(!p.success)return jsonError("Check the task details and reason.",422);const v=p.data;
 if(["MEDICATION_RECEIVED","COMPLETED"].includes(v.status))return jsonError("Use Record medication received to confirm stock and complete this action.",422);
 const row=await prisma.$transaction(async tx=>{const m=await tx.clientMedication.update({where:{id:v.id},data:{version:{increment:1}}});if(!m.activeTaskId)throw Error("No reminder action is open.");const task=await tx.operationalTask.findUniqueOrThrow({where:{id:m.activeTaskId}});if(terminalMedicationStates.has(task.status))throw Error("This reminder cycle is closed. Confirm stock to start a new cycle.");if(v.assignedStaffId&&!await tx.staffMember.findFirst({where:{id:v.assignedStaffId,active:true}}))throw Error("Choose active staff.");const details={...task.details as object,...v,requestedBy:v.status==="PRESCRIPTION_REQUESTED"?user.id:(task.details as Record<string,unknown>)?.requestedBy};const updated=await tx.operationalTask.update({where:{id:task.id},data:{status:v.status,assignedStaffId:v.assignedStaffId,details:jsonValue(details)}});await tx.clientMedication.update({where:{id:m.id},data:{prescription:jsonValue(details),...(v.assignedStaffId!==undefined?{responsibleStaffId:v.assignedStaffId}:{})}});await tx.operationalTaskEvent.create({data:{taskId:task.id,actorId:user.id,action:v.status,details:jsonValue({before:task.details,after:details})}});await auditAction(tx,user.id,"MEDICATION_TASK_UPDATED","OperationalTask",task.id,{status:task.status},{status:updated.status});if(v.assignedStaffId){const staff=await tx.staffMember.findUnique({where:{id:v.assignedStaffId}});const users=(await actionRecipients(tx,CAPABILITIES.MEDICATION_VIEW)).filter(u=>u.id===staff?.userId);await notifyAction(tx,users,`assign:${task.id}:${v.assignedStaffId}:${createHash("sha256").update(v.status).digest("hex").slice(0,8)}`,"PRESCRIPTION_ASSIGNED",task.id,"A prescription action has been assigned to you.",`/dashboard/medications?medication=${m.id}`)}return updated},{isolationLevel:"Serializable"});return reply(row);
 }
 if(body.action==="RECEIVED"&&!can(CAPABILITIES.MEDICATION_COMPLETE))return jsonError("Medication completion permission required.",403);
 if(!can(CAPABILITIES.MEDICATION_ADJUST))return jsonError("Stock adjustment permission required.",403);const p=stock.safeParse(body);if(!p.success)return jsonError(p.error.issues[0].message,422);return reply(await changeMedicationStock(p.data.id,p.data,user.id));
 }catch(error){return jsonError(error instanceof Prisma.PrismaClientKnownRequestError?"Unable to save. Reload and try again.":error instanceof Error?error.message:"Unable to save.",409)}
})}
import {Prisma} from "@prisma/client";
