"use client";
import {useEffect,useRef,useState} from "react";
import {appConfirm} from "@/lib/app-dialog";
import Link from "next/link";
import {ArrowRight,CheckCircle2,Settings,FileText,Search} from "lucide-react";
import {InvoiceArchive} from "./invoice-archive";
import {needsAmendmentReason} from "@/lib/billing-total-rules";
import styles from "./billing-wizard.module.css";
type Period={id:string;label:string;cycle:string;periodStart:string;periodEnd:string};
type Client={id:string;name:string;payer:string;profileId:string|null;quantity:number|null;rate:number|null;total:number|null;error:string|null;existing:{id:string;invoiceNumber:string}|null};
type Result={runId:string;invoices:Array<{id:string;studentName:string;invoiceNumber:string;grossTotal:string;documentId:string}>};
const money=(n:number)=>new Intl.NumberFormat("en-GB",{style:"currency",currency:"GBP"}).format(n);
const periodLabel=(p:Period)=>`${new Date(p.periodStart).toLocaleDateString("en-GB",{day:"numeric",month:"short",year:"numeric",timeZone:"UTC"})} – ${new Date(p.periodEnd).toLocaleDateString("en-GB",{day:"numeric",month:"short",year:"numeric",timeZone:"UTC"})}`;
export function BillingWizard({canCreate,canSettings}:{canCreate:boolean;canSettings:boolean}){
 const [periods,setPeriods]=useState<Period[]>([]),[periodId,setPeriodId]=useState(""),[clients,setClients]=useState<Client[]>([]),[selected,setSelected]=useState<string[]>([]),[amounts,setAmounts]=useState<Record<string,string>>({}),[reasons,setReasons]=useState<Record<string,string>>({}),[token,setToken]=useState(""),[method,setMethod]=useState("agreed"),[step,setStep]=useState(1),[search,setSearch]=useState(""),[showAll,setShowAll]=useState(false),[archive,setArchive]=useState(false),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(""),[confirm,setConfirm]=useState(false),[replace,setReplace]=useState(false),[result,setResult]=useState<Result>(),[zip,setZip]=useState(""),[dirty,setDirty]=useState(false),[refresh,setRefresh]=useState(0);
 const request=useRef<{key:string;signature:string}|undefined>(undefined),submitting=useRef(false),leaving=useRef(false),confirmation=useRef<HTMLDialogElement>(null),heading=useRef<HTMLHeadingElement>(null);
 useEffect(()=>{fetch("/api/billing/periods",{cache:"no-store"}).then(async r=>{if(!r.ok)throw Error("Billing periods could not be loaded.");const rows:Period[]=await r.json();setPeriods(rows);const today=new Date().toLocaleDateString("sv-SE");const ordered=[...rows].sort((a,b)=>a.periodStart.localeCompare(b.periodStart));setPeriodId((ordered.find(p=>p.periodStart.slice(0,10)<=today&&p.periodEnd.slice(0,10)>=today)||ordered.find(p=>p.periodStart.slice(0,10)>today)||ordered.at(-1))?.id||"");if(!rows.length)setLoading(false)}).catch(e=>{setError(e.message);setLoading(false)})},[]);
 useEffect(()=>{if(!periodId)return;const controller=new AbortController();setLoading(true);setError("");setReplace(false);fetch(`/api/billing/prepare?period=${periodId}`,{signal:controller.signal,cache:"no-store"}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);setClients(d.rows);setSelected(d.rows.filter((c:Client)=>!c.error).map((c:Client)=>c.id));setAmounts(Object.fromEntries(d.rows.map((c:Client)=>[c.id,c.total===null?"":c.total.toFixed(2)])));setReasons({});setToken(d.token);setDirty(false)}).catch(e=>{if(e.name!=="AbortError")setError(e.message)}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[periodId,refresh]);
 useEffect(()=>{
  const leave=(e:BeforeUnloadEvent)=>{if(dirty&&!result&&!leaving.current){e.preventDefault();e.returnValue=""}};
  const navigate=(e:MouseEvent)=>{
   if(!dirty||result||leaving.current||e.button!==0||e.ctrlKey||e.metaKey||e.shiftKey||e.altKey)return;
   const anchor=(e.target as HTMLElement).closest("a");
   if(!anchor||anchor.target==="_blank"||anchor.hasAttribute("download")||!anchor.href||anchor.href===window.location.href||anchor.getAttribute("href")?.startsWith("#"))return;
   e.preventDefault();e.stopImmediatePropagation();
   void appConfirm("Leave billing and discard your current selections and total changes?").then(ok=>{if(ok){leaving.current=true;window.location.assign(anchor.href)}});
  };
  window.addEventListener("beforeunload",leave);document.addEventListener("click",navigate,true);
  return()=>{window.removeEventListener("beforeunload",leave);document.removeEventListener("click",navigate,true)};
 },[dirty,result]);
 useEffect(()=>{heading.current?.focus()},[step]);
 useEffect(()=>{if(confirm)confirmation.current?.showModal();else confirmation.current?.close()},[confirm]);
 const period=periods.find(p=>p.id===periodId),chosen=clients.filter(c=>selected.includes(c.id)),shown=clients.filter(c=>`${c.name} ${c.payer}`.toLowerCase().includes(search.toLowerCase())),display=showAll?shown:shown.slice(0,6),total=chosen.reduce((sum,c)=>sum+(Number(amounts[c.id])||0),0);
 const valid=(c:Client)=>amounts[c.id]?.trim()!==""&&Number.isFinite(Number(amounts[c.id]))&&Number(amounts[c.id])>0&&Number(amounts[c.id])<=1000000&&Math.abs(Number(amounts[c.id])*100-Math.round(Number(amounts[c.id])*100))<0.00001;
 const blocker=!periodId?"Choose a billing period.":!chosen.length?"Select at least one client.":chosen.some(c=>c.error)?"Check the billing details for the highlighted clients, or deselect them.":chosen.some(c=>!valid(c))?"Enter a valid total greater than £0 for each selected client.":"";
 const missingReason=chosen.some(c=>valid(c)&&needsAmendmentReason(c.total,Number(amounts[c.id]))&&(reasons[c.id]||"").trim().length<5),existing=chosen.filter(c=>c.existing);
 function toggle(id:string){setSelected(prev=>prev.includes(id)?prev.filter(v=>v!==id):[...prev,id]);setDirty(true)}
 function changeAmount(id:string,value:string){setAmounts(prev=>({...prev,[id]:value}));setDirty(true)}
 function status(c:Client){if(c.error)return c.error;if(!valid(c))return "Enter a total greater than £0 (up to 2 decimal places).";if(c.total===null)return "Manual total — agreement still to be confirmed.";if(Math.abs(Number(amounts[c.id])-c.total)>0.001)return `Changed from ${money(c.total)}.`;if(c.existing)return `Already invoiced: ${c.existing.invoiceNumber}.`;return "Ready"}
 async function create(){if(submitting.current)return;submitting.current=true;setBusy(true);setError("");try{const payload={periodId,token,replaceExisting:replace,entries:chosen.map(c=>({studentId:c.id,total:Number(amounts[c.id]),reason:reasons[c.id]||""}))};const signature=JSON.stringify(payload);if(!request.current||request.current.signature!==signature)request.current={signature,key:crypto.randomUUID()};const r=await fetch("/api/billing/prepare",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...payload,requestKey:request.current.key})});const d=await r.json();if(!r.ok)throw Error(d.error);setResult(d);setDirty(false);setConfirm(false);setStep(3)}catch(e){setError(e instanceof Error?e.message:"Invoices could not be created. Retry safely.");setConfirm(false)}finally{submitting.current=false;setBusy(false)}}
 async function download(){if(!result)return;setBusy(true);setError("");try{const r=await fetch(`/api/billing/runs/${result.runId}/documents`,{method:"POST"});const d=await r.json();if(!r.ok)throw Error(d.error);setZip(`/api/documents/${d.zipDocument.id}/download`)}catch(e){setError(e instanceof Error?e.message:"Download unavailable. Your invoices are saved.")}finally{setBusy(false)}}
 function restart(){setStep(1);setResult(undefined);setZip("");setDirty(false);request.current=undefined;setRefresh(v=>v+1)}
 return <div className={styles.layout}><div><section className={`card ${styles.main}`}><header><h1 ref={heading} tabIndex={-1}>{step===3?"Invoices created":"Create invoices"}</h1><p>Select the clients and period, check the totals, then create the invoices.</p></header><ol className={styles.progress} aria-label="Invoice creation progress">{["Choose","Check totals","Create invoices"].map((label,index)=><li key={label} aria-current={step===index+1?"step":undefined} className={step>=index+1?styles.current:""}><span>{index+1}</span><b>{label}</b></li>)}</ol>
 {error&&<div role="alert" className={styles.warning}>{error}{step!==3&&<button className="btn secondary" disabled={busy} onClick={()=>{setStep(1);setRefresh(v=>v+1)}}>Refresh choices</button>}</div>}
 {step===1&&<><div className={styles.choices}><label>Billing period<select className="field" value={periodId} disabled={busy} onChange={async e=>{const next=e.target.value;if(dirty&&!await appConfirm("Change period and discard the current selections and total changes?"))return;setPeriodId(next);setShowAll(false)}}><option value="">Choose a period</option>{periods.map(p=><option key={p.id} value={p.id}>{periodLabel(p)} · {p.cycle==="LBE"?"LBE":"Monthly"}</option>)}</select></label><fieldset className={styles.methods}><legend className="sr-only">Calculation method</legend>{[["agreed","Use agreed amounts","Recommended — totals filled in automatically"],["manual","Enter totals myself","Type or change each client's total"]].map(([value,title,description])=><label className={method===value?styles.selectedMethod:""} key={value}><input type="radio" name="billing-method" value={value} checked={method===value} onChange={()=>setMethod(value)}/><span><b>{title}</b><small>{description}</small></span></label>)}</fieldset></div>
 <h2>Select clients</h2><label className={styles.search}><Search size={20}/><span className="sr-only">Search clients</span><input placeholder="Search clients" value={search} onChange={e=>setSearch(e.target.value)}/></label>
 {loading?<p role="status">Loading clients and agreed amounts…</p>:<><label className={styles.selectAll}><input type="checkbox" checked={clients.length>0&&selected.length===clients.length} onChange={e=>{setSelected(e.target.checked?clients.map(c=>c.id):[]);setDirty(true)}}/>Select all {clients.length} clients</label><div className={styles.tableHead}><span/><b>Client</b><b>Payer</b><b>Total</b></div>{display.map(c=><div key={c.id} className={`${styles.clientRow} ${selected.includes(c.id)?styles.selectedRow:""}`} onClick={e=>{if(!(e.target as HTMLElement).closest("input,button,a,label"))toggle(c.id)}}><input aria-label={`Select ${c.name}`} type="checkbox" checked={selected.includes(c.id)} onChange={()=>toggle(c.id)}/><b>{c.name}</b><span>{c.payer}</span><div>{method==="manual"||c.total===null?<label><span className="sr-only">Invoice total for {c.name}</span><input className="field" type="number" inputMode="decimal" min="0.01" max="1000000" step="0.01" value={amounts[c.id]??""} placeholder="Enter total" onChange={e=>changeAmount(c.id,e.target.value)}/></label>:<span>{money(Number(amounts[c.id]))}</span>}{c.error&&<small className={styles.amber}>{c.error} {canSettings&&<Link href={`/dashboard/billing/profiles?studentId=${c.id}`}>Fix details</Link>}</small>}{c.existing&&<small className={styles.amber}>Invoice already exists</small>}</div></div>)}{!shown.length&&<p>No clients match this selection.</p>}<div className={styles.count}>{selected.length} clients selected {shown.length>6&&<button className="btn ghost" onClick={()=>setShowAll(!showAll)}>{showAll?"Show fewer":`Show all ${shown.length}`}</button>}</div></>}
 {!periods.length&&!loading&&<p>Add billing periods in <Link href="/dashboard/billing/settings">Billing settings</Link> to get started.</p>}
 </>}
 {step===2&&<><h2>{period&&periodLabel(period)}</h2>{period&&period.periodEnd.slice(0,10)<new Date().toLocaleDateString("sv-SE")&&<p className={styles.amber}>You are preparing invoices for a previous period.</p>}<div className={styles.reviewList}>{chosen.map(c=><article key={c.id} className={styles.reviewRow}><div><h3>{c.name}</h3><p>{c.payer}</p>{c.quantity!==null&&<small>{c.quantity} × {money(c.rate||0)} before VAT</small>}</div><div><label>Invoice total (£)<input aria-label={`Invoice total for ${c.name}`} className="field" type="number" min="0.01" max="1000000" step="0.01" inputMode="decimal" value={amounts[c.id]??""} onChange={e=>changeAmount(c.id,e.target.value)}/></label><small className={status(c)==="Ready"?styles.ready:styles.amber}>{status(c)==="Ready"&&<CheckCircle2 size={14}/>} {status(c)}</small>{valid(c)&&needsAmendmentReason(c.total,Number(amounts[c.id]))&&<label>Reason for this total<input className="field" value={reasons[c.id]||""} minLength={5} maxLength={2000} placeholder="Brief reason (at least 5 characters)" onChange={e=>{setReasons({...reasons,[c.id]:e.target.value});setDirty(true)}}/></label>}</div></article>)}</div>{existing.length>0&&<label className={styles.warning}><input type="checkbox" checked={replace} onChange={e=>setReplace(e.target.checked)}/> Replace the existing invoices for {existing.map(c=>c.name).join(", ")}. Previous versions will stay in the history.</label>}</>}
 {step<3&&<footer className={styles.summary}><div><b>{selected.length} clients selected</b><span>Total<strong aria-live="polite">{money(total)}</strong></span></div><div className={styles.actions}><button className="btn ghost" disabled={busy} onClick={async()=>{if(step===2)setStep(1);else if(!dirty||await appConfirm("Clear these selections and total changes?"))restart()}}>{step===2?"Back":"Cancel"}</button><button className="btn primary" disabled={busy||loading||!!blocker||(step===2&&(missingReason||(!replace&&existing.length>0)||!canCreate))} onClick={()=>step===1?setStep(2):setConfirm(true)}>{step===1?"Check totals":`Create ${chosen.length} invoices`} <ArrowRight size={20}/></button></div>{(blocker||step===2&&(missingReason?"Add a reason for each highlighted change.":existing.length&&!replace?"Confirm that the existing invoices should be replaced.":!canCreate?"An authorised manager must create these invoices.":""))&&<p className={styles.amber}>{blocker||(missingReason?"Add a reason for each highlighted change.":!canCreate?"An authorised manager must create these invoices.":"Confirm replacement of the existing invoices.")}</p>}</footer>}
 {step===3&&result&&<div className={styles.success}><CheckCircle2 size={42}/><h2>{result.invoices.length} invoices created</h2><p>{period&&periodLabel(period)}</p><strong>{money(result.invoices.reduce((sum,i)=>sum+Number(i.grossTotal),0))}</strong><p>All selected clients were invoiced.</p>{zip?<a className="btn primary" href={zip}>Download invoices</a>:<button className="btn primary" disabled={busy} onClick={()=>void download()}>{busy?"Preparing download…":"Download invoices"}</button>}<details><summary>View created invoices</summary>{result.invoices.map(i=><p key={i.id}>{i.studentName} · {i.invoiceNumber} <a href={`/api/documents/${i.documentId}/view`} target="_blank" rel="noreferrer">View</a> · <a href={`/api/documents/${i.documentId}/download`}>Download</a></p>)}</details><button className="btn secondary" onClick={restart}>Start another billing period</button></div>}
 </section>{step===1&&<section className={`card ${styles.archive}`}><button aria-expanded={archive} className={styles.archiveButton} onClick={()=>setArchive(!archive)}><FileText size={22}/>Previous invoices <span>{archive?"−":"⌄"}</span></button>{archive&&<InvoiceArchive/>}</section>}</div><aside className={`card ${styles.help}`}><h2>It’s as simple as…</h2><ol><li>Select the period and clients</li><li>Check or enter the totals</li><li>Create the invoices</li></ol>{canSettings&&<Link className="btn secondary" href="/dashboard/billing/settings"><Settings size={20}/>Billing settings</Link>}</aside><dialog ref={confirmation} className={`modal ${styles.confirm}`} onCancel={()=>setConfirm(false)} aria-labelledby="confirm-invoices"><h2 id="confirm-invoices">Create {chosen.length} invoices totalling {money(total)}?</h2><p>{period&&periodLabel(period)}</p><div className="toolbar"><button className="btn secondary" disabled={busy} onClick={()=>setConfirm(false)}>Go back</button><button className="btn primary" disabled={busy} onClick={()=>void create()}>{busy?"Creating invoices…":"Create invoices"}</button></div></dialog></div>;
}
