"use client";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { addMonths, endOfMonth, format, getDay, parseISO, startOfMonth } from "date-fns";
import { CalendarDays, ChevronLeft, ChevronRight, GraduationCap, Plus, ReceiptText, Users } from "lucide-react";

type Person = { id: string; name: string };
type Day = { date: string; expectedStudents: Person[]; expectedStaff: Array<Person & { start: string; end: string; status: string; role?: string }>; activities: Array<{ id: string; title: string; type: string; description?: string; start: string; end: string; location?: string; status: string; readiness: string; staff: string[]; students: string[] }>; training: Array<{ id: string; staff: string; course: string; expiryDate: string; mandatory: boolean }>; billingCycles: Array<{ id: string; label: string; start: string; end: string; status: string; studentCount: number }> };
type Payload = { pilot: boolean; days: Day[]; trainingFlags: Array<{ id: string; staff: string; course: string; expiryDate: string; mandatory: boolean; state: "OVERDUE" | "DUE_SOON" }> };
type ActivityType = "ACTIVITY" | "EVENT" | "OUTING" | "APPOINTMENT" | "MEETING";
const today = () => format(new Date(), "yyyy-MM-dd");
const newActivity = (date = today()) => ({ title: "", type: "ACTIVITY" as ActivityType, date, startTime: "09:00", endTime: "10:00", location: "", description: "" });
const displayDate = (value: string) => format(parseISO(value), "EEEE d MMMM yyyy");
const displayTime = (value: string) => format(new Date(value), "HH:mm");
const weekdays = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"];

export function CalendarPilot() {
  const [month, setMonth] = useState(startOfMonth(new Date()));
  const start = format(startOfMonth(month), "yyyy-MM-dd");
  const end = format(endOfMonth(month), "yyyy-MM-dd");
  const [data, setData] = useState<Payload>();
  const [selectedDay, setSelectedDay] = useState<Day>();
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [editing, setEditing] = useState(false);
  const [form, setForm] = useState(newActivity());
  const [saving, setSaving] = useState(false);
  const blanks = useMemo(() => Array.from({ length: (getDay(startOfMonth(month)) + 6) % 7 }), [month]);
  const load = useCallback(async () => { setLoading(true); setError(""); const response = await fetch(`/api/calendar/pilot?start=${start}&end=${end}`, { cache: "no-store" }); const result = await response.json().catch(() => ({})); if (!response.ok) setError(result.error || "Unable to load the calendar."); else setData(result); setLoading(false); }, [start, end]);
  useEffect(() => { load(); }, [load]);
  function openAdd(date = selectedDay?.date || today()) { setSelectedDay(undefined); setForm(newActivity(date)); setEditing(true); }
  async function save(event: React.FormEvent) { event.preventDefault(); setSaving(true); setError(""); const response = await fetch("/api/calendar/pilot", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(form) }); const result = await response.json().catch(() => ({})); if (!response.ok) setError(result.error || "Unable to save the activity."); else { setEditing(false); setForm(newActivity()); await load(); } setSaving(false); }
  return <>
    <div className="calendar-pilot-note"><b>Pilot safety:</b> calendar planning does not mark attendance, change payroll or create an invoice.</div>
    <div className="calendar-toolbar"><div className="table-actions"><button className="btn secondary" onClick={() => setMonth(addMonths(month, -1))} aria-label="Previous month"><ChevronLeft size={18}/></button><button className="btn secondary" onClick={() => setMonth(startOfMonth(new Date()))}>Today</button><button className="btn secondary" onClick={() => setMonth(addMonths(month, 1))} aria-label="Next month"><ChevronRight size={18}/></button></div><h2>{format(month, "MMMM yyyy")}</h2><div className="table-actions"><Link className="btn secondary" href="/dashboard/billing">Billing cycles</Link><button className="btn primary" onClick={() => openAdd()}><Plus size={18}/>Add activity</button></div></div>
    <div className="calendar-key" aria-label="Calendar key"><b>Key</b><span><i className="key-staff"/>Staff expected</span><span><i className="key-student"/>Students expected</span><span><i className="key-activity"/>Activity or event</span><span><i className="key-training"/>Training renewal</span><span><i className="key-billing"/>Billing cycle</span></div>
    {!!data?.trainingFlags.length && <section className="card calendar-training-flags"><h3><GraduationCap size={20}/> Training flags</h3><div className="calendar-flag-list">{data.trainingFlags.map(flag => <div key={flag.id} className={`calendar-flag ${flag.state === "OVERDUE" ? "overdue" : "due"}`}><b>{flag.course}</b><span>{flag.staff}</span><small>{flag.state === "OVERDUE" ? "Overdue" : "Due soon"}: {displayDate(flag.expiryDate.slice(0, 10))}</small></div>)}</div></section>}
    {error && <div className="alert alert-error">{error}</div>}
    {loading ? <div className="empty"><span className="spinner"/> Loading calendar...</div> : <div className="month-calendar"><div className="month-weekdays">{weekdays.map(day => <b key={day}>{day}</b>)}</div><div className="month-grid">{blanks.map((_, index) => <span className="month-blank" key={`blank-${index}`}/>)}{data?.days.map(day => { const total = day.expectedStaff.length + day.expectedStudents.length + day.activities.length + day.training.length + day.billingCycles.length; return <button key={day.date} className={`month-day ${day.date === today() ? "today" : ""}`} onClick={() => setSelectedDay(day)} aria-label={`Open ${displayDate(day.date)}`}><strong>{format(parseISO(day.date), "d")}</strong><div className="month-dots">{day.expectedStaff.length > 0 && <i className="key-staff"/>}{day.expectedStudents.length > 0 && <i className="key-student"/>}{day.activities.length > 0 && <i className="key-activity"/>}{day.training.length > 0 && <i className="key-training"/>}{day.billingCycles.length > 0 && <i className="key-billing"/>}</div><small>{total ? `${total} item${total === 1 ? "" : "s"}` : "No items"}</small></button>; })}</div></div>}
    {selectedDay && <div className="modal-backdrop" role="dialog" aria-modal="true" onMouseDown={() => setSelectedDay(undefined)}><div className="modal calendar-day-modal" onMouseDown={event => event.stopPropagation()}><div className="modal-title-row"><div><h2>{displayDate(selectedDay.date)}</h2><p className="muted">Daily planning information</p></div><button className="btn primary" onClick={() => openAdd(selectedDay.date)}><Plus size={17}/>Add activity</button></div><div className="calendar-modal-grid"><section><h3><Users size={18}/> Expected staff ({selectedDay.expectedStaff.length})</h3>{selectedDay.expectedStaff.length ? <ul>{selectedDay.expectedStaff.map(item => <li key={`${item.id}-${item.start}`}><b>{item.name}</b><span>{displayTime(item.start)} to {displayTime(item.end)}{item.role ? ` - ${item.role}` : ""}</span></li>)}</ul> : <p className="muted">No staff schedule recorded.</p>}<h3>Students expected ({selectedDay.expectedStudents.length})</h3>{selectedDay.expectedStudents.length ? <ul className="calendar-name-grid">{selectedDay.expectedStudents.map(item => <li key={item.id}>{item.name}</li>)}</ul> : <p className="muted">No students expected.</p>}</section><section><h3><CalendarDays size={18}/> Activities and events</h3>{selectedDay.activities.length ? selectedDay.activities.map(item => <article className="calendar-item" key={item.id}><b>{item.title}</b><span>{item.type.replaceAll("_", " ")} - {displayTime(item.start)} to {displayTime(item.end)}</span>{item.location && <small>{item.location}</small>}{item.staff.length > 0 && <small>Staff: {item.staff.join(", ")}</small>}{item.students.length > 0 && <small>Students: {item.students.join(", ")}</small>}</article>) : <p className="muted">No activities added.</p>}{selectedDay.training.map(item => <article className="calendar-item warning" key={item.id}><GraduationCap size={16}/><b>{item.course}</b><span>{item.staff} renewal due</span></article>)}{selectedDay.billingCycles.map(item => <article className="calendar-item billing" key={item.id}><ReceiptText size={16}/><b>{item.label}</b><span>{item.studentCount} selected students - {item.status}</span><small>Ends {displayDate(item.end.slice(0, 10))}</small></article>)}</section></div><div className="modal-actions"><button className="btn secondary" onClick={() => setSelectedDay(undefined)}>Close</button></div></div></div>}
    {editing && <div className="modal-backdrop" role="dialog" aria-modal="true"><form className="modal" onSubmit={save}><h2>Add calendar activity</h2><p className="muted">This creates a planning event only.</p><div className="form-grid"><label className="form-label full">Title<input className="field" required maxLength={191} value={form.title} onChange={event => setForm({ ...form, title: event.target.value })}/></label><label className="form-label">Type<select className="field" value={form.type} onChange={event => setForm({ ...form, type: event.target.value as ActivityType })}><option value="ACTIVITY">Activity</option><option value="EVENT">Event</option><option value="OUTING">Outing</option><option value="APPOINTMENT">Appointment</option><option value="MEETING">Meeting</option></select></label><label className="form-label">Date<input className="field" type="date" required value={form.date} onChange={event => setForm({ ...form, date: event.target.value })}/></label><label className="form-label">Start time<input className="field" type="time" required value={form.startTime} onChange={event => setForm({ ...form, startTime: event.target.value })}/></label><label className="form-label">End time<input className="field" type="time" required value={form.endTime} onChange={event => setForm({ ...form, endTime: event.target.value })}/></label><label className="form-label full">Location<input className="field" maxLength={191} value={form.location} onChange={event => setForm({ ...form, location: event.target.value })}/></label><label className="form-label full">Description<textarea className="field" maxLength={2000} value={form.description} onChange={event => setForm({ ...form, description: event.target.value })}/></label></div><div className="modal-actions"><button type="button" className="btn secondary" onClick={() => setEditing(false)}>Cancel</button><button className="btn primary" disabled={saving}>{saving ? "Saving..." : "Add activity"}</button></div></form></div>}
  </>;
}
