"use client";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { addDays, format, parseISO } from "date-fns";
import { CalendarDays, ChevronLeft, ChevronRight, GraduationCap, Plus, ReceiptText, Users } from "lucide-react";

type Person = { id: string; name: string };
type Day = { date: string; expectedStudents: Person[]; expectedStaff: Array<Person & { start: string; end: string; status: string; role?: string }>; activities: Array<{ id: string; title: string; type: string; description?: string; start: string; end: string; location?: string; status: string; readiness: string; staff: string[]; students: string[] }>; training: Array<{ id: string; staff: string; course: string; expiryDate: string; mandatory: boolean }>; billingCycles: Array<{ id: string; label: string; start: string; end: string; status: string; studentCount: number }> };
type Payload = { pilot: boolean; days: Day[]; trainingFlags: Array<{ id: string; staff: string; course: string; expiryDate: string; mandatory: boolean; state: "OVERDUE" | "DUE_SOON" }> };
const today = () => format(new Date(), "yyyy-MM-dd");
const blank = { title: "", type: "ACTIVITY", date: today(), startTime: "09:00", endTime: "10:00", location: "", description: "" };
const displayDate = (value: string) => format(parseISO(value), "EEEE d MMMM yyyy");
const displayTime = (value: string) => format(new Date(value), "HH:mm");

export function CalendarPilot() {
  const [start, setStart] = useState(today());
  const end = useMemo(() => format(addDays(parseISO(start), 13), "yyyy-MM-dd"), [start]);
  const [data, setData] = useState<Payload>();
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [editing, setEditing] = useState(false);
  const [form, setForm] = useState(blank);
  const [saving, setSaving] = useState(false);
  const load = useCallback(async () => { setLoading(true); setError(""); const response = await fetch(`/api/calendar/pilot?start=${start}&end=${end}`, { cache: "no-store" }); const result = await response.json().catch(() => ({})); if (!response.ok) setError(result.error || "Unable to load the calendar."); else setData(result); setLoading(false); }, [start, end]);
  useEffect(() => { load(); }, [load]);
  function move(days: number) { setStart(format(addDays(parseISO(start), days), "yyyy-MM-dd")); }
  async function save(event: React.FormEvent) { event.preventDefault(); setSaving(true); setError(""); const response = await fetch("/api/calendar/pilot", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(form) }); const result = await response.json().catch(() => ({})); if (!response.ok) setError(result.error || "Unable to save the activity."); else { setEditing(false); setForm(blank); await load(); } setSaving(false); }
  return <>
    <div className="calendar-pilot-note"><b>Pilot safety:</b> this page reads existing attendance, training and billing information. Adding an activity does not mark attendance, change payroll or create an invoice.</div>
    <div className="calendar-toolbar"><div className="table-actions"><button className="btn secondary" onClick={() => move(-14)} aria-label="Previous two weeks"><ChevronLeft size={18}/></button><button className="btn secondary" onClick={() => setStart(today())}>Today</button><button className="btn secondary" onClick={() => move(14)} aria-label="Next two weeks"><ChevronRight size={18}/></button></div><b>{displayDate(start)} – {displayDate(end)}</b><div className="table-actions"><Link className="btn secondary" href="/dashboard/billing">Billing cycles</Link><button className="btn primary" onClick={() => { setForm({ ...blank, date: start }); setEditing(true); }}><Plus size={18}/>Add activity</button></div></div>
    {!!data?.trainingFlags.length && <section className="card calendar-training-flags"><h2><GraduationCap size={21}/> Training renewal flags</h2><div className="calendar-flag-list">{data.trainingFlags.map(flag => <div key={flag.id} className={`calendar-flag ${flag.state === "OVERDUE" ? "overdue" : "due"}`}><b>{flag.course}</b><span>{flag.staff}</span><small>{flag.state === "OVERDUE" ? "Overdue" : "Due soon"}: {displayDate(flag.expiryDate.slice(0, 10))}</small></div>)}</div></section>}
    {error && <div className="alert alert-error">{error}</div>}
    {loading ? <div className="empty"><span className="spinner"/> Loading calendar…</div> : <div className="calendar-days">{data?.days.map(day => { const count = day.expectedStudents.length + day.expectedStaff.length + day.activities.length + day.training.length + day.billingCycles.length; return <details className="calendar-day" key={day.date} open={day.date === today()}><summary><span><b>{displayDate(day.date)}</b><small>{count ? `${count} planning item${count === 1 ? "" : "s"}` : "Nothing scheduled"}</small></span><span className="calendar-day-counts"><span><Users size={15}/>{day.expectedStaff.length} staff</span><span>{day.expectedStudents.length} students</span>{day.activities.length > 0 && <span><CalendarDays size={15}/>{day.activities.length}</span>}</span></summary><div className="calendar-day-body">
      <section><h3>Expected in</h3><b>Staff</b>{day.expectedStaff.length ? <ul>{day.expectedStaff.map(item => <li key={`${item.id}-${item.start}`}>{item.name} · {displayTime(item.start)}–{displayTime(item.end)}{item.role ? ` · ${item.role}` : ""}</li>)}</ul> : <p className="muted">No staff schedule recorded.</p>}<b>Students</b>{day.expectedStudents.length ? <ul className="calendar-name-grid">{day.expectedStudents.map(item => <li key={item.id}>{item.name}</li>)}</ul> : <p className="muted">No students expected from their selected days.</p>}</section>
      <section><h3>Activities and events</h3>{day.activities.length ? day.activities.map(item => <article className="calendar-item" key={item.id}><b>{item.title}</b><span>{item.type.replaceAll("_", " ")} · {displayTime(item.start)}–{displayTime(item.end)}</span>{item.location && <small>{item.location}</small>}{item.staff.length > 0 && <small>Staff: {item.staff.join(", ")}</small>}{item.students.length > 0 && <small>Students: {item.students.join(", ")}</small>}</article>) : <p className="muted">No activities added.</p>}{day.training.map(item => <article className="calendar-item warning" key={item.id}><GraduationCap size={16}/><b>{item.course}</b><span>{item.staff} renewal due</span></article>)}{day.billingCycles.map(item => <article className="calendar-item billing" key={item.id}><ReceiptText size={16}/><b>{item.label}</b><span>{item.studentCount} selected students · {item.status}</span><small>Ends {displayDate(item.end.slice(0, 10))}</small></article>)}</section>
    </div></details>; })}</div>}
    {editing && <div className="modal-backdrop" role="dialog" aria-modal="true"><form className="modal" onSubmit={save}><h2>Add calendar activity</h2><p className="muted">This creates a planning event only. Staff and students can be assigned in a later pilot step.</p><div className="form-grid"><label className="form-label full">Title<input className="field" required maxLength={191} value={form.title} onChange={event => setForm({ ...form, title: event.target.value })}/></label><label className="form-label">Type<select className="field" value={form.type} onChange={event => setForm({ ...form, type: event.target.value })}><option value="ACTIVITY">Activity</option><option value="EVENT">Event</option><option value="OUTING">Outing</option><option value="APPOINTMENT">Appointment</option><option value="MEETING">Meeting</option></select></label><label className="form-label">Date<input className="field" type="date" required value={form.date} onChange={event => setForm({ ...form, date: event.target.value })}/></label><label className="form-label">Start time<input className="field" type="time" required value={form.startTime} onChange={event => setForm({ ...form, startTime: event.target.value })}/></label><label className="form-label">End time<input className="field" type="time" required value={form.endTime} onChange={event => setForm({ ...form, endTime: event.target.value })}/></label><label className="form-label full">Location<input className="field" maxLength={191} value={form.location} onChange={event => setForm({ ...form, location: event.target.value })}/></label><label className="form-label full">Description<textarea className="field" maxLength={2000} value={form.description} onChange={event => setForm({ ...form, description: event.target.value })}/></label></div><div className="modal-actions"><button type="button" className="btn secondary" onClick={() => setEditing(false)}>Cancel</button><button className="btn primary" disabled={saving}>{saving ? "Saving…" : "Add activity"}</button></div></form></div>}
  </>;
}
