"use client";
import {useEffect,useState} from "react";
import Image from "next/image";
import QRCode from "qrcode";
import {StaffDialog} from "./staff-dialog";
type Row={id:string;name:string;enabled:boolean};
export function FleetDriverLinks(){const [rows,setRows]=useState<Row[]>([]),[name,setName]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[link,setLink]=useState(""),[qr,setQr]=useState(""),[copied,setCopied]=useState(false);
 async function load(){const r=await fetch("/api/fleet/drivers",{cache:"no-store"});const d=await r.json();if(!r.ok)throw Error(d.error);setRows(d)}
 useEffect(()=>{void load().catch(e=>setMessage(e.message))},[]);
 useEffect(()=>{let cancelled=false;setQr("");setCopied(false);if(link)void QRCode.toDataURL(link,{width:280,margin:2}).then(value=>{if(!cancelled)setQr(value)}).catch(()=>setMessage("Unable to generate the QR code. Use the copyable link."));return()=>{cancelled=true}},[link]);
 async function save(action:string,id?:string){setBusy(true);setMessage("");try{const r=await fetch("/api/fleet/drivers",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,id,...(action==="create"?{name}:{})})});const d=await r.json();if(!r.ok)throw Error(d.error);if(d.url)setLink(d.url);setName("");setMessage(action==="disable"?"Driver link disabled.":"Driver link ready.");await load()}catch(e){setMessage(e instanceof Error?e.message:"Unable to save driver link.")}finally{setBusy(false)}}
 return <section className="card" style={{padding:22,marginTop:20}}><h2>Driver links</h2><p>A simple vehicle-check page for drivers who do not use the Staff Area. Each personal link opens directly, with no PIN or sign-in.</p><form className="toolbar" onSubmit={e=>{e.preventDefault();void save("create")}}><label>Driver name<input className="field" required minLength={2} maxLength={120} value={name} onChange={e=>setName(e.target.value)}/></label><button className="btn primary" disabled={busy}>Create driver link</button></form><p role="status">{message}</p>{rows.map(row=><div className="toolbar" key={row.id} style={{padding:"12px 0",borderBottom:"1px solid #e6deeb"}}><strong>{row.name}</strong><span>{row.enabled?"Active":"Disabled"}</span><button className="btn secondary" disabled={busy} onClick={()=>void save("replace",row.id)}>{row.enabled?"Replace link / QR":"Create new link / QR"}</button>{row.enabled&&<button className="btn danger" disabled={busy} onClick={()=>void save("disable",row.id)}>Disable link</button>}</div>)}{!rows.length&&<p>No driver links created yet.</p>}{link&&<StaffDialog management label="Driver vehicle-check link" onClose={()=>setLink("")}><h2>Driver link and QR code</h2><p>Send this link to the driver or let them scan the QR code. It opens vehicle checks only. Copy it now; replacing it later disables the old link.</p>{qr&&<Image src={qr} alt="Scan to open the driver's vehicle-check page" width={280} height={280} unoptimized/>}<label>Personal link<input className="field" readOnly value={link} onFocus={e=>e.target.select()}/></label><div className="toolbar"><button className="btn primary" onClick={()=>void navigator.clipboard.writeText(link).then(()=>setCopied(true)).catch(()=>setCopied(false))}>{copied?"Copied":"Copy link"}</button>{qr&&<a className="btn secondary" href={qr} download="stars-driver-qr.png">Download QR</a>}<button className="btn secondary" onClick={()=>setLink("")}>Close</button></div></StaffDialog>}</section>
}
