"use client";
import Link from"next/link";import{usePathname,useRouter}from"next/navigation";import{BookOpen,CheckCircle2,ChevronRight,CircleHelp,GraduationCap,RotateCcw,X}from"lucide-react";import{useEffect,useMemo,useState}from"react";import{helpWorkflowById,helpWorkflows,workflowsForPath,type HelpWorkflow}from"@/lib/help-workflows";
const managerRoots=["/dashboard","/timesheets","/live","/reports","/settings"],kioskRoots=["/","/clock","/register","/visitors","/emergency","/setup"],progressKey="stars-connect-training-progress-v1";
function applies(pathname:string){return managerRoots.some(path=>pathname===path||pathname.startsWith(`${path}/`))||kioskRoots.some(path=>pathname===path||(path!=="/"&&pathname.startsWith(`${path}/`)))}
function contextFor(pathname:string){const direct=workflowsForPath(pathname);if(direct.length)return direct;const id=pathname.startsWith("/clock")?"clocking":pathname.startsWith("/register")?"register":pathname.startsWith("/emergency")?"emergency":"";return id?[helpWorkflowById.get(id)].filter(Boolean)as HelpWorkflow[]:[]}
export function HelpTrainingSystem(){const pathname=usePathname(),router=useRouter(),[open,setOpen]=useState(false),[training,setTraining]=useState<HelpWorkflow|null>(null),[step,setStep]=useState(0),[completed,setCompleted]=useState<string[]>([]),[query,setQuery]=useState(""),context=useMemo(()=>contextFor(pathname),[pathname]),isManager=managerRoots.some(path=>pathname===path||pathname.startsWith(`${path}/`)),suggestions=useMemo(()=>{if(!query.trim())return context;const words=query.toLowerCase().split(/\s+/);return helpWorkflows.filter(item=>words.some(word=>`${item.title} ${item.summary} ${item.keywords.join(" ")}`.toLowerCase().includes(word))).slice(0,8)},[context,query]);
useEffect(()=>{try{setCompleted(JSON.parse(localStorage.getItem(progressKey)||"[]"))}catch{setCompleted([])}},[]);
useEffect(()=>{if(!training)return;const target=training.steps[step]?.selector;if(!target)return;const element=document.querySelector<HTMLElement>(target);if(!element)return;element.classList.add("training-highlight");const advance=()=>setStep(value=>Math.min(value+1,training.steps.length-1));element.addEventListener("click",advance,{once:true});return()=>{element.classList.remove("training-highlight");element.removeEventListener("click",advance)}},[training,step,pathname]);
if(!applies(pathname))return null;
function begin(item:HelpWorkflow){setOpen(false);setTraining(item);setStep(0);if(item.route!==pathname)router.push(item.route)}
function finish(){if(!training)return;const next=Array.from(new Set([...completed,training.id]));localStorage.setItem(progressKey,JSON.stringify(next));setCompleted(next);setTraining(null)}
return <><button className="help-launcher no-print" type="button" onClick={()=>setOpen(value=>!value)} aria-expanded={open} aria-controls="stars-help-panel"><CircleHelp size={21}/><span>Help</span></button>{open&&<aside id="stars-help-panel" className="help-panel no-print" aria-label="Page help"><header><div><strong>Help for this page</strong><small>Plain-English guidance and training</small></div><button type="button" onClick={()=>setOpen(false)} aria-label="Close help"><X/></button></header><div className="help-search"><label htmlFor="help-search">Search help</label><input id="help-search" value={query} onChange={event=>setQuery(event.target.value)} placeholder="What would you like to do?"/></div><div className="help-scroll">{!suggestions.length&&<p className="muted">No matching guidance. Try payroll, register or backup.</p>}{suggestions.map(item=><section className="help-topic" key={item.id}><h2>{item.title}</h2><p>{item.purpose}</p><h3>Before you begin</h3><ul>{item.before.map(text=><li key={text}>{text}</li>)}</ul><h3>What to do</h3><ol>{item.steps.map(entry=><li key={entry.title}><b>{entry.title}.</b> {entry.instruction}</li>)}</ol><div className="help-result"><CheckCircle2 size={17}/><span><b>Expected result:</b> {item.outcome}</span></div>{item.warnings[0]&&<p className="help-warning"><b>Take care:</b> {item.warnings[0]}</p>}{isManager&&<button className="btn secondary" type="button" onClick={()=>begin(item)}><GraduationCap size={17}/> Start guided lesson</button>}</section>)}</div>{isManager&&<footer><Link href="/help"><BookOpen size={17}/> Open the full Help Centre</Link></footer>}</aside>}{training&&<aside className="training-coach no-print" aria-live="polite"><header><GraduationCap/><div><strong>{training.title}</strong><small>Step {step+1} of {training.steps.length}</small></div><button type="button" onClick={()=>setTraining(null)} aria-label="Exit training"><X/></button></header><div className="training-progress"><i style={{width:`${((step+1)/training.steps.length)*100}%`}}/></div><div className="training-body"><h2>{training.steps[step].title}</h2><p>{training.steps[step].instruction}</p>{training.steps[step].warning&&<p className="help-warning">{training.steps[step].warning}</p>}</div><footer><button type="button" className="btn secondary" onClick={()=>setStep(0)}><RotateCcw size={16}/> Restart</button>{step<training.steps.length-1?<button type="button" className="btn" onClick={()=>setStep(value=>value+1)}>Next <ChevronRight size={16}/></button>:<button type="button" className="btn" onClick={finish}>Complete lesson</button>}</footer>{completed.includes(training.id)&&<small className="training-complete">Previously completed - practising again is safe.</small>}</aside>}</>}
