"use client";
import {useEffect,useRef,useState} from "react";
import {Plus,Trash2,ArrowLeft,CheckCircle2} from "lucide-react";
import {manualInvoiceSchema,type ManualInvoiceInput} from "@/lib/manual-invoice";
import {calculateInvoiceLines,calculateInvoiceTotals} from "@/lib/invoice-reissue";
import styles from "./manual-invoice-builder.module.css";

type Profile={id:string;updatedAt:string;payerName:string;billingAddress:string;purchaseOrderNumber:string|null;paymentTermsDays:number;vatRate:string};
type Client={id:string;displayName:string;active:boolean;profiles:Profile[]};
const today=()=>new Date().toLocaleDateString("en-CA",{timeZone:"Europe/London"});
const money=(n:number)=>new Intl.NumberFormat("en-GB",{style:"currency",currency:"GBP"}).format(Number.isFinite(n)?n:0);
type InvoiceForm=ManualInvoiceInput & {payerName:string;payerAddress:string;purchaseOrderNumber:string};
const blank=():InvoiceForm=>({requestKey:crypto.randomUUID(),studentId:"",profileId:"",profileVersion:"",invoiceDate:today(),dueDate:today(),periodStart:today(),periodEnd:today(),payerName:"",payerAddress:"",purchaseOrderNumber:"",lines:[{date:"",service:"",quantity:1,unitRate:0,vatRate:0}]});
export function ManualInvoiceBuilder({onBack}:{onBack:()=>void}){
 const [clients,setClients]=useState<Client[]>([]),[loading,setLoading]=useState(true),[form,setForm]=useState<InvoiceForm|null>(null),[search,setSearch]=useState(""),[review,setReview]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[result,setResult]=useState<{id:string;invoiceNumber:string;documentId:string}|null>(null),[dirty,setDirty]=useState(false);
 const sending=useRef(false),title=useRef<HTMLHeadingElement>(null);
 useEffect(()=>{setForm(blank());fetch("/api/billing/manual",{cache:"no-store"}).then(async r=>{if(!r.ok)throw Error("Clients could not be loaded. Refresh to try again.");setClients(await r.json());}).catch(e=>setError(e.message)).finally(()=>setLoading(false));},[]);
 useEffect(()=>{const leave=(e:BeforeUnloadEvent)=>{if(dirty&&!result){e.preventDefault();e.returnValue="";}};window.addEventListener("beforeunload",leave);return()=>window.removeEventListener("beforeunload",leave);},[dirty,result]);
 useEffect(()=>{title.current?.focus();},[review,result]);
 if(!form)return <p role="status">Loading Custom Invoice…</p>;
 const client=clients.find(c=>c.id===form.studentId),totals=calculateInvoiceTotals(calculateInvoiceLines(form.lines));
 const change=(patch:Partial<InvoiceForm>)=>{setForm({...form,...patch});setDirty(true);setError("");};
 const selectProfile=(p:Profile)=>{const due=new Date(`${form.invoiceDate}T12:00:00Z`);due.setUTCDate(due.getUTCDate()+p.paymentTermsDays);return{profileId:p.id,profileVersion:p.updatedAt,payerName:p.payerName,payerAddress:p.billingAddress,purchaseOrderNumber:p.purchaseOrderNumber||"",dueDate:due.toISOString().slice(0,10),lines:form.lines.map(l=>({...l,vatRate:Number(p.vatRate)}))};};
 async function back(){if(dirty&&!result&&!window.confirm("Leave Custom Invoice and discard this invoice?"))return;onBack();}
 async function issue(){if(sending.current||!form)return;sending.current=true;setBusy(true);setError("");try{const r=await fetch("/api/billing/manual",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)}),d=await r.json();if(!r.ok)throw Error(d.error||"The invoice could not be issued.");setResult(d);setDirty(false);}catch(e){setError(e instanceof Error?e.message:"Please try again. Retrying will not duplicate this invoice.");}finally{sending.current=false;setBusy(false);}}
 const field=(label:string,key:"invoiceDate"|"dueDate"|"periodStart"|"periodEnd"|"payerName"|"purchaseOrderNumber",type="text")=><label>{label}<input className="field" type={type} required={key!=="purchaseOrderNumber"} maxLength={key==="purchaseOrderNumber"?100:191} value={form[key]} onChange={e=>change({[key]:e.target.value})}/></label>;
 return <section className={`card ${styles.builder}`}><button type="button" className="btn secondary" disabled={busy} onClick={back}><ArrowLeft size={16}/>Billing options</button><h1 tabIndex={-1} ref={title}>{result?"Invoice created":review?"Review your invoice":"Custom Invoice"}</h1><p className="muted">{result?"Saved to Previous invoices and included in payment tracking.":"Choose a client, add your charges, then review and issue. Your regular billing stays unchanged."}</p>{error&&<div role="alert" className="alert alert-error">{error}</div>}
 {result?<div className={styles.success}><CheckCircle2 size={36}/><h2>{result.invoiceNumber}</h2><p>{client?.displayName} · {money(totals.gross)}</p><div className={styles.actions}><a className="btn primary" href={`/api/documents/${result.documentId}/view`} target="_blank" rel="noreferrer">View invoice</a><a className="btn secondary" href={`/api/documents/${result.documentId}/download`}>Download</a><a className="btn secondary" href={`/dashboard/billing/invoices/${result.id}`}>Invoice details</a><button className="btn secondary" onClick={()=>{setForm(blank());setResult(null);setReview(false);setSearch("");}}>Create another</button></div></div>:review?<><div className={styles.reviewHeader}><div><h2>{client?.displayName}</h2><p>{form.payerName}</p><p style={{whiteSpace:"pre-line"}}>{form.payerAddress}</p>{form.purchaseOrderNumber&&<p>Your Ref: {form.purchaseOrderNumber}</p>}</div><div><p>Invoice date: {form.invoiceDate}</p><p>Payment due: {form.dueDate}</p><p>From {form.periodStart} to {form.periodEnd}</p></div></div><div className={styles.reviewLines}>{calculateInvoiceLines(form.lines).map((l,i)=><article key={i}><div><b className={styles.serviceText}>{l.service}</b><p>{l.date}</p><small>{l.quantity} × {money(l.unitRate)}{l.vatRate>0?` + ${l.vatRate}% VAT`:""}</small></div><b>{money(l.total)}</b></article>)}</div><p className={styles.notice}>This creates a new, additional invoice. It does not replace existing invoices or send an email.</p><div className={styles.total}><span>Net {money(totals.net)} · VAT {money(totals.vat)}</span><strong>Total {money(totals.gross)}</strong></div><div className={styles.actions}><button className="btn secondary" disabled={busy} onClick={()=>setReview(false)}>Back to edit</button><button className="btn primary" disabled={busy} onClick={issue}>{busy?"Issuing…":"Issue invoice"}</button></div></>:<form onSubmit={e=>{e.preventDefault();const filled={...form,lines:form.lines.map(l=>({...l,date:l.date.trim()||`${form.periodStart} to ${form.periodEnd}`}))},parsed=manualInvoiceSchema.safeParse(filled);if(!parsed.success){setError(parsed.error.issues[0]?.message||"Check the invoice details.");return;}setForm({...form,...parsed.data});setReview(true);setError("");}}>
 <div className={styles.fields}><label>Find a client<input className="field" type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search client name"/></label><label>Client<select className="field" required disabled={loading} value={form.studentId} onChange={e=>{const c=clients.find(c=>c.id===e.target.value);change({studentId:e.target.value,...(c?.profiles[0]?selectProfile(c.profiles[0]):{profileId:"",payerName:"",payerAddress:"",purchaseOrderNumber:""})});}}><option value="">{loading?"Loading clients…":"Choose a client"}</option>{clients.filter(c=>c.id===form.studentId||c.displayName.toLowerCase().includes(search.toLowerCase())).map(c=><option key={c.id} value={c.id}>{c.displayName}{c.active?"":" (archived)"}</option>)}</select></label></div>
 {client&&!client.profiles.length&&<p role="status" className={styles.notice}>This client needs payer details first. <a href="/dashboard/billing/profiles" target="_blank" rel="noreferrer">Open Billing setup</a>, then refresh this page.</p>}
 {client&&client.profiles.length>0&&<><div className={styles.fields}>{client.profiles.length>1&&<label>Saved payer<select className="field" value={form.profileId} onChange={e=>{const p=client.profiles.find(p=>p.id===e.target.value);if(p)change(selectProfile(p));}}>{client.profiles.map(p=><option key={p.id} value={p.id}>{p.payerName}</option>)}</select></label>}{field("From","periodStart","date")}{field("To","periodEnd","date")}{field("Invoice date","invoiceDate","date")}{field("Payment due","dueDate","date")}</div><details className={styles.payer}><summary>Payer & reference · {form.payerName}</summary><p className="muted">Saved billing details · managed in Billing setup.</p><p>{form.payerName}</p><p style={{whiteSpace:"pre-line"}}>{form.payerAddress}</p><p>PO / Your Ref: {form.purchaseOrderNumber||"Not supplied"}</p></details><h2>Invoice lines</h2><p className="muted">For a fixed amount, use quantity 1. Add separate lines for respite, trips or other services.</p><div className={styles.lines}>{form.lines.map((l,i)=><article className={styles.line} key={i}><div className={styles.lineTop}><b>Line {i+1}</b><button type="button" className="btn secondary" aria-label={`Remove line ${i+1}`} disabled={form.lines.length===1} onClick={()=>change({lines:form.lines.filter((_,n)=>n!==i)})}><Trash2 size={16}/>Remove</button></div><label className={styles.description}>Description<textarea className="field" rows={3} required minLength={2} maxLength={191} placeholder="e.g. Additional respite day" value={l.service} onChange={e=>change({lines:form.lines.map((v,n)=>n===i?{...v,service:e.target.value}:v)})}/></label><label>Date / period (optional)<input className="field" maxLength={80} placeholder="Uses the From–To dates above" value={l.date} onChange={e=>change({lines:form.lines.map((v,n)=>n===i?{...v,date:e.target.value}:v)})}/></label>{([['Quantity','quantity','0.001',10000],['Rate (£)','unitRate','0.01',1000000],['VAT %','vatRate','0.01',100]] as const).map(([label,key,step,max])=><label key={key}>{label}<input className="field" required type="number" inputMode="decimal" min={key==='quantity'?0.001:0} max={max} step={step} value={Number.isNaN(l[key])?"":l[key]} onChange={e=>change({lines:form.lines.map((v,n)=>n===i?{...v,[key]:e.target.value===""?NaN:Number(e.target.value)}:v)})}/></label>)}<div className={styles.lineTotal}>Line total <b>{money(calculateInvoiceLines([l])[0].total)}</b></div></article>)}</div><button type="button" className="btn secondary" disabled={form.lines.length>=100} onClick={()=>change({lines:[...form.lines,{date:"",service:"",quantity:1,unitRate:0,vatRate:form.lines[0].vatRate}]})}><Plus size={18}/>Add line</button><div className={styles.total} aria-live="polite"><span>Net {money(totals.net)} · VAT {money(totals.vat)}</span><strong>Total {money(totals.gross)}</strong></div><div className={styles.actions}><button className="btn primary">Review invoice</button></div></>}
 </form>}</section>;
}
