"use client";
import {useState,useRef,useEffect} from "react";
import {TriangleAlert} from "lucide-react";
import Link from "next/link";
type Alert={id:string;name:string;time:string};
export function MissingClockOuts({rows,canResolve,onChanged}:{rows:Alert[];canResolve:boolean;onChanged:()=>void}){
 const dialog=useRef<HTMLDialogElement>(null),[busy,setBusy]=useState(""),[error,setError]=useState(""),[selected,setSelected]=useState<Alert>(),[reason,setReason]=useState("");
 useEffect(()=>{const node=dialog.current;return()=>node?.close()},[]);
 async function resolve(row:Alert){if(reason.trim().length<3)return;setBusy(row.id);setError("");try{const r=await fetch("/api/dashboard/clock-alerts",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id:row.id,reason})});if(!r.ok)throw Error((await r.json()).error);setSelected(undefined);setReason("");onChanged()}catch(e){setError(e instanceof Error?e.message:"Unable to close alert.")}finally{setBusy("")}}
 return <><button type="button" className={`card stat ${rows.length?"stat-attention":"stat-healthy"}`} style={{textAlign:"left",cursor:"pointer"}} onClick={()=>dialog.current?.showModal()}><span className="stat-icon"><TriangleAlert size={25} aria-hidden="true"/></span><span className="stat-copy"><span>Missing clock-outs</span><b style={{color:rows.length?"var(--warning)":"var(--success)"}}>{rows.length}</b></span></button><dialog ref={dialog} className="modal" style={{maxWidth:600,width:"calc(100vw - 32px)",maxHeight:"85dvh",overflow:"auto"}} aria-labelledby="clock-alert-title"><h2 id="clock-alert-title">Missing clock-outs</h2><p>Historical clock-ins without a later clock-out. Correct working hours in Timesheets, or close an investigated false alert with a reason.</p>{error&&<p role="alert">{error}</p>}{!rows.length&&<p>No outstanding alerts.</p>}{rows.map(row=><article key={row.id} style={{borderTop:"1px solid var(--border)",padding:"14px 0"}}><b>{row.name}</b><p>Clocked in: {new Date(row.time).toLocaleString("en-GB")}</p>{canResolve&&<button className="btn secondary" disabled={!!busy} onClick={()=>{setSelected(row);setReason("")}}>Close investigated alert</button>}</article>)}{selected&&<form onSubmit={event=>{event.preventDefault();void resolve(selected)}}><label>Reason for closing {selected.name}&apos;s alert<textarea className="field" value={reason} onChange={event=>setReason(event.target.value)} required minLength={3} maxLength={2000}/></label><p>This closes only the dashboard alert. It does not change timesheet hours.</p><button className="btn primary" disabled={!!busy||reason.trim().length<3}>Confirm closure</button><button type="button" className="btn secondary" onClick={()=>setSelected(undefined)}>Cancel</button></form>}<div className="toolbar"><Link className="btn secondary" href="/timesheets">Open Timesheets</Link><button className="btn primary" onClick={()=>dialog.current?.close()}>Close</button></div></dialog></>;
}
