"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import {CheckCircle2,Clock3,FileText,Settings,Filter,MoreVertical} from "lucide-react";
import type {PaymentRow,TrackingSettings} from "@/lib/payments";
import {localDateKey} from "@/lib/dates";
import "./payments.css";
type Row=Omit<PaymentRow,"history">&{history:Array<{id:string;action:string;actorName:string;createdAt:string;amount?:string|null;reason?:string|null;notes?:string|null;reference?:string|null;receivedDate?:string|null}>};
type Data={settings:TrackingSettings|null;rows:Row[];total:number;filteredTotal:string;periods:Array<{id:string;label:string}>;summary:{outstandingCount:number;outstandingTotal:string;paidCount:number;paidTotal:string;ignoredCount:number}};
type Action="PAY"|"IGNORE"|"RESTORE"|"REVERSE"|"DETAILS"|"SETTINGS";
const reasons=["Predates payment tracking","Cancelled outside STARS Connect","Duplicate historic record","Not being tracked under the new process","Other"];
const money=(value:string)=>`£${value.replace(/\B(?=(\d{3})+(?!\d))/g,",")}`;
const date=(value?:string|null)=>value?new Date(value).toLocaleDateString("en-GB",{day:"2-digit",month:"short",year:"numeric",timeZone:"Europe/London"}):"—";
function total(rows:Row[]){const cents=rows.reduce((sum,r)=>sum+BigInt(r.balance.replace(".","")),BigInt(0));return `${cents/BigInt(100)}.${String(cents%BigInt(100)).padStart(2,"0")}`}
const emptyFilters={period:"",from:"",to:"",due:"",payer:"",client:"",receivedFrom:"",receivedTo:"",reason:""};
export function Payments({canRecord,canReverse,canSettings}:{canRecord:boolean;canReverse:boolean;canSettings:boolean}){
 const [data,setData]=useState<Data|null>(null),[tab,setTab]=useState("OUTSTANDING"),[search,setSearch]=useState(""),[filters,setFilters]=useState(emptyFilters),[showFilters,setShowFilters]=useState(false),[page,setPage]=useState(1),[selected,setSelected]=useState<string[]>([]),[loading,setLoading]=useState(true),[message,setMessage]=useState(""),[error,setError]=useState(""),[refresh,setRefresh]=useState(0);
 const [dialog,setDialog]=useState<{action:Action;rows:Row[]}|null>(null),[busy,setBusy]=useState(false),[formError,setFormError]=useState("");
 const [receivedDate,setReceivedDate]=useState(localDateKey()),[amount,setAmount]=useState(""),[reference,setReference]=useState(""),[notes,setNotes]=useState(""),[reason,setReason]=useState(reasons[0]),[startDate,setStartDate]=useState(localDateKey());
 const [impact,setImpact]=useState<{included:number;excluded:number;total:string;preserved:number;token:string}|null>(null);
 const modal=useRef<HTMLDialogElement>(null),opener=useRef<HTMLElement|null>(null),submitLock=useRef(false);
 const load=useCallback(()=>{setRefresh(v=>v+1);setSelected([])},[]);
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError("");const q=new URLSearchParams({...filters,tab,search,page:String(page)});fetch(`/api/payments?${q}`,{signal:controller.signal,cache:"no-store"}).then(async r=>{const result=await r.json();if(!r.ok)throw Error(result.error);setData(result)}).catch(e=>{if(e.name!=="AbortError")setError(e.message)}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[tab,search,filters,page,refresh]);
 useEffect(()=>{if(dialog){modal.current?.showModal()}else if(modal.current?.open){modal.current.close();opener.current?.focus()}},[dialog]);
 function open(action:Action,rows:Row[]=[]){opener.current=document.activeElement as HTMLElement;setFormError("");setReceivedDate(localDateKey());setAmount(rows[0]?.balance||"");setReference("");setNotes("");setReason(action==="REVERSE"?"":reasons[0]);setStartDate(data?.settings?.startDate||localDateKey());setImpact(null);setDialog({action,rows})}
 async function send(url:string,body:unknown){const res=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const result=await res.json();if(!res.ok)throw Error(result.error||"Unable to save. Please try again.");return result}
 async function submit(event:React.FormEvent){event.preventDefault();if(!dialog||submitLock.current)return;submitLock.current=true;setBusy(true);setFormError("");try{
  if(dialog.action==="SETTINGS"){
   const result=await send("/api/payments/settings",{startDate,token:impact?.token});if(!impact){setImpact(result);return}
  }else await send("/api/payments",{action:dialog.action,items:dialog.rows.map(r=>({id:r.id,revision:r.revision})),receivedDate,amount:dialog.action==="PAY"&&dialog.rows.length===1?amount:undefined,reference,notes,reason});
  setMessage(dialog.action==="PAY"?"Payment received and recorded.":dialog.action==="SETTINGS"?"Payment tracking settings saved.":"Payment checklist updated.");setDialog(null);load();window.dispatchEvent(new Event("payments-updated"));
 }catch(e){setFormError(e instanceof Error?e.message:"Unable to save.");if(dialog.action==="SETTINGS")setImpact(null)}finally{setBusy(false);submitLock.current=false}}
 function changeFilter(key:keyof typeof filters,value:string){setFilters(previous=>({...previous,[key]:value}));setPage(1);setSelected([])}
 const rows=data?.rows||[],chosen=rows.filter(r=>selected.includes(r.id));
 const view=(r:Row)=>r.documentId?<a href={`/api/documents/${r.documentId}/view`} target="_blank" rel="noreferrer">View invoice</a>:<span>PDF unavailable</span>;
 return <div className="payments-page">
 <header className="page-head"><div><h1 className="page-title">Payments</h1><p className="muted">Check what is outstanding and record payments when they arrive.</p></div>{canSettings&&<button data-help="payment-settings" className="btn secondary" onClick={()=>open("SETTINGS")}><Settings size={19} aria-hidden="true"/>Payment settings</button>}</header>
 {message&&<p className="alert alert-success" role="status">{message}</p>}{error&&<p className="alert alert-error" role="alert">{error}</p>}
 {data&&!data.settings?<section className="card payment-setup"><h2>Set up payment tracking</h2><p>Choose when STARS started using this payment checklist.</p><p>Historic invoices will stay unclassified until the start date is confirmed.</p>{canSettings?<button className="btn primary" onClick={()=>open("SETTINGS")}>Choose start date</button>:<p>Ask a manager with payment settings access to complete setup.</p>}</section>:null}
 {data?.settings&&<><div className="payment-summary">
 <section className="card"><Clock3 aria-hidden="true"/><div><span>Outstanding</span><strong className="payment-amber">{data.summary.outstandingCount} invoice{data.summary.outstandingCount===1?"":"s"}</strong><b>{money(data.summary.outstandingTotal)}</b></div></section>
 <section className="card"><CheckCircle2 aria-hidden="true"/><div><span>Paid this month</span><strong className="payment-green">{data.summary.paidCount} invoice{data.summary.paidCount===1?"":"s"}</strong><b>{money(data.summary.paidTotal)}</b></div></section>
 <section className="card"><FileText aria-hidden="true"/><div><span>Ignored</span><strong>{data.summary.ignoredCount} invoice{data.summary.ignoredCount===1?"":"s"}</strong><small>Excluded from payment tracking</small></div></section></div>
 <div className="payments-layout"><section className="card payments-list"><div className="payments-toolbar"><div className="payment-tabs" role="tablist" aria-label="Payment status">{["OUTSTANDING","PAID","IGNORED"].map(t=><button key={t} role="tab" aria-selected={tab===t} aria-controls="payment-results" id={`tab-${t}`} data-help={t==="IGNORED"?"payment-ignored":t==="PAID"?"payment-paid":undefined} onClick={()=>{setTab(t);setPage(1);setSelected([]);setFilters(emptyFilters)}}>{t.charAt(0)+t.slice(1).toLowerCase()}</button>)}</div><label className="payment-search"><span className="sr-only">Search client, payer or invoice</span><input className="field" placeholder="Search client, payer or invoice" value={search} onChange={e=>{setSearch(e.target.value);setPage(1);setSelected([])}}/></label><button className="btn secondary" aria-expanded={showFilters} onClick={()=>setShowFilters(!showFilters)}><Filter size={17} aria-hidden="true"/>Filters</button></div>
 {showFilters&&<div className="form-grid payment-filters"><label>Billing period<select className="field" value={filters.period} onChange={e=>changeFilter("period",e.target.value)}><option value="">All periods</option>{data.periods.map(p=><option key={p.id} value={p.id}>{p.label}</option>)}</select></label><label>Invoice date from<input type="date" className="field" value={filters.from} onChange={e=>changeFilter("from",e.target.value)}/></label><label>Invoice date to<input type="date" className="field" value={filters.to} onChange={e=>changeFilter("to",e.target.value)}/></label><label>Due-date state<select className="field" value={filters.due} onChange={e=>changeFilter("due",e.target.value)}><option value="">All</option><option value="due">Due</option><option value="overdue">Overdue</option></select></label>{(["payer","client"] as const).map(key=><label key={key}>{key==="payer"?"Payer":"Client"}<input className="field" value={filters[key]} onChange={e=>changeFilter(key,e.target.value)}/></label>)}{tab==="PAID"&&(["receivedFrom","receivedTo"] as const).map(key=><label key={key}>{key==="receivedFrom"?"Received from":"Received to"}<input type="date" className="field" value={filters[key]} onChange={e=>changeFilter(key,e.target.value)}/></label>)}{tab==="IGNORED"&&<label>Ignore reason<select className="field" value={filters.reason} onChange={e=>changeFilter("reason",e.target.value)}><option value="">All reasons</option>{[...reasons,"Fully credited","Invoice superseded","Invoice void"].map(r=><option key={r}>{r}</option>)}</select></label>}<button className="btn ghost" onClick={()=>{setFilters(emptyFilters);setSearch("");setPage(1);setSelected([])}}>Reset filters</button></div>}
 <div className="payment-banner">Payment tracking started on <b>{date(data.settings.startDate)}</b>. Older invoices can be reviewed under Ignored. {canSettings&&<button onClick={()=>open("SETTINGS")}>Change start date</button>}</div>
 {chosen.length>0&&tab==="OUTSTANDING"&&canRecord&&<div className="payment-bulk" role="region" aria-label="Selected invoices"><b>{chosen.length} selected · {money(total(chosen))}</b><button className="btn primary" onClick={()=>open("PAY",chosen)}>Mark selected as paid</button><button className="btn secondary" onClick={()=>open("IGNORE",chosen)}>Ignore selected</button></div>}
 <div id="payment-results" role="tabpanel" aria-labelledby={`tab-${tab}`} aria-busy={loading}>{loading?<p role="status">Loading payments…</p>:<><table className="payment-table"><caption className="sr-only">{tab.toLowerCase()} invoices</caption><thead><tr>{tab==="OUTSTANDING"&&canRecord&&<th><input type="checkbox" aria-label="Select all invoices on this page" checked={rows.length>0&&selected.length===rows.length} onChange={e=>setSelected(e.target.checked?rows.map(r=>r.id):[])}/></th>}<th>Client</th><th>Invoice</th><th>Payer</th>{tab==="OUTSTANDING"&&<><th>Invoice date</th><th>Due date</th></>}<th>Amount</th>{tab==="PAID"?<><th>Amount received</th><th>Date received</th><th>Recorded by</th><th>Payment reference</th></>:tab==="IGNORED"?<><th>Invoice date</th><th>Ignore reason</th><th>Ignored by</th><th>Ignored date</th></>:<th>Status</th>}<th>Action</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}>
 {tab==="OUTSTANDING"&&canRecord&&<td data-label="Select"><input type="checkbox" aria-label={`Select invoice ${r.invoiceNumber}`} checked={selected.includes(r.id)} onChange={e=>setSelected(e.target.checked?[...selected,r.id]:selected.filter(id=>id!==r.id))}/></td>}
 <td data-label="Client">{r.client}</td><td data-label="Invoice"><a href={`/dashboard/billing/invoices/${r.id}`}>{r.invoiceNumber}</a></td><td data-label="Payer">{r.payer}</td>{tab==="OUTSTANDING"&&<><td data-label="Invoice date">{date(r.invoiceDate)}</td><td data-label="Due date">{date(r.dueDate)}</td></>}<td data-label="Amount"><b>{money(tab==="OUTSTANDING"?r.balance:r.amount)}</b></td>
 {tab==="PAID"?<><td data-label="Amount received">{money(r.receivedAmount||"0.00")}</td><td data-label="Date received">{date(r.receivedDate)}</td><td data-label="Recorded by">{r.actor}</td><td data-label="Payment reference">{r.reference||"—"}</td></>:tab==="IGNORED"?<><td data-label="Invoice date">{date(r.invoiceDate)}</td><td data-label="Ignore reason">{r.reason}</td><td data-label="Ignored by">{r.actor}</td><td data-label="Ignored date">{date(r.actionAt)}</td></>:<td data-label="Status"><span className="payment-badge">Outstanding</span>{r.overdue&&<small className="payment-amber">Overdue</small>}</td>}
 <td data-label="Action"><div className="payment-actions">{tab==="OUTSTANDING"&&canRecord&&<button data-help="payment-mark-paid" className="btn primary" onClick={()=>open("PAY",[r])}>Mark as paid</button>}{tab==="IGNORED"&&canRecord&&r.canRestore&&<button className="btn secondary" onClick={()=>open("RESTORE",[r])}>Restore to Outstanding</button>}<details><summary aria-label={`More actions for ${r.invoiceNumber}`}><MoreVertical size={20} aria-hidden="true"/></summary><div className="payment-menu">{view(r)}<button onClick={()=>open("DETAILS",[r])}>View payment details</button>{tab==="OUTSTANDING"&&canRecord&&<button onClick={()=>open("IGNORE",[r])}>Ignore</button>}{tab==="PAID"&&canReverse&&<button onClick={()=>open("REVERSE",[r])}>Reverse payment</button>}</div></details></div></td></tr>)}</tbody></table>{!rows.length&&<p className="empty">No invoices match this view.</p>}</>}</div>
 <footer className="payments-toolbar"><span>{data.total} invoice{data.total===1?"":"s"} · {money(data.filteredTotal)} {tab==="OUTSTANDING"?"outstanding":"total"}</span><div className="toolbar"><button className="btn secondary" disabled={page<=1||loading} onClick={()=>{setPage(page-1);setSelected([])}}>Previous</button><span>Page {page} of {Math.max(1,Math.ceil(data.total/25))}</span><button className="btn secondary" disabled={page*25>=data.total||loading} onClick={()=>{setPage(page+1);setSelected([])}}>Next</button></div></footer></section>
 <aside className="card payment-help"><h2>How it works</h2><ol><li>Invoices appear here automatically</li><li>Mark them paid when money arrives</li><li>Ignore older invoices you do not want to track</li></ol><small>This checklist records receipt of money. It does not connect to your bank.</small></aside></div></>}
 {!data&&!error&&<p role="status">Loading payments…</p>}
 <dialog ref={modal} className="payment-dialog" aria-labelledby="payment-dialog-title" onCancel={e=>{e.preventDefault();if(!busy)setDialog(null)}}>{dialog&&<form onSubmit={submit}><h2 id="payment-dialog-title">{{PAY:"Mark payment as received",IGNORE:dialog.rows.length>1?"Ignore selected invoices?":"Ignore this invoice?",RESTORE:"Restore to Outstanding?",REVERSE:"Reverse payment?",DETAILS:"Payment details",SETTINGS:data?.settings?"Payment settings":"Set up payment tracking"}[dialog.action]}</h2>
 {dialog.rows.length===1&&<div className="payment-confirm-details"><b>{dialog.rows[0].client} · {dialog.rows[0].invoiceNumber}</b><p>{dialog.rows[0].payer} · Invoice total {money(dialog.rows[0].amount)}</p></div>}{dialog.rows.length>1&&<><p><b>{dialog.rows.length} invoices · {money(total(dialog.rows))}</b></p><ul>{dialog.rows.map(r=><li key={r.id}>{r.invoiceNumber} · {r.client} · {money(r.balance)}</li>)}</ul></>}
 {dialog.action==="SETTINGS"&&<><p>Choose when STARS started using this payment checklist. Individual paid, ignored and restored decisions are preserved.</p><label>Start date<input id="payment-start" className="field" type="date" required max={localDateKey()} value={startDate} onChange={e=>{setStartDate(e.target.value);setImpact(null)}}/></label>{impact&&<div className="payment-banner"><p>{impact.included} invoices will become Outstanding.</p><p>{impact.excluded} invoices will become Ignored.</p><p>Total affected value: {money(impact.total)}</p><p>{impact.preserved} individual decisions preserved.</p><b>Confirm these changes to apply the start date.</b></div>}</>}
 {dialog.action==="PAY"&&<><label>Date received<input id="payment-date" className="field" type="date" required max={localDateKey()} value={receivedDate} onChange={e=>setReceivedDate(e.target.value)}/></label>{dialog.rows.length===1?<label>Amount received (£)<input id="payment-amount" className="field" inputMode="decimal" required pattern="[0-9]+([.][0-9]{1,2})?" value={amount} onChange={e=>setAmount(e.target.value)}/><small>The amount must match the full balance of {money(dialog.rows[0].balance)}.</small></label>:<p>Each invoice will be recorded as paid in full using the same received date.</p>}<label>Payment reference (optional)<input id="payment-reference" className="field" maxLength={191} value={reference} onChange={e=>setReference(e.target.value)}/></label></>}
 {dialog.action==="IGNORE"&&<><p>This removes it from active payment tracking. The invoice and its history will not be deleted.</p><label>Reason<select id="payment-reason" className="field" required value={reason} onChange={e=>setReason(e.target.value)}>{reasons.map(r=><option key={r}>{r}</option>)}</select></label></>}
 {dialog.action==="REVERSE"&&<><p>This returns the invoice to Outstanding unless it has been credited or superseded. Its payment history is retained.</p><label>Reason<input id="payment-reason" className="field" required minLength={3} maxLength={191} value={reason} onChange={e=>setReason(e.target.value)}/></label></>}
 {dialog.action==="RESTORE"&&<p>This invoice will return to Outstanding. Its previous ignore history is retained.</p>}
 {["PAY","IGNORE"].includes(dialog.action)&&<label>{reason==="Other"&&dialog.action==="IGNORE"?"Explanation (required)":"Notes (optional)"}<textarea id="payment-notes" className="field" required={dialog.action==="IGNORE"&&reason==="Other"} maxLength={1000} value={notes} onChange={e=>setNotes(e.target.value)}/></label>}
 {dialog.action==="DETAILS"&&<><p>Status: {dialog.rows[0].state.toLowerCase()} · {dialog.rows[0].state==="IGNORED"?dialog.rows[0].reason:""}</p>{dialog.rows[0].history.length?<ol>{dialog.rows[0].history.map(e=><li key={e.id}><b>{{PAY:"Payment recorded",IGNORE:"Ignored",RESTORE:"Restored",REVERSE:"Payment reversed"}[e.action]||e.action}</b> · {e.actorName} · {new Date(e.createdAt).toLocaleString("en-GB")}<p>{e.amount&&money(e.amount)} {e.receivedDate&&`received ${date(e.receivedDate)}`} {e.reference}</p><p>{e.reason} {e.notes}</p></li>)}</ol>:<p>Automatically classified using the confirmed tracking start date. No individual actions recorded.</p>}</>}
 {formError&&<div className="alert alert-error" role="alert">{formError}<p>{dialog.action==="PAY"?<><a href="#payment-date">Check received date</a> · {dialog.rows.length===1&&<a href="#payment-amount">Check amount</a>}</>:<a href={dialog.action==="SETTINGS"?"#payment-start":"#payment-reason"}>Review details</a>}</p></div>}
 <div className="toolbar"><button type="button" className="btn secondary" disabled={busy} onClick={()=>setDialog(null)}>{dialog.action==="DETAILS"?"Close":"Cancel"}</button>{dialog.action!=="DETAILS"&&<button className="btn primary" disabled={busy}>{busy?"Saving…":dialog.action==="SETTINGS"?(impact?"Confirm start date":"Preview impact"):dialog.action==="PAY"?"Confirm payment received":dialog.action==="IGNORE"?"Confirm ignore":dialog.action==="RESTORE"?"Confirm restore":"Confirm reversal"}</button>}</div></form>}</dialog>
 </div>
}
