/* eslint-disable @next/next/no-img-element */
"use client";
import{useEffect,useState}from"react";
import{Monitor,Save}from"lucide-react";
import{screensaverDefaults,type ScreensaverSettings}from"@/lib/screensaver";import{SeasonalScreensaverArt,type SeasonalScene}from"@/components/seasonal-screensaver-art";
const animationLabels={constellation:"Classic constellation",halloween:"Halloween haunted house",christmas:"Christmas string lights","st-patricks":"St Patrick's leprechaun"} as const;
export function ScreensaverSettingsForm(){const[settings,setSettings]=useState<ScreensaverSettings>(screensaverDefaults),[loading,setLoading]=useState(true),[message,setMessage]=useState("");useEffect(()=>{fetch("/api/settings/screensaver",{cache:"no-store"}).then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.error);setSettings(body)}).catch(error=>setMessage(error.message)).finally(()=>setLoading(false))},[]);
async function save(event:React.FormEvent){event.preventDefault();setMessage("");const response=await fetch("/api/settings/screensaver",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify(settings)}),body=await response.json();setMessage(response.ok?"Screensaver settings saved. Devices will cache them when next online.":body.error||"Unable to save settings.")}
if(loading)return <div className="empty">Loading screensaver settings...</div>;const check=(key:keyof ScreensaverSettings,label:string)=><label className="check-row"><input type="checkbox" checked={Boolean(settings[key])} onChange={event=>setSettings({...settings,[key]:event.target.checked})}/><span>{label}</span></label>;
return <form autoComplete="off" className="grid" onSubmit={save}>{message&&<div className={message.includes("saved")?"alert alert-success":"alert alert-error"}>{message}</div>}<div className="grid" style={{gridTemplateColumns:"repeat(auto-fit,minmax(310px,1fr))"}}>
<section className="card" style={{padding:22}}><h2><Monitor size={20}/>Content and wake-up</h2>{check("screensaverEnabled","Enable idle screensaver")}<label className="form-label">Idle timeout (seconds)<input className="field" type="number" min="15" max="3600" value={settings.idleTimeoutSeconds} onChange={event=>setSettings({...settings,idleTimeoutSeconds:Number(event.target.value)})}/></label><label className="form-label">Fade into kiosk after touch (seconds)<input className="field" type="number" min="0" max="5" step=".25" value={settings.wakeTransitionSeconds} onChange={event=>setSettings({...settings,wakeTransitionSeconds:Number(event.target.value)})}/><small className="muted">The screensaver continues blocking kiosk buttons during this delay.</small></label><label className="form-label">Heading<input className="field" maxLength={120} value={settings.headline} onChange={event=>setSettings({...settings,headline:event.target.value})}/></label><label className="form-label">Touch/wake message<input className="field" maxLength={120} value={settings.screensaverMessage} onChange={event=>setSettings({...settings,screensaverMessage:event.target.value})}/></label><label className="form-label">Device/location name<input className="field" maxLength={120} placeholder="Uses provisioned device name when blank" value={settings.deviceLocationName} onChange={event=>setSettings({...settings,deviceLocationName:event.target.value})}/></label>{check("showClock","Show time")}{check("showDate","Show date")}{check("showDeviceName","Show device/location")}{check("showOnSiteCount","Show number of people currently on site")}</section>
<section className="card" style={{padding:22}}><h2>Logo, colours and live preview</h2>{check("showLogo","Show logo")}<label className="form-label">Logo URL or data image<input className="field" value={settings.logoUrl} onChange={event=>setSettings({...settings,logoUrl:event.target.value})}/></label><label className="form-label">Background colour<input className="field" type="color" value={settings.backgroundColor} onChange={event=>setSettings({...settings,backgroundColor:event.target.value})}/></label><label className="form-label">Text colour<input className="field" type="color" value={settings.textColor} onChange={event=>setSettings({...settings,textColor:event.target.value})}/></label><label className="form-label">Accent colour<input className="field" type="color" value={settings.accentColor} onChange={event=>setSettings({...settings,accentColor:event.target.value})}/></label><div className={`screensaver-preview theme-${settings.backgroundAnimationStyle}`} style={{background:settings.backgroundColor,color:settings.textColor}}>{settings.backgroundAnimationStyle==="constellation"?<div className="preview-animation">{Array.from({length:18},(_,index)=><i key={index}/>)}</div>:<SeasonalScreensaverArt scene={settings.backgroundAnimationStyle as SeasonalScene}/>}<div className="preview-content">{settings.showLogo&&settings.logoUrl&&<img src={settings.logoUrl} alt=""/>}<h3>{settings.headline}</h3><strong>12:34</strong><p>{settings.screensaverMessage}</p></div></div></section>
<section className="card" style={{padding:22}}><h2>Weather</h2>{check("screensaverWeatherEnabled","Show current weather on screensaver")}<label className="form-label">Weather location<input className="field" maxLength={120} placeholder="Enfield, London" value={settings.screensaverWeatherLocation} onChange={event=>setSettings({...settings,screensaverWeatherLocation:event.target.value})}/><small className="muted">Town, city or UK postcode. Tablets do not request location permission.</small></label></section>
<section className="card" style={{padding:22}}><h2>Background animation</h2>{check("constellationEnabled","Enable animated background")}<label className="form-label">Animation style<select className="field" value={settings.backgroundAnimationStyle} onChange={event=>setSettings({...settings,backgroundAnimationStyle:event.target.value as ScreensaverSettings["backgroundAnimationStyle"]})}>{Object.entries(animationLabels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label className="form-label">Animation intensity: {settings.constellationIntensity}%<input type="range" min="0" max="100" value={settings.constellationIntensity} onChange={event=>setSettings({...settings,constellationIntensity:Number(event.target.value)})}/></label><p className="muted">Reduced-motion accessibility settings are always respected.</p></section>
<section className="card" style={{padding:22}}><h2>Day and night dimming</h2><div className="form-grid"><label className="form-label">Day starts<input className="field" type="time" value={settings.dayModeStart} onChange={event=>setSettings({...settings,dayModeStart:event.target.value})}/></label><label className="form-label">Day brightness %<input className="field" type="number" min="5" max="100" value={settings.dayDimLevel} onChange={event=>setSettings({...settings,dayDimLevel:Number(event.target.value)})}/></label><label className="form-label">Evening starts<input className="field" type="time" value={settings.eveningModeStart} onChange={event=>setSettings({...settings,eveningModeStart:event.target.value})}/></label><label className="form-label">Evening brightness %<input className="field" type="number" min="5" max="100" value={settings.eveningDimLevel} onChange={event=>setSettings({...settings,eveningDimLevel:Number(event.target.value)})}/></label><label className="form-label">Night starts<input className="field" type="time" value={settings.nightModeStart} onChange={event=>setSettings({...settings,nightModeStart:event.target.value})}/></label><label className="form-label">Night brightness %<input className="field" type="number" min="5" max="100" value={settings.nightDimLevel} onChange={event=>setSettings({...settings,nightDimLevel:Number(event.target.value)})}/></label></div></section>
</div><button className="btn primary"><Save size={17}/>Save screensaver settings</button></form>}
