"use client";
import {staffAbsenceLabel} from "@/lib/staff-absence-types";
import {useCallback,useEffect,useState} from "react";
import {StaffAbsences} from "./staff-absences";
import type {absenceSummary} from "@/lib/staff-absence-summary";
type Data={summary:ReturnType<typeof absenceSummary>;pending:number;version:number;canEditAllowance:boolean;canManage:boolean;records:Array<{id:string;type:string;startDate:string;endDate:string;approvalStatus:string;bradfordExcluded:boolean}>};
const showDate=(s:string)=>new Date(s).toLocaleDateString("en-GB",{timeZone:"UTC"});
export function StaffAbsenceProfile({staffId}:{staffId:string}){
 const [data,setData]=useState<Data>(),[year,setYear]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[editing,setEditing]=useState(false),[allowance,setAllowance]=useState({entitlementDays:"",carryOverDays:"0",reason:""});
 const load=useCallback(async()=>{try{const r=await fetch(`/api/staff/${staffId}/absences${year?`?year=${year}`:""}`,{cache:"no-store"});const d=await r.json();if(!r.ok)throw Error(d.error||"Absence profile unavailable.");setData(d);setError("")}catch(e){setError((e as Error).message)}},[staffId,year]);
 useEffect(()=>{void load()},[load]);
 if(!data)return <section className="card" style={{padding:20}}><p role="status">{error||"Loading holiday and absence record…"}</p></section>;
 const s=data.summary,b=s.bradford;
 const missing=[...new Set([...s.taken.unknownDates,...s.booked.unknownDates,...b.unknownDates,...s.otherLeave.flatMap(l=>[...l.taken.unknownDates,...l.booked.unknownDates])])];
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);try{const r=await fetch(`/api/staff/${staffId}/absences`,{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({yearStart:s.year.start,version:data!.version,entitlementDays:Number(allowance.entitlementDays),carryOverDays:Number(allowance.carryOverDays),reason:allowance.reason})});const d=await r.json();if(!r.ok)throw Error(d.error||"Allowance could not be saved.");setEditing(false);await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <section className="card" style={{padding:20,marginBlock:16}}><h2>Holiday & absence record</h2>
 <div className="toolbar"><button type="button" className="btn secondary" disabled={busy||editing} onClick={()=>setYear(String(Number(s.year.start.slice(0,4))-1))}>Previous year</button><strong>{showDate(s.year.start)} – {showDate(s.year.end)}</strong><button type="button" className="btn secondary" disabled={busy||editing} onClick={()=>setYear(String(Number(s.year.start.slice(0,4))+1))}>Next year</button></div>
 {error&&<p role="alert" className="alert alert-error">{error}</p>}
 <dl className="form-grid" style={{marginBlock:20}}>{[["Entitlement",s.entitlementDays===null?"Not set":`${s.entitlementDays} days`],["Carry-over",`${s.carryOverDays} days`],["Taken (through today)",`${s.taken.days} days`],["Booked (after today)",`${s.booked.days} days`],["Remaining after bookings",s.remainingDays===null?"Incomplete":`${s.remainingDays} days`],["Pending leave requests",String(data.pending)]].map(([label,value])=><div key={label}><dt className="muted">{label}</dt><dd style={{margin:0,fontSize:"1.2rem",fontWeight:700}}>{value}</dd></div>)}</dl>
 {s.entitlementDays===null&&<p className="alert">Set the agreed allowance for this leave year to calculate the remaining balance.</p>}{s.remainingDays!==null&&s.remainingDays<0&&<p className="alert">Approved holiday exceeds the recorded allowance by {Math.abs(s.remainingDays)} days.</p>}
 {missing.length>0&&<p className="alert">Working patterns are missing for {missing.length} absence dates. Totals show known working days only; affected balances and Bradford scores are incomplete.</p>}
 <p className="muted">Only approved paid holiday is deducted from entitlement. Unpaid holiday and compassionate leave are tracked separately and do not count towards Bradford scores. Non-working days are excluded; partial days use the proportion of scheduled time missed. Enter the agreed allowance including any pro-rata entitlement and applicable bank holidays. Bank holidays are deducted only when recorded as leave.</p>
 {data.canEditAllowance&&!editing&&<button type="button" className="btn secondary" onClick={()=>{setAllowance({entitlementDays:s.entitlementDays?.toString()||"",carryOverDays:String(s.carryOverDays),reason:""});setEditing(true)}}>Edit this year’s allowance</button>}
 {editing&&<form onSubmit={save}><fieldset disabled={busy} style={{border:0,padding:0}}><div className="form-grid"><label className="form-label">Entitlement (days)<input className="field" required type="number" min={0} max={366} step="0.01" value={allowance.entitlementDays} onChange={e=>setAllowance({...allowance,entitlementDays:e.target.value})}/></label><label className="form-label">Carry-over (days)<input className="field" required type="number" min={0} max={366} step="0.01" value={allowance.carryOverDays} onChange={e=>setAllowance({...allowance,carryOverDays:e.target.value})}/></label><label className="form-label full">Reason for change<textarea className="field" required maxLength={2000} value={allowance.reason} onChange={e=>setAllowance({...allowance,reason:e.target.value})}/></label></div><div className="toolbar"><button className="btn primary">Save allowance</button><button type="button" className="btn secondary" onClick={()=>setEditing(false)}>Cancel</button></div></fieldset></form>}
 <h3 style={{marginTop:24}}>Other leave this year</h3>{s.otherLeave.map(l=><p key={l.type}><strong>{staffAbsenceLabel(l.type)}</strong> · {l.taken.days} days taken · {l.booked.days} days booked</p>)}
 <h3 style={{marginTop:24}}>Bradford score · {b.score===null?"Incomplete":b.score}</h3><p>{showDate(b.start)} – {showDate(b.end)} · rolling 52 weeks</p><p>{b.spells} sickness spells × {b.spells} × {b.days} working days lost{b.excludedRecords?` · ${b.excludedRecords} excluded records`:""}</p><p className="muted">Overlapping records and spells separated only by known non-working days count together. Future sickness and excluded records do not count. Use this score as a prompt for an individual review, not an automatic decision.</p>
 <StaffAbsences staffId={staffId} onChanged={()=>void load()}/>
 <details><summary>Complete absence history · {data.records.length} records</summary>{data.records.map(r=><p key={r.id}>{staffAbsenceLabel(r.type)} · {showDate(r.startDate)} – {showDate(r.endDate)} · {r.approvalStatus==="REJECTED"?"Cancelled / rejected":r.approvalStatus.toLowerCase()}{r.bradfordExcluded?" · Bradford excluded":""}</p>)}</details>
 </section>;
}
