"use client";
import {useEffect,useState} from "react";
import Image from "next/image";
import QRCode from "qrcode";
import {StaffDialog} from "./staff-dialog";
export function StaffAccess({id,levelId}:{id:string;levelId?:string;hasAccount:boolean}){
 const [levels,setLevels]=useState<Array<{id:string;name:string;active:boolean}>>([]),[selected,setSelected]=useState(levelId||""),[message,setMessage]=useState(""),[link,setLink]=useState(""),[qr,setQr]=useState(""),[open,setOpen]=useState(false),[busy,setBusy]=useState(false);
 useEffect(()=>{void fetch('/api/access-levels').then(async r=>{if(r.ok)setLevels(await r.json())});void fetch('/api/staff-access',{cache:'no-store'}).then(async r=>{if(r.ok){const d=await r.json();const a=d.staff.find((s:{id:string})=>s.id===id)?.portalAccount;if(a?.loginLink&&a.enabled)setLink(d.entryUrl+'?member='+a.loginLink)}})},[id]);
 useEffect(()=>{if(link)void QRCode.toDataURL(link,{width:320,margin:2}).then(setQr)},[link]);
 if(!levels.length)return null;
 return <section className="card" style={{padding:16}}><h3>Staff app access</h3><p>Choose what this person can access. They sign in with their existing clocking PIN.</p><label>Access level<select className="field" value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Select level</option>{levels.filter(l=>l.active).map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label><div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:12}}><button type="button" className="btn primary" disabled={!selected||busy} onClick={async()=>{setBusy(true);try{const r=await fetch(`/api/staff/${id}/access`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({accessLevelId:selected,staffApp:true})});const d=await r.json();if(!r.ok)throw Error(d.error);setLink(d.personalUrl);setOpen(true);setMessage('Staff app access enabled. Share the personal link or QR code.')}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}}>{busy?'Saving…':link?'Save access level':'Create invite link'}</button>{link&&<button type="button" className="btn secondary" onClick={()=>setOpen(true)}>Invite link & QR code</button>}</div><p role="status">{message}</p><small><a href="/dashboard/settings/access-levels">Manage access levels</a> · <a href="/dashboard/staff/access">Disable or recover staff access</a>. Management passwords are managed in Users & Permissions.</small>
 {open&&<StaffDialog label="Personal Staff app link" management onClose={()=>setOpen(false)}><div className="card" style={{padding:24}}><h2>Personal Staff app link</h2><p>Open or scan the link on their phone, choose Install STARS Staff, then sign in with their existing PIN. The link alone does not sign them in.</p>{qr&&<Image unoptimized src={qr} alt="QR code for this employee's personal Staff app link" width={260} height={260}/>}<label>Personal link<input className="field" readOnly value={link} onFocus={e=>e.target.select()}/></label><div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:12}}><button type="button" className="btn primary" onClick={async()=>{try{await navigator.clipboard.writeText(link);setMessage('Personal link copied.')}catch{setMessage('Select and copy the link above.')}}}>Copy link</button><a className="btn secondary" href={qr} download="stars-staff-qr.png">Download QR</a><button type="button" className="btn secondary" onClick={()=>setOpen(false)}>Close</button></div></div></StaffDialog>}
 </section>
}
