"use client";
import {useEffect,useRef,useState} from "react";
type Receipt={viewedAt?:string;readAt?:string;agreedAt?:string;userName?:string};
type Resource={documentId?:string;id:string;title:string;content:string;category:string;status:string;version:number;receipt?:Receipt;receipts?:Receipt[]};
export function StaffPortal(){const openedLink=useRef(false);const [rows,setRows]=useState<Resource[]>([]),[selected,setSelected]=useState<Resource|null>(null),[canManage,setCanManage]=useState(false),[category,setCategory]=useState("POLICY"),[message,setMessage]=useState(""),[caps,setCaps]=useState<string[]>([]),[training,setTraining]=useState<Array<{id:string;courseName:string;completedDate:string;expiryDate?:string;staff:{displayName:string}}>>([]);
 async function load(){const r=await fetch("/api/staff-resources");const d=await r.json();if(!r.ok){setMessage(d.error);return}setRows(d.rows);setCanManage(d.canManage);if(!openedLink.current){openedLink.current=true;const requested=new URLSearchParams(window.location.search).get("resource");const resource=d.rows.find((r:Resource)=>r.id===requested);if(resource){setSelected(resource);setCategory(resource.category);}}setSelected(current=>current?d.rows.find((x:Resource)=>x.id===current.id)||null:null)}
 useEffect(()=>{void load();fetch("/api/auth/me").then(r=>r.json()).then(d=>setCaps(d.capabilities||[]));fetch("/api/staff-portal/training").then(async r=>{if(r.ok)setTraining(await r.json())})},[]);
 async function action(id:string,action:string,extra={}){const r=await fetch(`/api/staff-resources/${id}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,...extra})});const d=await r.json();setMessage(r.ok?"Saved.":d.error);if(r.ok)await load();return r.ok;}
 return <><div className="toolbar"><a className="btn secondary" href="/api/staff-portal/guidance">Download my personal guide</a>{caps.includes("staff-calendar.view")&&<a className="btn secondary" href="/staff-portal/calendar">Operational calendar</a>}</div><p>Open a published document to review it. Reading and agreement are recorded separately for each version.</p>{message&&<p role="status" className="alert">{message}</p>}<div className="toolbar">{[["POLICY","Policies","staff-policies.view"],["RIDDOR","RIDDOR","staff-riddor.view"],["SDS","SDS","staff-sds.view"],["RAMS","RAMS","staff-rams.view"]].filter(([, ,cap])=>caps.includes(cap)).map(([key,label])=><button className={`btn ${category===key?"primary":"secondary"}`} key={key} onClick={()=>setCategory(key)}>{label}</button>)}</div><section className="card table-wrap"><table className="table"><thead><tr><th>Document</th><th>Version</th><th>Status</th><th>Your acknowledgement</th><th>Action</th></tr></thead><tbody>{rows.filter(r=>r.category===category).map(r=><tr key={r.id}><td>{r.title}</td><td>{r.version}</td><td>{r.status}</td><td>{r.receipt?.agreedAt?"Agreed":r.receipt?.readAt?"Read":r.receipt?.viewedAt?"Viewed":"Not reviewed"}</td><td><button className="btn secondary" onClick={async()=>{setSelected(r);if(r.status==="PUBLISHED")await action(r.id,"view")}}>Open</button></td></tr>)}</tbody></table>{!rows.some(r=>r.category===category)&&<p className="empty">No documents available in this category.</p>}</section>
 {canManage&&<details className="card" style={{padding:20,marginTop:16}}><summary>Add a completed policy, SDS, RAMS or RIDDOR guidance</summary><form onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;const r=await fetch("/api/staff-resources",{method:"POST",body:new FormData(form)});const d=await r.json();setMessage(r.ok?"Draft added. Open it to review and publish.":d.error);if(r.ok){form.reset();await load()}}}><label>Title<input className="field" name="title" required maxLength={191}/></label><label>Category<select className="field" name="category">{["POLICY","RIDDOR","SDS","RAMS"].map(c=><option key={c}>{c}</option>)}</select></label><label>Document text / description<textarea className="field" name="content" required/></label><label>Completed document (PDF)<input className="field" type="file" name="file" accept="application/pdf"/></label><label>Review date<input className="field" type="date" name="reviewDate"/></label><button className="btn primary">Add draft</button></form></details>}
 {caps.includes("staff-training.view")&&<section className="card" style={{padding:20,marginTop:20}}><h2>Training matrix</h2><table className="table"><thead><tr><th>Staff</th><th>Course</th><th>Completed</th><th>Expires</th></tr></thead><tbody>{training.map(t=><tr key={t.id}><td>{t.staff.displayName}</td><td>{t.courseName}</td><td>{t.completedDate.slice(0,10)}</td><td>{t.expiryDate?.slice(0,10)||"No expiry"}</td></tr>)}</tbody></table>{!training.length&&<p>No training records available for your account.</p>}</section>}
 {selected&&<div className="modal-backdrop"><section className="modal"><h2>{selected.title} · v{selected.version}</h2>{canManage&&selected.status==="DRAFT"?<textarea className="field" rows={16} value={selected.content} onChange={e=>setSelected({...selected,content:e.target.value})}/>:<div style={{whiteSpace:"pre-wrap"}}>{selected.content}</div>}{selected.documentId&&<iframe title={selected.title} src={`/api/staff-resources/${selected.id}/download?inline=1`} style={{width:"100%",height:480,border:0}}/>}<div className="toolbar"><a className="btn secondary" href={`/api/staff-resources/${selected.id}/download`}>Download document</a>{selected.status==="PUBLISHED"&&<><button className="btn secondary" disabled={!selected.receipt?.viewedAt||!!selected.receipt?.readAt} onClick={()=>action(selected.id,"read")}>I have read this version</button><button className="btn primary" disabled={!selected.receipt?.readAt||!!selected.receipt?.agreedAt} onClick={()=>action(selected.id,"agree")}>I agree to this version</button></>}{canManage&&<>{selected.status==="DRAFT"?<><button className="btn secondary" onClick={()=>action(selected.id,"save",{content:selected.content})}>Save draft</button><button className="btn primary" onClick={async()=>{if(await action(selected.id,"save",{content:selected.content}))await action(selected.id,"publish")}}>Approve and publish</button></>:<button className="btn secondary" onClick={()=>action(selected.id,"revise")}>Create new revision</button>}<button className="btn secondary" onClick={()=>action(selected.id,"archive")}>Archive</button></>}<button className="btn secondary" onClick={()=>setSelected(null)}>Close</button></div>{canManage&&<details><summary>Staff view / read / agreed log</summary>{selected.receipts?.map((r,i)=><p key={i}>{r.userName}: viewed {r.viewedAt||"—"}; read {r.readAt||"—"}; agreed {r.agreedAt||"—"}</p>)}</details>}</section></div>}</>;
}
