"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import {CalendarDays,HeartPulse,X} from "lucide-react";

type Absence={id:string;staffId:string;name:string;type:string;startDate:string;endDate:string;startTime?:string|null;endTime?:string|null;notes?:string|null;updatedAt:string;bradfordExcluded?:boolean;bradfordReason?:string|null};
const today=()=>new Date().toLocaleDateString("sv-SE",{timeZone:"Europe/London"});
const date=(value:string)=>new Date(value).toLocaleDateString("en-GB",{timeZone:"UTC"});
const blank=(staffId="",type="ANNUAL_LEAVE")=>({staffId,type,startDate:today(),endDate:today(),startTime:"",endTime:"",notes:"",bradfordExcluded:false,bradfordReason:""});
export function StaffAbsences({onChanged,compact=false,staffId}:{onChanged?:()=>void;compact?:boolean;staffId?:string}){
 const dialog=useRef<HTMLDialogElement>(null);
 const [open,setOpen]=useState(false),[staff,setStaff]=useState<Array<{id:string;name:string}>>([]),[records,setRecords]=useState<Absence[]>([]),[canManage,setCanManage]=useState(false),[search,setSearch]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[form,setForm]=useState(blank(staffId)),[editing,setEditing]=useState<Absence|null>(null),[reason,setReason]=useState(""),[cancelling,setCancelling]=useState(false);
 const load=useCallback(async()=>{try{const response=await fetch(`/api/calendar/absences${staffId?`?staffId=${staffId}`:""}`,{cache:"no-store"});if(response.status===403)return;if(!response.ok)throw Error("Unable to load staff absences.");const result=await response.json();setStaff(result.staff);setRecords(result.records);setCanManage(result.canManage)}catch(error){setError(error instanceof Error?error.message:"Unable to load staff absences.")}},[staffId]);
 useEffect(()=>{void load()},[load]);useEffect(()=>{if(open)dialog.current?.showModal();else dialog.current?.close()},[open]);
 function start(type:string){setForm(blank(staffId,type));setEditing(null);setCancelling(false);setReason("");setError("");setOpen(true)}
 function edit(record:Absence,cancel=false){setEditing(record);setCancelling(cancel);setForm({staffId:record.staffId,type:record.type,startDate:record.startDate.slice(0,10),endDate:record.endDate.slice(0,10),startTime:record.startTime||"",endTime:record.endTime||"",notes:record.notes||"",bradfordExcluded:!!record.bradfordExcluded,bradfordReason:record.bradfordReason||""});setReason("");setError("");setOpen(true)}
 async function save(event:React.FormEvent){event.preventDefault();if(busy)return;setBusy(true);setError("");try{
  const values={...form,startTime:form.startTime||null,endTime:form.endTime||null};
  const body=editing?{id:editing.id,updatedAt:editing.updatedAt,reason,...(!cancelling?{values}:{})}:values;
  const response=await fetch("/api/calendar/absences",{method:editing?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});
  const result=await response.json();if(!response.ok)throw Error(result.error||"Unable to save absence.");setOpen(false);await load();onChanged?.();window.dispatchEvent(new Event("staff-planning-changed"));
 }catch(error){setError(error instanceof Error?error.message:"Unable to save absence.")}finally{setBusy(false)}}
 return <section className="staff-absences">
 {canManage&&<div className="toolbar"><button type="button" className="btn secondary" onClick={()=>start("ANNUAL_LEAVE")}><CalendarDays size={18}/>Record holiday</button><button type="button" className="btn secondary" onClick={()=>start("SICKNESS")}><HeartPulse size={18}/>Record sickness</button></div>}
 {!open&&error&&<p role="alert">{error}</p>}
 {!compact&&<details className="card" style={{padding:16,marginBottom:20}} open={!!staffId}><summary>Staff holidays & sickness · {records.length} {staffId?"records":"recent records"}</summary>
 {!staffId&&<label className="form-label">Search absence records<input className="field" type="search" value={search} onChange={event=>setSearch(event.target.value)} placeholder="Staff name"/></label>}
 {records.filter(record=>record.name.toLowerCase().includes(search.toLowerCase())).map(record=><div className="staff-absence-row" key={record.id}><div><b>{record.name}</b><p>{record.type==="SICKNESS"?"Sickness":"Holiday"} · {date(record.startDate)} – {date(record.endDate)}{record.startTime?` · ${record.startTime}–${record.endTime}`:""}</p>{record.bradfordExcluded&&<small>Excluded from Bradford score</small>}</div>{canManage&&<div className="toolbar"><button type="button" className="btn secondary" disabled={busy} onClick={()=>edit(record)}>Edit</button><button type="button" className="btn ghost" disabled={busy} onClick={()=>edit(record,true)}>Cancel record</button></div>}</div>)}
 {!records.length&&<p className="muted">No holidays or sickness recorded.</p>}</details>}
 <dialog ref={dialog} className="staff-absence-dialog" aria-labelledby="absence-title" onCancel={event=>{event.preventDefault();if(!busy)setOpen(false)}}><header><h2 id="absence-title">{cancelling?"Cancel":editing?"Edit":"Record"} {form.type==="SICKNESS"?"sickness":"holiday"}</h2><button type="button" className="btn ghost" aria-label="Close absence form" disabled={busy} onClick={()=>setOpen(false)}><X size={20}/></button></header>
 <form onSubmit={save}><p className="muted">{cancelling?"The record remains in the audit history and will stop counting towards absence totals.":"Updates the staff profile and planned staffing. Clocking and payroll are managed separately."}</p>
 <fieldset disabled={busy||cancelling} style={{border:0,padding:0}}><div className="form-grid">
 <label className="form-label full">Staff member<select className="field" required disabled={!!editing||!!staffId} value={form.staffId} onChange={event=>setForm({...form,staffId:event.target.value})}><option value="">Choose staff member</option>{!staff.some(s=>s.id===form.staffId)&&editing&&<option value={editing.staffId}>{editing.name}</option>}{staff.map(person=><option key={person.id} value={person.id}>{person.name}</option>)}</select></label>
 <label className="form-label">From<input className="field" type="date" required value={form.startDate} onChange={event=>setForm({...form,startDate:event.target.value,endDate:form.endDate<event.target.value?event.target.value:form.endDate})}/></label>
 <label className="form-label">To<input className="field" type="date" required min={form.startDate} value={form.endDate} onChange={event=>setForm({...form,endDate:event.target.value})}/></label>
 <label className="form-label">Start time (optional)<input className="field" type="time" value={form.startTime} onChange={e=>setForm({...form,startTime:e.target.value})}/></label><label className="form-label">End time (optional)<input className="field" type="time" required={!!form.startTime} value={form.endTime} onChange={e=>setForm({...form,endTime:e.target.value})}/></label><small className="full">Leave both times blank for whole working days. Times apply to each date in the range.</small>
 <label className="form-label full">Management note (optional)<textarea className="field" maxLength={2000} value={form.notes} onChange={event=>setForm({...form,notes:event.target.value})}/><small>Notes are kept in the management record, not displayed on the calendar.</small></label>
 {form.type==="SICKNESS"&&<><label className="full"><input type="checkbox" checked={form.bradfordExcluded} onChange={e=>setForm({...form,bradfordExcluded:e.target.checked})}/> Exclude from Bradford score</label>{form.bradfordExcluded&&<label className="form-label full">Exclusion reason<textarea className="field" required maxLength={500} value={form.bradfordReason} onChange={e=>setForm({...form,bradfordReason:e.target.value})}/><small>For example, an agreed adjustment or pregnancy-related absence.</small></label>}</>}
 </div></fieldset>
 {editing&&<label className="form-label">Reason for {cancelling?"cancellation":"change"}<textarea className="field" required maxLength={2000} disabled={busy} value={reason} onChange={e=>setReason(e.target.value)}/></label>}
 {error&&<p role="alert" className="alert alert-error">{error}</p>}<div className="modal-actions"><button type="button" className="btn secondary" disabled={busy} onClick={()=>setOpen(false)}>Back</button><button className={`btn ${cancelling?"danger":"primary"}`} disabled={busy}>{busy?"Saving…":cancelling?"Cancel record":"Save absence"}</button></div></form></dialog></section>;
}
