"use client";
import {useEffect,useState} from "react";
import {CalendarDays} from "lucide-react";
import {workingDaysInput} from "@/lib/staff-planning";
const weekdays=[[1,"Monday"],[2,"Tuesday"],[3,"Wednesday"],[4,"Thursday"],[5,"Friday"],[6,"Saturday"],[0,"Sunday"]] as const;
type Day={dayOfWeek:number;startTime:string;endTime:string};
type Pattern={id:string;effectiveStart:string;effectiveEnd:string|null;cycleWeeks:number;intervals:Day[]};
const today=()=>new Date().toLocaleDateString("sv-SE",{timeZone:"Europe/London"});
export function StaffWorkingDays({staffId}:{staffId:string}){
 const [days,setDays]=useState<Day[]>([]),[effectiveStart,setStart]=useState(today),[patterns,setPatterns]=useState<Pattern[]>([]),[canManage,setCanManage]=useState(false),[visible,setVisible]=useState(true),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 useEffect(()=>{const abort=new AbortController();fetch(`/api/staff/${staffId}/working-days`,{signal:abort.signal,cache:"no-store"}).then(async response=>{if(response.status===403){setVisible(false);return}if(!response.ok)throw Error("Unable to load working days.");const data=await response.json();setPatterns(data.patterns);setCanManage(data.canManage);const latest=data.patterns[0] as Pattern|undefined;if(latest){setDays(latest.intervals.filter((day,index,array)=>array.findIndex(item=>item.dayOfWeek===day.dayOfWeek)===index));setStart(latest.effectiveStart.slice(0,10)>today()?latest.effectiveStart.slice(0,10):today())}}).catch(error=>{if(error.name!=="AbortError")setMessage(error.message)}).finally(()=>{if(!abort.signal.aborted)setLoading(false)});return()=>abort.abort()},[staffId]);
 async function save(){const payload={effectiveStart,days};if(!workingDaysInput.safeParse(payload).success){setMessage("Check each selected day's start and end times.");return}setBusy(true);setMessage("");try{const response=await fetch(`/api/staff/${staffId}/working-days`,{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const result=await response.json();if(!response.ok)throw Error(result.error||"Unable to save working days.");setPatterns(previous=>[result.pattern,...previous]);setMessage("Working days saved. The operational calendar now uses this schedule.");window.dispatchEvent(new Event("staff-planning-changed"))}catch(error){setMessage(error instanceof Error?error.message:"Unable to save working days.")}finally{setBusy(false)}}
 if(!visible)return null;
 return <section className="staff-working-days"><h3><CalendarDays size={20}/> Working days</h3><p className="muted">Set the weekly schedule shown on the operational calendar. These are planned hours, separate from clocking and payroll.</p>{loading?<p>Loading working days…</p>:<><label className="form-label">Apply schedule from<input className="field" type="date" min={today()} value={effectiveStart} disabled={!canManage||busy} onChange={event=>setStart(event.target.value)}/></label>{patterns[0]&&<small className="muted">Latest saved schedule starts {new Date(patterns[0].effectiveStart).toLocaleDateString("en-GB",{timeZone:"UTC"})}.{patterns[0].cycleWeeks>1&&" Saving here replaces the rotating pattern with a weekly schedule from the chosen date."}</small>}<div className="staff-week-grid">{weekdays.map(([value,label])=>{const day=days.find(item=>item.dayOfWeek===value);return <div key={value} className={day?"working":""}><label><input type="checkbox" checked={!!day} disabled={!canManage||busy} onChange={event=>setDays(previous=>event.target.checked?[...previous,{dayOfWeek:value,startTime:"09:00",endTime:"17:00"}]:previous.filter(item=>item.dayOfWeek!==value))}/>{label}</label>{day&&<div><input className="field" aria-label={`${label} start time`} type="time" value={day.startTime} disabled={!canManage||busy} onChange={event=>setDays(previous=>previous.map(item=>item.dayOfWeek===value?{...item,startTime:event.target.value}:item))}/><span>to</span><input className="field" aria-label={`${label} end time`} type="time" value={day.endTime} disabled={!canManage||busy} onChange={event=>setDays(previous=>previous.map(item=>item.dayOfWeek===value?{...item,endTime:event.target.value}:item))}/></div>}</div>})}</div><p className="muted">Times use Europe/London. New days start at 09:00–17:00; adjust them before saving. Clear every day to end the regular schedule from the chosen date.</p>{canManage&&<button type="button" className="btn secondary" disabled={busy} onClick={()=>void save()}>{busy?"Saving…":"Save working days"}</button>}</>}{message&&<p role="status">{message}</p>}</section>;
}
