"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { Archive, CalendarClock, CreditCard, Download, FileClock, HeartPulse, Pencil, Plus, RotateCcw, Search, ShieldCheck, UserRound } from "lucide-react";
import { appConfirm } from "@/lib/app-dialog";
import { latestConsentValues } from "@/lib/student-profile";

type JsonMap = Record<string, string>;
type BillingProfile = { id: string; payerType: string; payerName: string; billingAddress: string; billingEmail?: string; activeFrom: string; activeTo?: string; vatTreatment: string; vatRate: number|string; chargeRules: Array<{rate:number|string;description?:string}> };
type Consent = { id:string; consentType:string; newValue:unknown; providedByName:string; providedAt:string; approvedAt?:string|null };
type Review = { id:string; status:string; submittedAt?:string|null; completedAt?:string|null; nextReviewDate?:string|null };
type Student = {
  id:string; firstName:string; lastName:string; displayName:string; active:boolean; startDate:string; endDate?:string; expectedDays:number[]; internalReference?:string; notes?:string;
  dateOfBirth?:string; addressLine1?:string; addressLine2?:string; town?:string; postcode?:string; phone?:string; email?:string; nhsNumber?:string; hospitalNumber?:string;
  emergencyContactName?:string; emergencyContactRelationship?:string; emergencyContactPhone?:string; emergencyContactAlternativePhone?:string; emergencyContactEmail?:string; emergencyContactNotes?:string;
  secondaryEmergencyContact?:JsonMap|null; gpName?:string; gpSurgery?:string; gpPhone?:string; medicalProfile?:JsonMap|null; personCentredProfile?:JsonMap|null;
  lastInformationReviewAt?:string|null; nextInformationReviewAt?:string|null; consentHistory?:Consent[]; informationReviews?:Review[]; billingProfile?:BillingProfile|null;
};
type Tab = "details"|"contacts"|"medical"|"profile"|"consents"|"billing"|"rams";

const blank = {
  firstName:"",lastName:"",displayName:"",startDate:"",endDate:"",expectedDays:[1,2,3,4,5],internalReference:"",notes:"",dateOfBirth:"",addressLine1:"",addressLine2:"",town:"",postcode:"",phone:"",email:"",nhsNumber:"",hospitalNumber:"",
  emergencyContactName:"",emergencyContactRelationship:"",emergencyContactPhone:"",emergencyContactAlternativePhone:"",emergencyContactEmail:"",emergencyContactNotes:"",
  secondaryEmergencyContact:{name:"",relationship:"",phone:"",email:""},gpName:"",gpSurgery:"",gpPhone:"",medicalProfile:{conditions:"",allergies:"",emergencyMedication:"",currentMedication:"",instructions:""},
  personCentredProfile:{communication:"",supportStrategies:"",interests:"",dislikes:"",triggers:"",calmingStrategies:"",goals:""},
};
const days = [[1,"Mon"],[2,"Tue"],[3,"Wed"],[4,"Thu"],[5,"Fri"],[6,"Sat"],[7,"Sun"]] as const;
const tabs:Array<[Tab,string]> = [["details","Details"],["contacts","Emergency contacts"],["medical","Medical"],["profile","Person-centred"],["consents","Consents & reviews"],["billing","Billing"],["rams","RAMS"]];
const consentLabels:Record<string,string> = {photography:"Photography and video",localTrips:"Local outings",transport:"STARS transport",emergencyTreatment:"Emergency treatment",informationSharing:"Necessary information sharing"};
const dateValue=(value?:string|null)=>value?.slice(0,10)||"";
const field=(value:unknown)=>typeof value==="string"?value:"";
const medicalText=(value:unknown)=>Array.isArray(value)?value.map(item=>typeof item==="string"?item:typeof item==="object"&&item?`${String((item as Record<string,unknown>).name||"")}${(item as Record<string,unknown>).frequency?` - ${String((item as Record<string,unknown>).frequency)}`:""}${(item as Record<string,unknown>).dosage?` - ${String((item as Record<string,unknown>).dosage)}`:""}`:"").filter(Boolean).join("\n"):field(value);
const consentSummary=(key:string,value:unknown)=>{if(value===undefined)return "Not recorded";if(typeof value==="boolean")return value?"Consent given":"Consent not given";if(key==="localTrips")return value==="YES"?"Consent given":value==="NO"?"Consent not given":"Other instructions recorded";if(key==="photography"&&typeof value==="object"&&value){const choices=value as Record<string,boolean>;if(choices.none)return "No media consent";const count=Object.entries(choices).filter(([name,enabled])=>name!=="none"&&enabled).length;return count?`${count} approved use${count===1?"":"s"}`:"No choices selected"}return "Recorded"};

export function StudentManagerV2(){
  const[rows,setRows]=useState<Student[]>([]),[search,setSearch]=useState(""),[status,setStatus]=useState("active"),[editing,setEditing]=useState<Student|null|"new">(null),[form,setForm]=useState(blank),[tab,setTab]=useState<Tab>("details");
  const[error,setError]=useState(""),[notice,setNotice]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[canManageBilling,setCanManageBilling]=useState(false);
  const load=useCallback(async()=>{setLoading(true);const response=await fetch(`/api/students/records?status=${status}&search=${encodeURIComponent(search)}`,{cache:"no-store"});if(response.status===403){location.href="/login";return}setRows(response.ok?await response.json():[]);setLoading(false)},[search,status]);
  useEffect(()=>{fetch("/api/auth/me").then(r=>r.ok?r.json():null).then(user=>setCanManageBilling(Boolean(user&&["DIRECTOR","ADMINISTRATOR"].includes(user.role))))},[]);
  useEffect(()=>{const id=setTimeout(load,200);return()=>clearTimeout(id)},[load]);
  const nested=(group:"secondaryEmergencyContact"|"medicalProfile"|"personCentredProfile",key:string,value:string)=>setForm(current=>({...current,[group]:{...current[group],[key]:value}}));
  function open(row?:Student){setEditing(row||"new");setTab("details");setError("");setNotice("");setForm(row?{
    firstName:row.firstName,lastName:row.lastName,displayName:row.displayName,startDate:dateValue(row.startDate),endDate:dateValue(row.endDate),expectedDays:(row.expectedDays||[]).map(Number),internalReference:row.internalReference||"",notes:row.notes||"",dateOfBirth:dateValue(row.dateOfBirth),addressLine1:row.addressLine1||"",addressLine2:row.addressLine2||"",town:row.town||"",postcode:row.postcode||"",phone:row.phone||"",email:row.email||"",nhsNumber:row.nhsNumber||"",hospitalNumber:row.hospitalNumber||"",
    emergencyContactName:row.emergencyContactName||"",emergencyContactRelationship:row.emergencyContactRelationship||"",emergencyContactPhone:row.emergencyContactPhone||"",emergencyContactAlternativePhone:row.emergencyContactAlternativePhone||"",emergencyContactEmail:row.emergencyContactEmail||"",emergencyContactNotes:row.emergencyContactNotes||"",
    secondaryEmergencyContact:{...blank.secondaryEmergencyContact,...(row.secondaryEmergencyContact||{})},gpName:row.gpName||"",gpSurgery:row.gpSurgery||"",gpPhone:row.gpPhone||"",medicalProfile:{conditions:medicalText(row.medicalProfile?.conditions),allergies:medicalText(row.medicalProfile?.allergies),emergencyMedication:medicalText(row.medicalProfile?.emergencyMedication),currentMedication:medicalText(row.medicalProfile?.currentMedication),instructions:medicalText(row.medicalProfile?.instructions)},personCentredProfile:{...blank.personCentredProfile,...(row.personCentredProfile||{})},
  }:{...blank,expectedDays:[...blank.expectedDays],secondaryEmergencyContact:{...blank.secondaryEmergencyContact},medicalProfile:{...blank.medicalProfile},personCentredProfile:{...blank.personCentredProfile}})}
  async function save(event:React.FormEvent){event.preventDefault();setSaving(true);setError("");const isNew=editing==="new";const response=await fetch(isNew?"/api/students/records":`/api/students/records/${(editing as Student).id}`,{method:isNew?"POST":"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(form)});const result=await response.json().catch(()=>({}));setSaving(false);if(!response.ok)return setError(result.error||"Unable to save the student profile.");setEditing(null);setNotice(isNew?"Student added.":"Student profile updated.");await load()}
  async function setActive(row:Student,active:boolean){if(!await appConfirm(`${active?"Restore":"Archive"} ${row.displayName}? Historic attendance and billing records will be preserved.`))return;await fetch(`/api/students/records/${row.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({active})});await load()}
  const current=editing&&editing!=="new"?editing:null;
  const consents=latestConsentValues(current?.consentHistory||[]);
  const input=(label:string,key:keyof typeof blank,type="text")=><label className="form-label">{label}<input autoComplete="off" className="field" type={type} value={String(form[key]??"")} onChange={event=>setForm({...form,[key]:event.target.value})}/></label>;
  const area=(label:string,group:"medicalProfile"|"personCentredProfile",key:string)=><label className="form-label">{label}<textarea className="field" rows={4} value={field((form[group] as Record<string,string>)[key])} onChange={event=>nested(group,key,event.target.value)}/></label>;
  return <>
    {notice&&<div className="alert alert-success">{notice}</div>}
    <div className="toolbar"><label style={{position:"relative"}}><Search size={18} style={{position:"absolute",left:13,top:16}}/><input autoComplete="off" className="field" style={{paddingLeft:40}} placeholder="Search students" value={search} onChange={event=>setSearch(event.target.value)}/></label><select className="field" value={status} onChange={event=>setStatus(event.target.value)}><option value="active">Active students</option><option value="archived">Archived students</option><option value="all">All students</option></select><button className="btn primary" style={{marginLeft:"auto"}} onClick={()=>open()}><Plus size={18}/>Add student</button></div>
    <section className="card table-wrap">{loading?<div className="empty">Loading students...</div>:rows.length?<table className="table"><thead><tr><th>Name</th><th>Reference</th><th>Expected days</th><th>Emergency contact</th><th>Billing</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><b>{row.displayName}</b></td><td>{row.internalReference||"—"}</td><td>{(row.expectedDays||[]).map(Number).map(n=>days.find(day=>day[0]===n)?.[1]).join(", ")||"None"}</td><td>{row.emergencyContactName?<><b>{row.emergencyContactName}</b><small className="muted" style={{display:"block"}}>{row.emergencyContactPhone||"No telephone"}</small></>:<span className="badge badge-warning">Not configured</span>}</td><td>{row.billingProfile?<><span className={`badge ${row.billingProfile.activeTo?"badge-neutral":"badge-success"}`}>{row.billingProfile.activeTo?"Ended":"Configured"}</span><small className="muted" style={{display:"block"}}>{row.billingProfile.payerName}</small></>:canManageBilling?<span className="badge badge-warning">Not configured</span>:"—"}</td><td><span className={`badge ${row.active?"badge-success":"badge-neutral"}`}>{row.active?"Active":"Archived"}</span></td><td><div className="table-actions"><button className="btn ghost" onClick={()=>open(row)} aria-label={`Open ${row.displayName}`}><Pencil size={17}/></button><button className={`btn ${row.active?"danger":"secondary"}`} onClick={()=>setActive(row,!row.active)}>{row.active?<Archive size={17}/>:<RotateCcw size={17}/>}</button></div></td></tr>)}</tbody></table>:<div className="empty"><b>No students found</b><p>Change the filters or add a student.</p></div>}</section>
    {editing&&<div className="modal-backdrop"><form autoComplete="off" className="modal student-record-modal" onSubmit={save}><div className="modal-title-row"><div><h2>{editing==="new"?"Add student":current!.displayName}</h2><p className="muted">Protected student profile</p></div><div className="student-record-title-actions">{current&&<a className="btn secondary" href={`/api/students/records/${current.id}/pdf`}><Download size={17}/>Download complete record PDF</a>}{current?.nextInformationReviewAt&&<span className="badge badge-neutral"><CalendarClock size={15}/> Review due {new Date(current.nextInformationReviewAt).toLocaleDateString("en-GB")}</span>}</div></div>{error&&<div className="alert alert-error">{error}</div>}
      <nav className="tabs student-profile-tabs" aria-label="Student profile sections">{tabs.map(([id,label])=><button type="button" key={id} className={`btn ${tab===id?"primary":"secondary"}`} onClick={()=>setTab(id)}>{label}</button>)}</nav>
      {tab==="details"&&<section><h3><UserRound size={19}/>Student details</h3><div className="form-grid">{input("First name","firstName")}{input("Surname","lastName")}{input("Display name","displayName")}{input("Internal reference","internalReference")}{input("Date of birth","dateOfBirth","date")}{input("Telephone","phone")}{input("Email","email","email")}{input("Start date","startDate","date")}{input("End date","endDate","date")}{input("Address line 1","addressLine1")}{input("Address line 2","addressLine2")}{input("Town","town")}{input("Postcode","postcode")}<fieldset className="full record-fieldset"><legend>Expected attendance days</legend><div className="check-list">{days.map(([number,label])=><label key={number}><input type="checkbox" checked={form.expectedDays.includes(number)} onChange={event=>setForm({...form,expectedDays:event.target.checked?[...form.expectedDays,number].sort():form.expectedDays.filter(value=>value!==number)})}/> {label}</label>)}</div></fieldset><label className="form-label full">Restricted manager notes<textarea className="field" rows={4} value={form.notes} onChange={event=>setForm({...form,notes:event.target.value})}/></label></div></section>}
      {tab==="contacts"&&<section><h3>Primary emergency contact</h3><p className="muted">Protected manager information. It is not downloaded to kiosk tablets.</p><div className="form-grid">{input("Contact name","emergencyContactName")}{input("Relationship","emergencyContactRelationship")}{input("Primary telephone","emergencyContactPhone")}{input("Alternative telephone","emergencyContactAlternativePhone")}{input("Email","emergencyContactEmail","email")}<label className="form-label full">Emergency instructions<textarea className="field" rows={4} value={form.emergencyContactNotes} onChange={event=>setForm({...form,emergencyContactNotes:event.target.value})}/></label></div><h3>Secondary emergency contact</h3><div className="form-grid">{[["Name","name"],["Relationship","relationship"],["Telephone","phone"],["Email","email"]].map(([label,key])=><label className="form-label" key={key}>{label}<input className="field" type={key==="email"?"email":"text"} value={field((form.secondaryEmergencyContact as Record<string,string>)[key])} onChange={event=>nested("secondaryEmergencyContact",key,event.target.value)}/></label>)}</div></section>}
      {tab==="medical"&&<section><h3><HeartPulse size={19}/>Medical information</h3><div className="form-grid">{input("NHS number","nhsNumber")}{input("Hospital number","hospitalNumber")}{input("GP name","gpName")}{input("GP surgery","gpSurgery")}{input("GP telephone","gpPhone")}{area("Medical conditions","medicalProfile","conditions")}{area("Allergies","medicalProfile","allergies")}{area("Emergency medication","medicalProfile","emergencyMedication")}{area("Current medication","medicalProfile","currentMedication")}{area("Other medical instructions","medicalProfile","instructions")}</div></section>}
      {tab==="profile"&&<section><h3>Person-centred profile</h3><div className="form-grid">{area("How I communicate","personCentredProfile","communication")}{area("Support strategies that work","personCentredProfile","supportStrategies")}{area("Interests and things I enjoy","personCentredProfile","interests")}{area("Dislikes","personCentredProfile","dislikes")}{area("Triggers or things that may upset me","personCentredProfile","triggers")}{area("What helps me feel calm","personCentredProfile","calmingStrategies")}{area("Current goals","personCentredProfile","goals")}</div></section>}
      {tab==="consents"&&<section><h3><ShieldCheck size={19}/>Current consent decisions</h3>{current?(Object.keys(consentLabels).map(key=><div className="student-summary-row" key={key}><span>{consentLabels[key]}</span><span className="badge badge-neutral">{consentSummary(key,consents[key])}</span></div>)):<div className="empty">Consent history becomes available after the student is saved.</div>}<h3><FileClock size={19}/>Information review history</h3>{current?.informationReviews?.length?current.informationReviews.map(review=><div className="student-summary-row" key={review.id}><span><b>{review.status.replaceAll("_"," ")}</b><small className="muted" style={{display:"block"}}>{review.submittedAt?`Submitted ${new Date(review.submittedAt).toLocaleString("en-GB")}`:"Not yet submitted"}</small></span><Link className="btn ghost" href={`/dashboard/information-reviews/${review.id}`}>View review</Link></div>):<div className="empty">No information reviews recorded.</div>}</section>}
      {tab==="billing"&&<section><h3><CreditCard size={19}/>Billing setup</h3>{!current?<div className="empty">Save this student before configuring billing.</div>:current.billingProfile?<div className="card student-billing-summary"><div><span className="muted">Payer</span><b>{current.billingProfile.payerName}</b><small>{current.billingProfile.payerType}</small></div><div><span className="muted">Day rate</span><b>£{Number(current.billingProfile.chargeRules[0]?.rate||0).toFixed(2)}</b><small>{current.billingProfile.vatTreatment.replaceAll("_"," ").toLowerCase()}</small></div><div><span className="muted">Invoice contact</span><b>{current.billingProfile.billingEmail||"No email set"}</b><small>{current.billingProfile.billingAddress}</small></div></div>:<div className="alert alert-warning">Billing has not been configured for this student.</div>}{current&&canManageBilling&&<Link className="btn primary" href={`/dashboard/billing/profiles?studentId=${current.id}`}>{current.billingProfile?"Edit billing setup":"Set up billing"}</Link>}{current&&!canManageBilling&&<p className="muted">A director or administrator can change billing setup.</p>}</section>}
      {tab==="rams"&&<section className="student-coming-soon"><ShieldCheck size={48}/><h3>Student RAMS</h3><p>Coming soon</p><small className="muted">This area will hold student-specific risk assessments and safe-working information. No RAMS data is collected yet.</small></section>}
      <div className="modal-actions"><button type="button" className="btn secondary" onClick={()=>setEditing(null)}>Cancel</button>{!["consents","billing","rams"].includes(tab)&&<button className="btn primary" disabled={saving}>{saving?"Saving...":"Save student profile"}</button>}</div>
    </form></div>}
  </>;
}
