"use client";

import { useCallback, useEffect, useState } from "react";
import { Archive, Pencil, Plus, RotateCcw, Search } from "lucide-react";

type Student = { id: string; firstName: string; lastName: string; displayName: string; active: boolean; startDate: string; endDate?: string; expectedDays: number[]; fundingCategory?: string; fundingOrganisation?: string; internalReference?: string; notes?: string };
const blank = { firstName: "", lastName: "", displayName: "", startDate: "", endDate: "", expectedDays: [1,2,3,4,5], fundingCategory: "", fundingOrganisation: "", internalReference: "", notes: "" };
const days = [[1,"Mon"],[2,"Tue"],[3,"Wed"],[4,"Thu"],[5,"Fri"],[6,"Sat"],[7,"Sun"]] as const;

export function StudentManager() {
  const [rows,setRows]=useState<Student[]>([]),[search,setSearch]=useState(""),[status,setStatus]=useState("active");
  const [editing,setEditing]=useState<Student|null|"new">(null),[form,setForm]=useState(blank),[error,setError]=useState(""),[loading,setLoading]=useState(true);
  const load=useCallback(async()=>{setLoading(true);const r=await fetch(`/api/students/manage?status=${status}&search=${encodeURIComponent(search)}`);if(r.status===403){location.href="/login";return}setRows(r.ok?await r.json():[]);setLoading(false)},[search,status]);
  useEffect(()=>{const id=setTimeout(load,200);return()=>clearTimeout(id)},[load]);
  function open(row?:Student){setEditing(row||"new");setError("");setForm(row?{firstName:row.firstName,lastName:row.lastName,displayName:row.displayName,startDate:row.startDate.slice(0,10),endDate:row.endDate?.slice(0,10)||"",expectedDays:(row.expectedDays||[]).map(Number),fundingCategory:row.fundingCategory||"",fundingOrganisation:row.fundingOrganisation||"",internalReference:row.internalReference||"",notes:row.notes||""}:blank)}
  async function save(e:React.FormEvent){e.preventDefault();const isNew=editing==="new";const r=await fetch(isNew?"/api/students/manage":`/api/students/manage/${(editing as Student).id}`,{method:isNew?"POST":"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(form)});if(!r.ok){setError((await r.json()).error||"Unable to save student.");return}setEditing(null);await load()}
  async function setActive(row:Student,active:boolean){if(!confirm(`${active?"Restore":"Archive"} ${row.displayName}? Historic attendance will be preserved.`))return;await fetch(`/api/students/manage/${row.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({active})});await load()}
  return <><div className="toolbar"><label style={{position:"relative"}}><Search size={18} style={{position:"absolute",left:13,top:16}}/><input autoComplete="off" className="field" style={{paddingLeft:40}} placeholder="Search students" value={search} onChange={e=>setSearch(e.target.value)}/></label><select className="field" value={status} onChange={e=>setStatus(e.target.value)}><option value="active">Active students</option><option value="archived">Archived students</option><option value="all">All students</option></select><button className="btn primary" style={{marginLeft:"auto"}} onClick={()=>open()}><Plus size={18}/> Add student</button></div>
  <section className="card table-wrap">{loading?<div className="empty">Loading students…</div>:rows.length?<table className="table"><thead><tr><th>Name</th><th>Reference</th><th>Expected days</th><th>Funding</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><b>{row.displayName}</b></td><td>{row.internalReference||"—"}</td><td>{(row.expectedDays||[]).map(Number).map(n=>days.find(d=>d[0]===n)?.[1]).join(", ")||"None"}</td><td>{row.fundingCategory||"—"}</td><td><span className={`badge ${row.active?"badge-success":"badge-neutral"}`}>{row.active?"Active":"Archived"}</span></td><td><div style={{display:"flex",gap:7}}><button className="btn ghost" onClick={()=>open(row)}><Pencil size={17}/></button><button className={`btn ${row.active?"danger":"secondary"}`} onClick={()=>setActive(row,!row.active)}>{row.active?<Archive size={17}/>:<RotateCcw size={17}/>}</button></div></td></tr>)}</tbody></table>:<div className="empty"><b>No students found</b><p>Change the filters or add a student.</p></div>}</section>
  {editing&&<div className="modal-backdrop" role="dialog" aria-modal="true"><form autoComplete="off" className="modal" onSubmit={save}><h2>{editing==="new"?"Add student":`Edit ${(editing as Student).displayName}`}</h2>{error&&<div className="alert alert-error">{error}</div>}<div className="form-grid"><label className="form-label">First name<input autoComplete="off" className="field" required value={form.firstName} onChange={e=>setForm({...form,firstName:e.target.value})}/></label><label className="form-label">Surname<input autoComplete="off" className="field" required value={form.lastName} onChange={e=>setForm({...form,lastName:e.target.value})}/></label><label className="form-label">Display name<input autoComplete="off" className="field" required value={form.displayName} onChange={e=>setForm({...form,displayName:e.target.value})}/></label><label className="form-label">Internal reference<input autoComplete="off" className="field" value={form.internalReference} onChange={e=>setForm({...form,internalReference:e.target.value})}/></label><label className="form-label">Start date<input autoComplete="off" className="field" type="date" required value={form.startDate} onChange={e=>setForm({...form,startDate:e.target.value})}/></label><label className="form-label">End date<input autoComplete="off" className="field" type="date" value={form.endDate} onChange={e=>setForm({...form,endDate:e.target.value})}/></label><fieldset className="full" style={{border:"1px solid var(--border)",borderRadius:12}}><legend>Expected attendance days</legend><div style={{display:"flex",flexWrap:"wrap",gap:12}}>{days.map(([n,label])=><label key={n}><input autoComplete="off" type="checkbox" checked={form.expectedDays.includes(n)} onChange={e=>setForm({...form,expectedDays:e.target.checked?[...form.expectedDays,n].sort():form.expectedDays.filter(x=>x!==n)})}/> {label}</label>)}</div></fieldset><label className="form-label">Funding category<input autoComplete="off" className="field" value={form.fundingCategory} onChange={e=>setForm({...form,fundingCategory:e.target.value})}/></label><label className="form-label">Funding organisation<input autoComplete="off" className="field" value={form.fundingOrganisation} onChange={e=>setForm({...form,fundingOrganisation:e.target.value})}/></label><label className="form-label full">Restricted manager notes<textarea autoComplete="off" className="field" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label></div><div style={{display:"flex",justifyContent:"flex-end",gap:9,marginTop:20}}><button type="button" className="btn secondary" onClick={()=>setEditing(null)}>Cancel</button><button className="btn primary">Save student</button></div></form></div>}</>;
}
