"use client";

import { FormEvent, ReactNode, useCallback, useEffect, useMemo, useState } from "react";
import { Archive, BookOpen, Building2, Grid3X3, Pencil, Plus, Search, X } from "lucide-react";
import { appConfirm } from "@/lib/app-dialog";
import "@/app/training-matrix.css";

type Staff={id:string;displayName:string;firstName:string;lastName:string;jobRole?:string};
type Provider={id:string;name:string;contactName?:string|null;email?:string|null;phone?:string|null;website?:string|null;bookingNotes?:string|null;credentialsSummary?:string|null;accreditationBody?:string|null;accreditationReference?:string|null;accreditationExpiry?:string|null;evidenceReference?:string|null};
type Requirement="REQUIRED"|"CONDITIONAL"|"NOT_REQUIRED";
type Course={id:string;name:string;category:string;description?:string|null;renewalMonths?:number|null;warningDays:number;requirementRules:Record<string,Requirement>;providers:{provider:{id:string;name:string}}[]};
type RecordRow={id:string;staffId:string;courseId?:string|null;providerId?:string|null;courseName:string;provider?:string|null;certificateReference?:string|null;completedDate:string;expiryDate?:string|null;mandatory:boolean;notes?:string|null;staff:Staff;course?:Course|null;trainingProvider?:Provider|null};
type Cell={courseId:string;state:string;expiryDate:string|null};
type Matrix={courses:{id:string;name:string}[];rows:{id:string;name:string;role:string;cells:Cell[]}[];counts:Record<string,number>};
const recordBlank={staffId:"",courseId:"",providerId:"",courseName:"",provider:"",certificateReference:"",completedDate:"",expiryDate:"",mandatory:false,notes:""};
const providerBlank={name:"",contactName:"",email:"",phone:"",website:"",bookingNotes:"",credentialsSummary:"",accreditationBody:"",accreditationReference:"",accreditationExpiry:"",evidenceReference:""};
const courseBlank={name:"",category:"Core compliance",description:"",renewalMonths:"12",warningDays:"60",providerIds:[] as string[],requirementRules:{} as Record<string,Requirement>};
const labels:Record<string,string>={CURRENT:"Current",DUE_SOON:"Due soon",EXPIRED:"Expired",MISSING:"Missing",CONDITIONAL:"Conditional",NOT_REQUIRED:"Not required"};
async function json(response:Response){const data=await response.json().catch(()=>null);if(!response.ok)throw new Error(data?.error||"Request failed.");return data;}
function date(value?:string|null){return value?new Date(value).toLocaleDateString("en-GB"):"-";}

export function TrainingManager(){
 const[tab,setTab]=useState<"matrix"|"records"|"courses"|"providers">("matrix"),[rows,setRows]=useState<RecordRow[]>([]),[staff,setStaff]=useState<Staff[]>([]),[providers,setProviders]=useState<Provider[]>([]),[courses,setCourses]=useState<Course[]>([]),[roles,setRoles]=useState<string[]>([]),[matrix,setMatrix]=useState<Matrix|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[search,setSearch]=useState("");
 const[recordEditor,setRecordEditor]=useState<RecordRow|null|"new">(null),[recordForm,setRecordForm]=useState(recordBlank),[providerEditor,setProviderEditor]=useState<Provider|null|"new">(null),[providerForm,setProviderForm]=useState(providerBlank),[courseEditor,setCourseEditor]=useState<Course|null|"new">(null),[courseForm,setCourseForm]=useState(courseBlank);
 const load=useCallback(async()=>{setLoading(true);setError("");try{const[a,b,c,d]=await Promise.all([fetch("/api/training"),fetch("/api/staff?status=active"),fetch("/api/training/configuration"),fetch("/api/training/matrix")]),config=await json(c);setRows(await json(a));setStaff(await json(b));setProviders(config.providers);setCourses(config.courses);setRoles(config.roles);setMatrix(await json(d));}catch(e){setError(e instanceof Error?e.message:"Unable to load training.");}finally{setLoading(false)}},[]);useEffect(()=>{void load()},[load]);
 function openRecord(row?:RecordRow,staffId="",courseId=""){const course=courses.find(x=>x.id===(row?.courseId||courseId));setRecordEditor(row||"new");setRecordForm(row?{staffId:row.staffId,courseId:row.courseId||"",providerId:row.providerId||"",courseName:row.courseName,provider:row.provider||"",certificateReference:row.certificateReference||"",completedDate:row.completedDate.slice(0,10),expiryDate:row.expiryDate?.slice(0,10)||"",mandatory:row.mandatory,notes:row.notes||""}:{...recordBlank,staffId,courseId,courseName:course?.name||""});}
 async function saveRecord(e:FormEvent){e.preventDefault();try{const isNew=recordEditor==="new";await json(await fetch(isNew?"/api/training":`/api/training/${(recordEditor as RecordRow).id}`,{method:isNew?"POST":"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({...recordForm,courseId:recordForm.courseId||null,providerId:recordForm.providerId||null,provider:recordForm.provider||null,certificateReference:recordForm.certificateReference||null,expiryDate:recordForm.expiryDate||null,notes:recordForm.notes||null})}));setRecordEditor(null);await load();}catch(e){setError(e instanceof Error?e.message:"Unable to save record.")}}
 async function archiveRecord(row:RecordRow){if(!await appConfirm(`Archive ${row.courseName} for ${row.staff.displayName}?`))return;await fetch(`/api/training/${row.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({active:false})});await load();}
 function openProvider(row?:Provider){setProviderEditor(row||"new");setProviderForm(row?Object.fromEntries(Object.keys(providerBlank).map(key=>[key,String(row[key as keyof Provider]||"")])) as typeof providerBlank:providerBlank);}
 async function saveProvider(e:FormEvent){e.preventDefault();try{await json(await fetch("/api/training/configuration",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({kind:"provider",id:providerEditor==="new"?undefined:providerEditor?.id,...providerForm})}));setProviderEditor(null);await load();}catch(e){setError(e instanceof Error?e.message:"Unable to save provider.")}}
 function openCourse(row?:Course){setCourseEditor(row||"new");setCourseForm(row?{name:row.name,category:row.category,description:row.description||"",renewalMonths:String(row.renewalMonths||""),warningDays:String(row.warningDays),providerIds:row.providers.map(x=>x.provider.id),requirementRules:{...row.requirementRules}}:{...courseBlank,requirementRules:Object.fromEntries(roles.map(role=>[role,"CONDITIONAL"]))});}
 async function saveCourse(e:FormEvent){e.preventDefault();try{await json(await fetch("/api/training/configuration",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({kind:"course",id:courseEditor==="new"?undefined:courseEditor?.id,...courseForm,renewalMonths:courseForm.renewalMonths?Number(courseForm.renewalMonths):null,warningDays:Number(courseForm.warningDays)})}));setCourseEditor(null);await load();}catch(e){setError(e instanceof Error?e.message:"Unable to save course.")}}
 async function install(){try{await json(await fetch("/api/training/configuration",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"install-framework"})}));await load();}catch(e){setError(e instanceof Error?e.message:"Unable to load framework.")}}
 const filtered=useMemo(()=>rows.filter(row=>`${row.staff.displayName} ${row.courseName} ${row.provider||""}`.toLowerCase().includes(search.toLowerCase())),[rows,search]);
 return <div className="training-workspace"><nav className="training-tabs"><Tab active={tab==="matrix"} onClick={()=>setTab("matrix")} icon={<Grid3X3/>}>Training matrix</Tab><Tab active={tab==="records"} onClick={()=>setTab("records")} icon={<BookOpen/>}>Records</Tab><Tab active={tab==="courses"} onClick={()=>setTab("courses")} icon={<BookOpen/>}>Courses</Tab><Tab active={tab==="providers"} onClick={()=>setTab("providers")} icon={<Building2/>}>Providers</Tab></nav>{error&&<div className="alert alert-error">{error}</div>}{loading&&<div className="card empty"><span className="spinner"/> Loading training information...</div>}
 {!loading&&tab==="matrix"&&<MatrixView matrix={matrix} courses={courses} select={openRecord} install={install}/>}
 {!loading&&tab==="records"&&<><div className="toolbar"><label className="training-search"><Search/><input className="field" placeholder="Search training records" value={search} onChange={e=>setSearch(e.target.value)}/></label><button className="btn primary" onClick={()=>openRecord()}><Plus/>Add training record</button></div><section className="card table-wrap">{filtered.length?<table className="table"><thead><tr><th>Staff</th><th>Course</th><th>Provider</th><th>Completed</th><th>Renewal</th><th>Evidence</th><th>Actions</th></tr></thead><tbody>{filtered.map(row=><tr key={row.id}><td><b>{row.staff.displayName}</b></td><td>{row.course?.name||row.courseName}</td><td>{row.trainingProvider?.name||row.provider||"-"}</td><td>{date(row.completedDate)}</td><td>{date(row.expiryDate)}</td><td>{row.certificateReference||"-"}</td><td><button className="icon-btn" onClick={()=>openRecord(row)}><Pencil/></button><button className="icon-btn danger" onClick={()=>archiveRecord(row)}><Archive/></button></td></tr>)}</tbody></table>:<div className="empty">No training records have been added yet.</div>}</section></>}
 {!loading&&tab==="courses"&&<><Heading title="Course catalogue" text="Define renewals, role requirements and approved providers."><>{!courses.length&&<button className="btn secondary" onClick={install}>Load STARS training framework</button>} <button className="btn primary" onClick={()=>openCourse()}><Plus/>Add course</button></></Heading><div className="training-card-grid">{courses.map(course=><article className="card training-card" key={course.id}><span className="badge badge-neutral">{course.category}</span><h3>{course.name}</h3><p>{course.description||"No course description recorded."}</p><div className="muted">Renew every {course.renewalMonths||"not set"} months · warn {course.warningDays} days before</div><div className="muted">{course.providers.length?course.providers.map(x=>x.provider.name).join(", "):"No approved provider linked"}</div><button className="btn secondary" onClick={()=>openCourse(course)}><Pencil/>Edit course</button></article>)}</div></>}
 {!loading&&tab==="providers"&&<><Heading title="Training providers" text="Keep booking contacts and evidence of provider suitability together."><button className="btn primary" onClick={()=>openProvider()}><Plus/>Add provider</button></Heading><div className="training-card-grid">{providers.map(provider=><article className="card training-card" key={provider.id}><h3>{provider.name}</h3><p>{provider.contactName||"No contact named"}{provider.email?` · ${provider.email}`:""}{provider.phone?` · ${provider.phone}`:""}</p><b>Credentials</b><p>{provider.credentialsSummary||"Not recorded"}</p><div className="muted">{provider.accreditationBody||"No accreditation body"}{provider.accreditationReference?` · ${provider.accreditationReference}`:""}{provider.accreditationExpiry?` · expires ${date(provider.accreditationExpiry)}`:""}</div><button className="btn secondary" onClick={()=>openProvider(provider)}><Pencil/>Edit provider</button></article>)}</div></>}
 {recordEditor&&<RecordModal form={recordForm} set={setRecordForm} staff={staff} courses={courses} providers={providers} close={()=>setRecordEditor(null)} submit={saveRecord}/>} {providerEditor&&<ProviderModal form={providerForm} set={setProviderForm} close={()=>setProviderEditor(null)} submit={saveProvider}/>} {courseEditor&&<CourseModal form={courseForm} set={setCourseForm} roles={roles} providers={providers} close={()=>setCourseEditor(null)} submit={saveCourse}/>}</div>;
}
function Tab({active,onClick,icon,children}:{active:boolean;onClick:()=>void;icon:ReactNode;children:ReactNode}){return <button className={active?"active":""} onClick={onClick}>{icon}{children}</button>}
function Heading({title,text,children}:{title:string;text:string;children:ReactNode}){return <div className="training-section-head"><div><h2>{title}</h2><p className="muted">{text}</p></div><div>{children}</div></div>}
function MatrixView({matrix,courses,select,install}:{matrix:Matrix|null;courses:Course[];select:(row?:RecordRow,staffId?:string,courseId?:string)=>void;install:()=>void}){if(!courses.length)return <div className="card empty"><h2>Set up the training matrix</h2><p>Load the supplied framework. This creates course definitions only and does not alter staff or training records.</p><button className="btn primary" onClick={install}>Load STARS training framework</button></div>;if(!matrix)return null;return <><div className="matrix-summary">{[["CURRENT","Current"],["DUE_SOON","Due within warning period"],["EXPIRED","Expired"],["MISSING","Required and missing"]].map(([key,label])=><div className={`card matrix-stat state-${key.toLowerCase()}`} key={key}><b>{matrix.counts[key]||0}</b><span>{label}</span></div>)}</div><p className="muted">Select a cell to add or update a record. Requirements follow each staff member’s job role.</p><div className="card matrix-wrap"><table className="training-matrix"><thead><tr><th>Staff member</th><th>Role</th>{matrix.courses.map(course=><th key={course.id}>{course.name}</th>)}</tr></thead><tbody>{matrix.rows.map(row=><tr key={row.id}><th>{row.name}</th><td>{row.role}</td>{row.cells.map(cell=><td key={cell.courseId}><button title={`${labels[cell.state]||cell.state}${cell.expiryDate?` - ${date(cell.expiryDate)}`:""}`} className={`matrix-cell state-${cell.state.toLowerCase()}`} onClick={()=>select(undefined,row.id,cell.courseId)}>{cell.state==="CURRENT"?"✓":cell.state==="DUE_SOON"?"!":cell.state==="EXPIRED"?"×":cell.state==="MISSING"?"•":"-"}</button></td>)}</tr>)}</tbody></table></div></>}
function Shell({title,close,children}:{title:string;close:()=>void;children:ReactNode}){return <div className="modal-backdrop"><div className="modal training-modal"><div className="training-modal-head"><h2>{title}</h2><button className="icon-btn" onClick={close}><X/></button></div>{children}</div></div>}
function Actions({close}:{close:()=>void}){return <div className="training-actions"><button type="button" className="btn secondary" onClick={close}>Cancel</button><button className="btn primary">Save</button></div>}
function RecordModal({form,set,staff,courses,providers,close,submit}:{form:typeof recordBlank;set:(x:typeof recordBlank)=>void;staff:Staff[];courses:Course[];providers:Provider[];close:()=>void;submit:(e:FormEvent)=>void}){const allowed=courses.find(x=>x.id===form.courseId)?.providers.map(x=>x.provider.id)||[];return <Shell title="Training record" close={close}><form onSubmit={submit} className="form-grid"><label>Staff member<select className="field" required value={form.staffId} onChange={e=>set({...form,staffId:e.target.value})}><option value="">Select staff</option>{staff.map(x=><option key={x.id} value={x.id}>{x.displayName}</option>)}</select></label><label>Course<select className="field" required value={form.courseId} onChange={e=>{const course=courses.find(x=>x.id===e.target.value);set({...form,courseId:e.target.value,courseName:course?.name||"",providerId:""})}}><option value="">Select course</option>{courses.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Provider<select className="field" value={form.providerId} onChange={e=>set({...form,providerId:e.target.value,provider:providers.find(x=>x.id===e.target.value)?.name||""})}><option value="">Not recorded</option>{providers.filter(x=>!allowed.length||allowed.includes(x.id)).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Certificate / evidence reference<input className="field" value={form.certificateReference} onChange={e=>set({...form,certificateReference:e.target.value})}/></label><label>Completed date<input className="field" type="date" required value={form.completedDate} onChange={e=>set({...form,completedDate:e.target.value})}/></label><label>Expiry / renewal date<input className="field" type="date" value={form.expiryDate} onChange={e=>set({...form,expiryDate:e.target.value})}/></label><label className="full">Notes<textarea className="field" value={form.notes} onChange={e=>set({...form,notes:e.target.value})}/></label><Actions close={close}/></form></Shell>}
function ProviderModal({form,set,close,submit}:{form:typeof providerBlank;set:(x:typeof providerBlank)=>void;close:()=>void;submit:(e:FormEvent)=>void}){return <Shell title="Training provider" close={close}><form onSubmit={submit} className="form-grid">{[["name","Provider name"],["contactName","Booking contact"],["email","Email"],["phone","Telephone"],["website","Website"],["accreditationBody","Accreditation / awarding body"],["accreditationReference","Accreditation reference"],["evidenceReference","Evidence reference"]].map(([key,label])=><label key={key}>{label}<input className="field" required={key==="name"} value={form[key as keyof typeof form]} onChange={e=>set({...form,[key]:e.target.value})}/></label>)}<label>Accreditation expiry<input className="field" type="date" value={form.accreditationExpiry} onChange={e=>set({...form,accreditationExpiry:e.target.value})}/></label><label className="full">Credentials and suitability<textarea className="field" value={form.credentialsSummary} onChange={e=>set({...form,credentialsSummary:e.target.value})}/></label><label className="full">Booking notes<textarea className="field" value={form.bookingNotes} onChange={e=>set({...form,bookingNotes:e.target.value})}/></label><Actions close={close}/></form></Shell>}
function CourseModal({form,set,roles,providers,close,submit}:{form:typeof courseBlank;set:(x:typeof courseBlank)=>void;roles:string[];providers:Provider[];close:()=>void;submit:(e:FormEvent)=>void}){return <Shell title="Training course" close={close}><form onSubmit={submit} className="form-grid"><label>Course name<input className="field" required value={form.name} onChange={e=>set({...form,name:e.target.value})}/></label><label>Category<input className="field" required value={form.category} onChange={e=>set({...form,category:e.target.value})}/></label><label>Renew every (months)<input className="field" type="number" min="1" max="120" value={form.renewalMonths} onChange={e=>set({...form,renewalMonths:e.target.value})}/></label><label>Upcoming warning (days)<input className="field" type="number" min="1" max="365" required value={form.warningDays} onChange={e=>set({...form,warningDays:e.target.value})}/></label><label className="full">Description<textarea className="field" value={form.description} onChange={e=>set({...form,description:e.target.value})}/></label><fieldset className="full training-fieldset"><legend>Role requirements</legend>{roles.map(role=><label key={role}>{role}<select className="field" value={form.requirementRules[role]||"CONDITIONAL"} onChange={e=>set({...form,requirementRules:{...form.requirementRules,[role]:e.target.value as Requirement}})}><option value="REQUIRED">Required</option><option value="CONDITIONAL">Conditional</option><option value="NOT_REQUIRED">Not required</option></select></label>)}</fieldset><fieldset className="full training-fieldset"><legend>Approved providers</legend>{providers.map(provider=><label className="training-check" key={provider.id}><input type="checkbox" checked={form.providerIds.includes(provider.id)} onChange={e=>set({...form,providerIds:e.target.checked?[...form.providerIds,provider.id]:form.providerIds.filter(id=>id!==provider.id)})}/>{provider.name}</label>)}</fieldset><Actions close={close}/></form></Shell>}
