"use client";
import Link from "next/link";
import {ArrowLeft,ArrowRight,Camera,Check,CheckCircle2,ChevronRight,ClipboardCheck,Fuel,Lightbulb,CircleDot,Eye,Accessibility,BriefcaseMedical,Cloud,Save,WifiOff,Info,TriangleAlert,Trash2} from "lucide-react";
import {normaliseMileage,formatVehicleDate} from "@/lib/vehicle-presentation";
import {useCallback,useEffect,useRef,useState} from "react";
import {vehicleDay} from "@/lib/vehicle-day";
import {checklist,DECLARATION} from "@/lib/vehicle-checklist";
import {loadLocal,saveLocal,amendDraft,rollDailyDraft,unfinishedChecks,latestDailyDraft,syncDraft,preparePhoto,type Draft,type Vehicle} from "@/lib/vehicle-local";
import styles from "./vehicle-check.module.css";
function Photo({blob}:{blob:Blob}){const [url,setUrl]=useState("");useEffect(()=>{const u=URL.createObjectURL(blob);setUrl(u);return()=>URL.revokeObjectURL(u)},[blob]);return url?<img className={styles.photo} src={url} alt="Vehicle evidence preview"/>:null;}
function PhotoPicker({label,onFile,disabled=false}:{label:string;onFile:(file:File|undefined)=>void;disabled?:boolean}){const input=useRef<HTMLInputElement>(null);return <><input ref={input} className={styles.fileInput} tabIndex={-1} type="file" aria-label={label} accept="image/jpeg,image/png" capture="environment" disabled={disabled} onChange={e=>{onFile(e.target.files?.[0]);e.target.value=""}}/><button type="button" className={styles.photoButton} disabled={disabled} onClick={()=>input.current?.click()}><Camera size={20}/>{label}</button></>}
const sectionIcons=[Fuel,Lightbulb,CircleDot,Eye,Accessibility,BriefcaseMedical];
export function VehicleCheckApp({staffArea=false,driverOnly=false}:{staffArea?:boolean;driverOnly?:boolean}){
 const apiBase=driverOnly?"/api/driver/vehicle":staffArea?"/api/staff-area/vehicle":"/api/fleet";
 const [user,setUser]=useState<{id:string;name:string}>(),[vehicles,setVehicles]=useState<Vehicle[]>([]),[draft,setDraft]=useState<Draft>(),[loading,setLoading]=useState(true),[message,setMessage]=useState(""),[saveState,setSaveState]=useState(""),[offline,setOffline]=useState(false),[offlineReady,setOfflineReady]=useState(false),[defectKey,setDefectKey]=useState<string>(),[pin,setPin]=useState(""),[identifier,setIdentifier]=useState(""),[password,setPassword]=useState(""),[busy,setBusy]=useState(false);
 const [unfinished,setUnfinished]=useState<Draft[]>([]);
 const [mileageEntry,setMileageEntry]=useState<{id:string;text:string}>();
 const observedDay=useRef(vehicleDay());
 const defectDialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{if(defectKey&&!defectDialog.current?.open)defectDialog.current?.showModal()},[defectKey]);
 const current=useRef<Draft|undefined>(undefined),syncing=useRef(false),saveChain=useRef(Promise.resolve());
 const store=useCallback((d:Draft)=>{current.current=d;setDraft(d);setSaveState("Saving locally…");saveChain.current=saveChain.current.then(()=>saveLocal(`draft:${d.userId}`,d)).then(()=>setSaveState(d.state==="PENDING"?"Awaiting sync":"Saved on this device")).catch(()=>setSaveState("LOCAL SAVE FAILED — keep this page open and retry. Storage may be full."));},[]);
 const load=useCallback(async()=>{setLoading(true);let canUseCache=false;try{const r=await fetch(`${apiBase}/vehicles`,{cache:"no-store"}).catch(error=>{canUseCache=true;throw error});if(r.status>=500)canUseCache=true;if(!r.ok){setUser(undefined);throw Error((await r.json()).error);}const d=await r.json();setUser(d.user);setVehicles(d.rows);if(!staffArea&&!driverOnly)await saveLocal("cached",d);const saved=await loadLocal<Draft>(`draft:${d.user.id}`);let daily=await rollDailyDraft(saved||undefined,d.rows);const selected=daily?.vehicle||d.rows.length===1&&d.rows[0];if(selected&&(!saved||saved.state==="SYNCED"||vehicleDay(saved.clientStartedAt)!==vehicleDay()))daily=await latestDailyDraft(d.user,selected,apiBase);if(daily)await saveLocal(`draft:${d.user.id}`,daily);current.current=daily;setDraft(daily);setUnfinished(await unfinishedChecks(d.user.id));observedDay.current=vehicleDay();setOffline(false);setMessage("");}catch(e){if(!staffArea&&!driverOnly&&(canUseCache||!navigator.onLine)){const cached=await loadLocal<{user:{id:string;name:string};rows:Vehicle[]}>("cached");if(cached){setUser(cached.user);setVehicles(cached.rows);const saved=await loadLocal<Draft>(`draft:${cached.user.id}`);const daily=await rollDailyDraft(saved,cached.rows);current.current=daily;setDraft(daily);setUnfinished(await unfinishedChecks(cached.user.id));observedDay.current=vehicleDay();}setOffline(true);}setMessage(e instanceof Error?e.message:"Unable to load vehicles.");}finally{setLoading(false)}},[apiBase,staffArea,driverOnly]);
 const sync=useCallback(async()=>{const d=current.current;if(!d||d.state!=="PENDING"||syncing.current||!navigator.onLine)return;syncing.current=true;setBusy(true);setSaveState("Uploading photographs and check…");try{await saveChain.current;const saved=await syncDraft(d,apiBase);current.current=saved;setDraft(saved);setUnfinished(await unfinishedChecks(d.userId));setSaveState("Synced — server confirmed");setMessage("");}catch(e){setSaveState("Sync failed — saved on this device");setMessage(e instanceof Error?e.message:"Sync failed. Sign in as the same account and retry.")}finally{syncing.current=false;setBusy(false)}},[apiBase]);
 useEffect(()=>{void load();if(!("serviceWorker" in navigator))return;
 if(driverOnly)return;
 if(staffArea){void navigator.serviceWorker.register("/staff/sw.js",{scope:"/staff/"});return;}
 let disposed=false;
 const cacheAssets=async()=>{try{const registration=await navigator.serviceWorker.ready;if(disposed)return;const channel=new MessageChannel();const timer=setTimeout(()=>channel.port1.close(),15000);channel.port1.onmessage=e=>{clearTimeout(timer);if(!disposed)setOfflineReady(e.data.ready===true);channel.port1.close()};const urls=Array.from(document.querySelectorAll("script[src],link[href]")).map(el=>el.getAttribute("src")||el.getAttribute("href")).filter(Boolean);registration.active?.postMessage({type:"CACHE_VEHICLE_ASSETS",urls},[channel.port2])}catch{if(!disposed)setOfflineReady(false)}};
 navigator.serviceWorker.addEventListener("controllerchange",cacheAssets);
 void navigator.serviceWorker.register("/sw.js").then(cacheAssets).catch(()=>{if(!disposed)setOfflineReady(false)});
 return()=>{disposed=true;navigator.serviceWorker.removeEventListener("controllerchange",cacheAssets)};
 },[load,staffArea,driverOnly]);
 useEffect(()=>{const online=()=>{setOffline(false);void sync()},off=()=>setOffline(true),focus=()=>{if(busy||loading||syncing.current)return;if(observedDay.current!==vehicleDay()){void saveChain.current.then(()=>load())}else void sync()};window.addEventListener("online",online);window.addEventListener("offline",off);window.addEventListener("focus",focus);const timer=setInterval(focus,30000);return()=>{window.removeEventListener("online",online);window.removeEventListener("offline",off);window.removeEventListener("focus",focus);clearInterval(timer)}},[sync,load,busy,loading]);
 useEffect(()=>{const leave=(e:BeforeUnloadEvent)=>{if(current.current&&current.current.state!=="SYNCED"){e.preventDefault();e.returnValue=""}};window.addEventListener("beforeunload",leave);return()=>window.removeEventListener("beforeunload",leave)},[]);
 function update(extra:Partial<Draft>){if(draft&&draft.state==="DRAFT")store({...draft,...extra})}
 function answer(key:string,extra:Partial<Draft["answers"][number]>){if(!draft)return;const previous=draft.answers.find(a=>a.key===key)||{key,response:"PASS" as const,notes:"",imageIds:[],secured:false};update({answers:[...draft.answers.filter(a=>a.key!==key),{...previous,...extra}]})}
 async function capture(file:File|undefined,key?:string){if(!file||!draft)return;setBusy(true);try{const blob=await preparePhoto(file),id=crypto.randomUUID(),latest=current.current!;const images=[...latest.images,{id,blob}];if(key){const a=latest.answers.find(a=>a.key===key)!;if(a.imageIds.length>=4)throw Error("Up to four photographs per defect.");store({...latest,images,answers:latest.answers.map(a=>a.key===key?{...a,imageIds:[...a.imageIds,id]}:a)})}else store({...latest,images,initialImageId:id});}catch(e){setMessage(e instanceof Error?e.message:"Camera failed. Please try again.")}finally{setBusy(false)}}
 async function login(usePin:boolean){setBusy(true);setMessage("");try{const headers:Record<string,string>={"content-type":"application/json"};if(usePin){headers["x-device-id"]=localStorage.getItem("pulse-device-id")||"";headers.authorization=`Bearer ${localStorage.getItem("pulse-device-token")||""}`}const r=await fetch(usePin?"/api/fleet/pin":"/api/auth/login",{method:"POST",headers,body:JSON.stringify(usePin?{pin}:{identifier,password})});if(!r.ok)throw Error((await r.json()).error);setPin("");setPassword("");await load();void sync();}catch(e){setMessage(e instanceof Error?e.message:"Sign-in failed")}finally{setBusy(false)}}
 useEffect(()=>{window.scrollTo({top:0,behavior:"instant"})},[draft?.step,draft?.state]);
 const sections=draft?checklist(draft.vehicle.fuelType,draft.vehicle.config):[],section=draft&&draft.step>0&&draft.step<7?sections[draft.step-1]:null;
 const unsafe=!!draft&&(draft.result==="UNSAFE"||draft.vehicle.status==="OUT_OF_SERVICE"||draft.answers.some(a=>a.response==="DEFECT"&&(a.severity==="CRITICAL"||sections.flatMap(s=>s.items).find(i=>i.key===a.key)?.stopUse)));
 const complete=(items:ReturnType<typeof checklist>[number]["items"])=>items.every(i=>draft?.answers.some(a=>a.key===i.key&&(a.response!=="DEFECT"||(!!a.notes.trim()&&!!a.severity&&a.imageIds.length>0))));
 const mileageText=draft?(mileageEntry?.id===draft.id?mileageEntry.text:draft.mileage?String(draft.mileage):""):"";
 function next(){if(!draft)return;if(draft.step===0&&(!mileageText||!draft.initialImageId||!Number.isInteger(draft.mileage)||draft.mileage<draft.vehicle.mileage)){setMessage("Enter mileage at or above the previous reading and take the vehicle photograph.");return}if(section&&!complete(section.items)){setMessage("Answer every item. Each defect needs severity, a description and a photograph.");return}setMessage("");update({step:draft.step+1})}
 const submitReason=busy?"Please wait while your check is saved.":!draft?.declaration?"Tick the declaration to submit your check.":!draft.initialImageId?"Add a vehicle photograph before submitting.":!sections.every(s=>complete(s.items))?"Complete every section before submitting.":"";
 function photos(ids:string[]){return ids.map(id=>{const image=draft?.images.find(i=>i.id===id);return image?<Photo key={id} blob={image.blob}/>:<img key={id} className={styles.photo} src={`${apiBase}/evidence?id=${id}`} alt="Previously submitted vehicle evidence"/>})}
 function back(){if(draft?.state==="DRAFT"&&draft.step>0)update({step:draft.step-1});else if(!driverOnly)window.location.assign(staffArea?"/staff/":"/staff-portal");else window.history.back()}
 return <main className={styles.app}>
 <header className={styles.header}><button type="button" className={styles.backIcon} aria-label="Back" onClick={back}><ArrowLeft size={20}/></button><div><span className={styles.brand}>STARS CONNECT</span><h1>Vehicle Check</h1>{draft&&<p>{draft.vehicle.name} · {draft.vehicle.registration}</p>}</div><ClipboardCheck className={styles.headerIcon} size={26}/></header>
 {draft&&<div className={styles.metadata}><span>{draft.staffName}</span><span>{formatVehicleDate(draft.clientStartedAt)}</span></div>}
 {offlineReady&&user&&<small className={styles.muted}>Available offline on this device</small>}
 {offline&&<p className={styles.info}><WifiOff size={18}/>Offline — check you are {user?.name}. Saved checks reach management after syncing.</p>}
 {message&&<p role="alert" className={styles.error}>{message}</p>}
 {user&&unfinished.filter(d=>d.id!==draft?.id).map(d=><section className={styles.card} key={d.id}><b>Unfinished check · {formatVehicleDate(d.clientStartedAt)}</b><p>{d.vehicle.name} · Answers and photographs saved.</p><button className="btn secondary" disabled={busy||loading} onClick={async()=>{await saveChain.current;const active=current.current;if(active&&active.id!==d.id&&active.state!=="SYNCED")await saveLocal(`unfinished:${active.userId}:${active.id}`,active);store(d);setUnfinished(await unfinishedChecks(d.userId))}}>Resume saved check</button></section>)}
 {loading?<p>Loading vehicles…</p>:!user&&driverOnly?<section className={styles.card}><h2>Open your vehicle-check link</h2><p>Use the link or QR code provided by STARS. Ask management for a new link if it no longer works.</p></section>:!user&&staffArea?<section className={styles.card}><h2>Staff sign-in required</h2><p>Sign in with your existing PIN. Management must enable vehicle check access.</p><Link className="btn primary" href="/staff/">Open STARS Staff</Link></section>:!user?<div className={styles.login}><h2>Sign in</h2><p>Use your staff PIN on a STARS tablet, or your account on your phone.</p><form onSubmit={e=>{e.preventDefault();void login(true)}}><label>Staff PIN<input type="password" inputMode="numeric" autoComplete="off" maxLength={8} value={pin} onChange={e=>setPin(e.target.value)}/></label><button className="btn primary" disabled={busy}>Continue with PIN</button></form><details><summary>Use my STARS account</summary><form onSubmit={e=>{e.preventDefault();void login(false)}}><label>Username or email<input autoComplete="username" value={identifier} onChange={e=>setIdentifier(e.target.value)}/></label><label>Password<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="btn primary" disabled={busy}>Sign in</button></form></details></div>:!draft?<><p className={styles.muted}>Checking as <b>{user.name}</b></p><h2>Choose a vehicle</h2>{!vehicles.length&&<p>No vehicles available. Ask management to add or reactivate one.</p>}{vehicles.map(v=><button key={v.id} className={`${styles.card} ${styles.vehicle}`} onClick={async()=>{try{store(await latestDailyDraft(user,v,apiBase))}catch(e){setMessage(e instanceof Error?e.message:"Unable to load today’s check.")}}}><b>{v.name}</b><span>{v.registration}</span><p>{v.status==="OUT_OF_SERVICE"?"DO NOT USE — Out of service":v.checks.length?`Checked today — ${v.checks[0].outcome.replaceAll("_"," ")}`:"Not yet checked today"}</p></button>)}</>:<>
 {unsafe&&<div role="alert" className={styles.danger}><TriangleAlert size={20}/><div><b>Do not use this vehicle</b><p>{draft.state!=="SYNCED"?"Notify management directly. This report may not have synced yet.":"Management can review this report in Fleet."}</p></div></div>}
 {draft.amendmentOf&&<p className={styles.info}><Info size={18}/>Amendment · Earlier versions and reported defects stay in the history.</p>}
 <p role="status" className={styles.status}>{offline?<WifiOff size={15}/>:draft.state==="SYNCED"?<Cloud size={15}/>:<Save size={15}/>}<span>{draft.state==="SYNCED"?"Synced — server confirmed":saveState||"Saved on this device"}</span></p>
 {draft.state!=="DRAFT"?<section className={`${styles.card} ${styles.completed}`}><CheckCircle2 size={30}/><h2>{draft.state==="SYNCED"?"Check submitted":"Saved — awaiting upload"}</h2><p>{draft.state==="SYNCED"?(draft.result==="PASSED"?"Passed":draft.result==="MINOR_DEFECTS"?"Passed with minor defects":"Unsafe — Out of service"):"Keep this check on this device until the server confirms receipt."}</p>{draft.state==="PENDING"&&<><button className="btn primary" disabled={busy} onClick={()=>void sync()}>Retry sync</button><button className="btn secondary" disabled={busy} onClick={()=>setUser(undefined)}>{driverOnly?"Reopen driver link":"Sign in again"}</button></>}{draft.state==="SYNCED"&&<>{vehicleDay(draft.clientStartedAt)===vehicleDay()&&<button className="btn primary" onClick={async()=>{try{const latest=await latestDailyDraft(user,draft.vehicle,apiBase);store(amendDraft(latest))}catch(e){setMessage(e instanceof Error?e.message:"Unable to amend check.")}}}>Edit today’s check</button>}<a className="btn secondary" href={`${driverOnly?"/driver/vehicle-check/record":staffArea?"/staff/vehicle-check/record":"/VehicleCheck/record"}?id=${draft.id}`}>View submitted check</a><button className="btn secondary" onClick={async()=>{await saveLocal(`draft:${user.id}`,null);current.current=undefined;setDraft(undefined);setUnfinished(await unfinishedChecks(user.id))}}>Choose vehicle</button></>}</section>:<>
 <div className={styles.progress}><span>Step {draft.step+1} of 8</span><h2>{draft.step===0?"Vehicle & mileage":draft.step===7?"Review & submit":section?.title}</h2><progress aria-label={`Step ${draft.step+1} of 8`} value={draft.step+1} max={8}/></div>
 {draft.step===0?<section className={styles.card}>
 <div className={styles.info}><Info size={18}/><div><b>{draft.amendmentOf?"Review your details":"Before you begin"}</b><p>{draft.amendmentOf?"Check the mileage and photograph. Replace the photo if needed.":"Confirm the vehicle, enter its current mileage and take a clear photograph showing the registration plate. Do not include clients in photographs."}</p></div></div>
 <label htmlFor="vehicle-mileage">Current mileage</label><input id="vehicle-mileage" type="text" inputMode="numeric" pattern="[0-9]*" maxLength={7} autoComplete="off" placeholder="Enter current mileage" value={mileageText} onFocus={e=>e.currentTarget.select()} onChange={e=>{const text=normaliseMileage(e.target.value);setMileageEntry({id:draft.id,text});update({mileage:Number(text)})}} aria-describedby="previous-mileage"/><p id="previous-mileage" className={styles.hint}>Previous reading: {draft.vehicle.mileage.toLocaleString("en-GB")} miles</p>
 <div className={styles.photoArea}><h3>Vehicle photograph</h3>{draft.initialImageId&&<div className={styles.preview}>{photos([draft.initialImageId])}</div>}<div className={styles.photoActions}><PhotoPicker label={draft.initialImageId?"Retake photo":"Take vehicle photo"} disabled={busy} onFile={file=>void capture(file)}/>{draft.initialImageId&&<button className={styles.removeButton} disabled={busy} onClick={()=>update({initialImageId:""})}><Trash2 size={17}/>Remove</button>}</div><p className={styles.hint}>{draft.amendmentOf?"The original photo is kept unless replaced.":"Include the registration plate. No clients in the photo."}</p></div>
 </section>:section?<section className={styles.checklist}><p className={styles.info}><Info size={18}/>{draft.step===3?"Visual checks only — not a calibrated tyre inspection.":"Only test what is safe. If unsure, report a safety-critical concern and ask management."}</p>{section.items.map(item=>{const a=draft.answers.find(a=>a.key===item.key);return <article className={`${styles.card} ${!item.applicable?styles.notApplicable:""}`} key={item.key}><h3>{item.label}</h3>{!item.applicable?<span className={styles.badge}>N/A · Not fitted or applicable</span>:<div className={styles.choices}><button aria-pressed={a?.response==="PASS"} data-pass={a?.response==="PASS"} onClick={()=>answer(item.key,{response:"PASS",severity:undefined,notes:"",imageIds:[]})}><Check size={18}/>Pass</button><button aria-pressed={a?.response==="DEFECT"} data-defect={a?.response==="DEFECT"} onClick={()=>{answer(item.key,{response:"DEFECT",severity:a?.severity||"CRITICAL"});setDefectKey(item.key)}}><TriangleAlert size={18}/>Defect</button></div>}{a?.response==="DEFECT"&&<p className={styles.defectSummary}>{a.severity==="CRITICAL"||item.stopUse?"Safety critical":"Minor defect"} · {a.notes||"Add details"} · {a.imageIds.length} photo(s)</p>}</article>})}</section>:<>
 <p className={styles.hint}>{draft.mileage.toLocaleString("en-GB")} miles · Started {new Date(draft.clientStartedAt).toLocaleTimeString("en-GB",{timeZone:"Europe/London",hour:"2-digit",minute:"2-digit"})}</p>
 <div className={styles.summary}>{(["PASS","DEFECT","NA"] as const).map((type,i)=><div key={type}><b>{draft.answers.filter(a=>a.response===type).length}</b><span>{["passed","defects","N/A"][i]}</span></div>)}</div>
 <div className={styles.reviewList}>{sections.map((s,i)=>{const Icon=sectionIcons[i],answers=draft.answers.filter(a=>s.items.some(item=>item.key===a.key)),defects=answers.filter(a=>a.response==="DEFECT").length,na=answers.filter(a=>a.response==="NA").length;return <button className={styles.reviewRow} key={s.title} onClick={()=>update({step:i+1})} aria-label={`Review ${s.title}`}><Icon size={19}/><span>{s.title}<small className={defects?styles.amberText:""}>{!complete(s.items)?"Needs attention":defects?`${defects} defect${defects===1?"":"s"}`:na?`Complete · ${na} N/A`:"Complete"}</small></span><ChevronRight size={18}/></button>})}</div>
 {draft.answers.filter(a=>a.response==="DEFECT").map(a=><article className={styles.card} key={a.key}><h3>{sections.flatMap(s=>s.items).find(i=>i.key===a.key)?.label}</h3><p className={styles.defectSummary}>{a.severity==="CRITICAL"?"Safety critical":"Minor defect"} · {a.notes}</p><div className={styles.evidenceGrid}>{photos(a.imageIds)}</div></article>)}
 <div className={`${styles.result} ${unsafe?styles.resultUnsafe:draft.answers.some(a=>a.response==="DEFECT")?styles.resultAmber:styles.resultPassed}`}>{unsafe?<TriangleAlert size={24}/>:<CheckCircle2 size={24}/>}<div><small>Overall result</small><b>{unsafe?"Do not use vehicle":draft.answers.some(a=>a.response==="DEFECT")?"Passed with defects":"Passed"}</b></div></div>
 <p className={`${styles.info} ${styles.disclaimer}`}>This records your observations. It does not certify roadworthiness or replace driver responsibility and professional maintenance.</p><label className={styles.declaration}><input type="checkbox" checked={draft.declaration} onChange={e=>update({declaration:e.target.checked})}/><span>{DECLARATION}</span></label>
 </>}
 <footer className={styles.footer}><div className={styles.footerButtons}><button className="btn secondary" disabled={busy} onClick={back}><ArrowLeft size={18}/>Back</button>{draft.step<7?<button className="btn primary" disabled={busy} onClick={next}>Continue<ArrowRight size={18}/></button>:<button className="btn primary" aria-disabled={!!submitReason} aria-describedby="submit-reason" onClick={async()=>{if(submitReason){setMessage(submitReason);return}const pending={...draft,state:"PENDING" as const};store(pending);await saveChain.current;void sync()}}>{draft.amendmentOf?"Save amendments":"Submit check"}<Check size={18}/></button>}</div>{draft.step===7&&submitReason&&<p id="submit-reason" className={styles.footerHint}>{submitReason}</p>}</footer>
 </>}
 </>}
 {defectKey&&draft&&<dialog ref={defectDialog} className={styles.sheet} aria-labelledby="defect-title" onCancel={()=>setDefectKey(undefined)}><span className={styles.brand}>VEHICLE CHECK</span><h2 id="defect-title">Report defect</h2><p className={styles.dialogItem}>{sections.flatMap(s=>s.items).find(i=>i.key===defectKey)?.label}</p><p className={styles.info}>If unsure, choose safety critical and ask management. Minor defects need attention but do not appear unsafe for the journey.</p>{(()=>{const a=draft.answers.find(a=>a.key===defectKey)!,missing=busy?"Wait for the photograph to finish saving.":!a.notes.trim()?"Describe the defect before continuing.":!a.imageIds.length?"Add a photograph of the defect.":"";return <><label>Severity<select value={a.severity} onChange={e=>answer(defectKey,{severity:e.target.value as "MINOR"|"CRITICAL"})}><option value="CRITICAL">Safety critical — do not use</option><option value="MINOR">Minor</option></select></label><label>What is wrong?<textarea autoFocus rows={3} maxLength={2000} placeholder="Describe what you found" value={a.notes} onChange={e=>answer(defectKey,{notes:e.target.value})}/></label><PhotoPicker label="Take defect photo" disabled={busy} onFile={file=>void capture(file,defectKey)}/><div className={styles.evidenceGrid}>{photos(a.imageIds)}</div><p className={styles.hint}>Avoid clients and personal information in photographs.</p><div className={styles.dialogActions}><button className="btn secondary" disabled={busy} onClick={()=>setDefectKey(undefined)}>Back</button><button className="btn primary" aria-disabled={!!missing} aria-describedby="defect-reason" onClick={()=>{if(!missing)setDefectKey(undefined)}}>Save defect</button></div>{missing&&<p id="defect-reason" className={styles.hint}>{missing}</p>}</>})()}</dialog>}
 </main>;
}
