import { NextRequest,NextResponse } from "next/server";
import { z } from "zod";
import { prisma } from "@/lib/prisma";
import { rateLimit } from "@/lib/rate-limit";
import { sha256 } from "@/lib/security";
import { audit } from "@/lib/audit";
import { requestContext } from "@/lib/api";
import { newDeviceCredential } from "@/lib/device-provisioning";
const schema=z.object({setupCode:z.string().trim().min(20).max(100),appVersion:z.string().trim().min(1).max(40).optional()});
export async function POST(req:NextRequest){const context=requestContext(req),rate=rateLimit(`provision:${context.ipAddress||"local"}`,8,60_000);if(!rate.allowed)return NextResponse.json({error:"Please wait before trying again."},{status:429});const parsed=schema.safeParse(await req.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:"The setup code is not valid."},{status:400});const record=await prisma.deviceProvisioningCode.findUnique({where:{codeHash:sha256(parsed.data.setupCode)},include:{device:true}});const now=new Date();if(!record||record.consumedAt||record.expiresAt<=now||record.device.status!=="ACTIVE"||record.device.isSeedData){await audit("DEVICE_SETUP_FAILED",{actorType:"UNKNOWN",...context});return NextResponse.json({error:"This setup code is invalid, expired or has already been used."},{status:401})}const token=newDeviceCredential();const result=await prisma.$transaction(async tx=>{const consumed=await tx.deviceProvisioningCode.updateMany({where:{id:record.id,consumedAt:null,expiresAt:{gt:now}},data:{consumedAt:now}});if(consumed.count!==1)throw new Error("SETUP_CODE_ALREADY_USED");return tx.device.update({where:{id:record.deviceId},data:{tokenHash:sha256(token),tokenRotatedAt:now,lastSeenAt:now,appVersion:parsed.data.appVersion||record.device.appVersion}})}).catch(()=>null);if(!result)return NextResponse.json({error:"This setup code has already been used."},{status:409});await audit("DEVICE_SETUP_COMPLETED",{actorType:"DEVICE",deviceId:result.id,entityType:"Device",entityId:result.id,afterValue:{name:result.name,appVersion:result.appVersion},...context});return NextResponse.json({id:result.id,name:result.name,token})}