import{mkdir,readFile,writeFile}from"node:fs/promises";import path from"node:path";import{helpWorkflows}from"../src/lib/help-workflows";
function markdown(item:(typeof helpWorkflows)[number]){return`<!-- Generated by scripts/generate-help-knowledge.ts. Edit src/lib/help-workflows.ts instead. -->
# ${item.title}

**Route:** \`${item.route}\`

${item.purpose}

## Before you begin
${item.before.map(x=>`- ${x}`).join("\n")}

## Steps
${item.steps.map((x,i)=>`${i+1}. **${x.title}:** ${x.instruction}`).join("\n")}

## Expected outcome
${item.outcome}

## Warnings
${item.warnings.map(x=>`- ${x}`).join("\n")}

## Common mistakes
${item.mistakes.map(x=>`- ${x}`).join("\n")}

## If it does not work
${item.recovery.map(x=>`- ${x}`).join("\n")}

## Questions
${item.faq.map(x=>`### ${x.question}\n${x.answer}`).join("\n\n")}
`}
async function main(){const root=process.cwd(),directory=path.join(root,"knowledge","workflows"),check=process.argv.includes("--check");await mkdir(directory,{recursive:true});for(const item of helpWorkflows){const file=path.join(directory,`${item.id}.md`),content=markdown(item);if(check){const current=await readFile(file,"utf8").catch(()=>null);if(current!==content)throw new Error(`${item.id}.md is not current`)}else await writeFile(file,content,"utf8")}const catalog=JSON.stringify({generatedFrom:"src/lib/help-workflows.ts",workflows:helpWorkflows},null,2)+"\n",catalogFile=path.join(directory,"catalog.json");if(check){if(await readFile(catalogFile,"utf8").catch(()=>null)!==catalog)throw new Error("catalog.json is not current")}else await writeFile(catalogFile,catalog,"utf8");console.log(`${helpWorkflows.length} workflow topics ${check?"verified":"generated"}.`)}
void main().catch(error=>{console.error(error);process.exitCode=1});
