import { NextRequest,NextResponse } from "next/server";
import { z } from "zod";
import { prisma } from "@/lib/prisma";
import { withRole,jsonError,requestContext } from "@/lib/api";
import { audit } from "@/lib/audit";
import { issueSetupCode,placeholderCredentialHash } from "@/lib/device-provisioning";
type Params={params:Promise<{id:string}>};
const schema=z.discriminatedUnion("action",[z.object({action:z.literal("rename"),name:z.string().trim().min(2).max(120).refine(value=>!/[<>]/.test(value))}),z.object({action:z.literal("rotate")}),z.object({action:z.literal("revoke")}),z.object({action:z.literal("settings"),deviceType:z.enum(["KIOSK_TABLET","MANAGER_DESKTOP"]),showBatteryStatus:z.boolean()})]);
export async function PATCH(req:NextRequest,{params}:Params){return withRole(req,"ADMINISTRATOR",async user=>{const{id}=await params,parsed=schema.safeParse(await req.json().catch(()=>null));if(!parsed.success)return jsonError("Invalid device action.",422);const before=await prisma.device.findUnique({where:{id}});if(!before)return jsonError("Device not found.",404);if(before.isSeedData)return jsonError("Seeded demonstration devices cannot be activated. Provision a new real device instead.",409);let setup:undefined|{setupCode:string;expiresAt:Date};let after;
 if(parsed.data.action==="settings")after=await prisma.device.update({where:{id},data:{deviceType:parsed.data.deviceType,showBatteryStatus:parsed.data.showBatteryStatus}});
 else if(parsed.data.action==="rename")after=await prisma.device.update({where:{id},data:{name:parsed.data.name}});
 else if(parsed.data.action==="revoke")after=await prisma.$transaction(async tx=>{await tx.deviceProvisioningCode.updateMany({where:{deviceId:id,consumedAt:null},data:{consumedAt:new Date()}});return tx.device.update({where:{id},data:{status:"REVOKED",revokedAt:new Date(),tokenHash:placeholderCredentialHash(),pendingEventCount:0}})});
 else {const result=await prisma.$transaction(async tx=>{const device=await tx.device.update({where:{id},data:{status:"ACTIVE",revokedAt:null,tokenHash:placeholderCredentialHash(),tokenRotatedAt:new Date(),lastSeenAt:null,lastSyncAt:null,pendingEventCount:0,currentCursor:0}});const code=await issueSetupCode(id,user.id,tx);return{device,code}});after=result.device;setup=result.code}
 const auditAction=parsed.data.action==="rename"?"DEVICE_RENAMED":parsed.data.action==="rotate"?"DEVICE_CREDENTIAL_ROTATED":parsed.data.action==="settings"?"DEVICE_SETTINGS_CHANGED":"DEVICE_REVOKED";await audit(auditAction,{actorType:"USER",actorId:user.id,entityType:"Device",entityId:id,beforeValue:{name:before.name,status:before.status,deviceType:before.deviceType,showBatteryStatus:before.showBatteryStatus},afterValue:{name:after.name,status:after.status,deviceType:after.deviceType,showBatteryStatus:after.showBatteryStatus,...(setup?{setupCodeExpiresAt:setup.expiresAt}:{})},...requestContext(req)});return NextResponse.json({device:{id:after.id,name:after.name,status:after.status,deviceType:after.deviceType,showBatteryStatus:after.showBatteryStatus},...setup})})}